# OLD VERSION

In [5]:
import pandas as pd
import lightkurve as lk
import time

In [6]:
# load data from .csv
table = pd.read_csv("TESS_M=0.4_RP=15.csv")

In [7]:
# for now do 20 because all would take long time
subset = table.head(20)

In [8]:
rows = []

In [9]:
# loops .csv
for id, ra, dec in zip(subset['source_id'], subset['ra'], subset['dec']):
    print(f"Checking source_id {id} (RA={ra}, Dec={dec})")
    try:
        # goes through TESS Full Frame Image (FFI)
        search = lk.search_tesscut('%s %s' % (ra, dec))
        for values in search:
            tab = values.table

            # get sector (either sequence_number/sector)
            if "sequence_number" in tab.colnames:
                sector = tab["sequence_number"][0]
            elif "sector" in tab.colnames:
                sector = tab["sector"][0]
            #else:
              #  sector = None

            # get exposure time
            exptime = tab["exptime"][0] 
            
            # append
            rows.append({
                "ID": id,
                "Sector": sector,
                "Exposure_Time": exptime
            })
    except Exception as e:
        print(f"Error for {id}: {e}")

Checking source_id 31958852451968 (RA=44.855783116029166, Dec=0.4211441654503658)
Checking source_id 77863462880768 (RA=44.660730046322826, Dec=0.5174706461824936)
Checking source_id 97551592960640 (RA=44.71163306521175, Dec=0.6747353569305051)
Checking source_id 110951890948096 (RA=44.96551311298629, Dec=0.771972846155539)
Checking source_id 115899693267968 (RA=45.1410279662417, Dec=0.8430052599114634)
Checking source_id 123424475948672 (RA=44.8000069221394, Dec=0.7794933038508934)
Checking source_id 154829276705920 (RA=45.79773407480096, Dec=0.9005394643362447)
Checking source_id 255709468513920 (RA=45.91261574351641, Dec=1.4039870019524443)
Checking source_id 290653322568704 (RA=44.44850159775912, Dec=0.7917886784873427)
Checking source_id 319545567090560 (RA=44.7927374760415, Dec=1.034519863807558)
Checking source_id 339993906853248 (RA=44.36039043546913, Dec=1.2086815246994866)
Checking source_id 435754497122304 (RA=45.051993502946864, Dec=1.4570431652076004)
Checking source_id 452212812313984 (RA=45.0349266115007, Dec=1.6364715669582413)
Checking source_id 473447130640640 (RA=45.56798124241752, Dec=1.8530268562479224)
Checking source_id 559483915442816 (RA=44.9305841009936, Dec=2.2485996306597062)
Checking source_id 596798591393792 (RA=46.437702757259544, Dec=1.7117729330493443)
Checking source_id 621228365371520 (RA=46.44320243069999, Dec=1.7609039732057747)
Checking source_id 640710336995072 (RA=46.128743548909256, Dec=1.725257074618689)
Checking source_id 769456276704128 (RA=47.51489911594037, Dec=2.572769511017299)
Checking source_id 780691911138816 (RA=46.77243553812111, Dec=2.261634737325701)

In [10]:
out = pd.DataFrame(rows)
display(out)

                 ID  Sector  Exposure_Time
0    31958852451968       4    1425.599419
1    31958852451968      31     475.199790
2    77863462880768       4    1425.599419
3    97551592960640       4    1425.599419
4    97551592960640      31     475.199790
5   110951890948096       4    1425.599419
6   110951890948096      31     475.199790
7   115899693267968       4    1425.599419
8   115899693267968      31     475.199790
9   123424475948672       4    1425.599419
10  123424475948672      31     475.199790
11  154829276705920       4    1425.599419
12  154829276705920      31     475.199790
13  255709468513920       4    1425.599419
14  255709468513920      31     475.199790
15  290653322568704       4    1425.599419
16  319545567090560       4    1425.599419
17  319545567090560      31     475.199790
18  339993906853248       4    1425.599419
19  435754497122304       4    1425.599419
20  435754497122304      31     475.199790
21  452212812313984       4    1425.599419
22  452212812313984      31     475.199790
23  473447130640640       4    1425.599419
24  473447130640640      31     475.199790
25  559483915442816       4    1425.599419
26  559483915442816      31     475.199790
27  596798591393792       4    1425.599419
28  596798591393792      31     475.199790
29  621228365371520       4    1425.599419
30  621228365371520      31     475.199790
31  640710336995072       4    1425.599419
32  640710336995072      31     475.199790
33  769456276704128       4    1425.599419
34  769456276704128      31     475.199790
35  780691911138816       4    1425.599419
36  780691911138816      31     475.199790

In [11]:
#save spreadsheet .csv
out.to_csv("tess_id_sector_exptime_first20.csv")
print("Saved in tess_id_sector_exptime_first20.csv")

Saved in tess_id_sector_exptime_first20.csv

# NEWEST VERSION

In [2]:
import pandas as pd
import lightkurve as lk
import time

In [3]:
# load data from .csv
table = pd.read_csv("TESS_M=0.4_RP=15.csv")

# convert parallax from mas to pc
table['distance_pc'] = 1000 / table['parallax']  

# filtered to have limit of G mag <16 and d<20
filtered = table[
    (table['phot_g_mean_mag'] <= 16) &
    (table['distance_pc'] <= 20)
]

# tells me total targets before and after filtering
print("Total sources before filtering:", len(table))
print("Sources after filtering:", len(filtered))
#print(filtered[['source_id','phot_g_mean_mag','distance_pc']].head())

Total sources before filtering: 140813
Sources after filtering: 736

In [4]:
subset = filtered

rows = []

# loops .csv
for i, (id, ra, dec) in enumerate(zip(subset['source_id'], subset['ra'], subset['dec']), start=1):
    print(f"{i}. Checking source_id {id} (RA={ra}, DEC={dec})")
    try:
        # goes through TESS Full Frame Image (FFI)
        search = lk.search_tesscut('%s %s' % (ra, dec))

        if len(search) == 0:
            # No FFI found, will tell me it's false
            rows.append({
                "ID": id,
                "Sector": None,
                "Exposure_Time": None,
                "FFI": False
            })
            continue

        for values in search:
            tab = values.table

            # get sector (either sequence_number/sector)
            if "sequence_number" in tab.colnames:
                sector = tab["sequence_number"][0]
            elif "sector" in tab.colnames:
                sector = tab["sector"][0]

            # get exposure time
            exptime = tab["exptime"][0] 

            # append (now with FFI column)
            rows.append({
                "ID": id,
                "Sector": sector,
                "Exposure_Time": exptime,
                "FFI": True    # 
            })

    except Exception as e:
        print(f"Error for {id}: {e}")
        rows.append({
            "ID": id,
            "Sector": None,
            "Exposure_Time": None,
            "FFI": False
        })

out = pd.DataFrame(rows)
display(out)

1. Checking source_id 769456276704128 (RA=47.51489911594037, DEC=2.572769511017299)
2. Checking source_id 16302463200535040 (RA=50.8422709188759, DEC=11.686387390947743)
3. Checking source_id 18986817760556416 (RA=39.82435828918509, DEC=7.470816071340625)
4. Checking source_id 35398295820372864 (RA=43.358915254728714, DEC=17.407883277761023)
5. Checking source_id 57739208163471744 (RA=51.68738385482385, DEC=19.243802626944703)

KeyboardInterrupt:

In [10]:
#save spreadsheet .csv
out.to_csv("tess_id_sector_exptime_G16d20_all_filtered.csv", index=False)
print("Saved in tess_id_sector_exptime_G16d20_all_filtered.csv")

Saved in tess_id_sector_exptime_G16d20_all_filtered.csv

## Will determine FFI based on ID

In [28]:
import pandas as pd
import lightkurve as lk

table = pd.read_csv("TESS_M=0.4_RP=15.csv")

id = 4349305645979265920


# lookup RA and Dec
row = table[table['source_id'] == id].iloc[0]
ra  = row['ra']
dec = row['dec']

search = lk.search_tesscut("%s %s" % (ra, dec))

if len(search) > 0:
    print(f"ID {id}: FFI: YES")
    print("Number of sectors:", len(search))
    print(search)
else:
    print(f"ID {id}: FFI: NO")

ID 4349305645979265920: FFI: NO

## Will determine FFI based on RA + DEC

In [22]:
import lightkurve as lk 

# test if ID has FFI 
# case where it has it 
#ra = 269.59373567871177 
#dec = -12.760552335950688 

#case where it doesn't 
ra = 265.4751620316947 
dec = 9.680499876229684 

search = lk.search_tesscut("%s %s" % (ra, dec)) 
if len(search) > 0: 
    print("FFI coverage: YES") 
    print("Number of sectors:", len(search)) 
    print(search) 
else: 
    print("FFI coverage: NO")

FFI coverage: NO

## Spreadsheet now impliments SPOC availability
* search_tesscut - finds FFI
* search_targetpixelfile - finds SPOC in short cadence target pixel files

In [1]:
import pandas as pd
import lightkurve as lk
import time

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/lightkurve/prf/__init__.py:7: UserWarning: Warning: the tpfmodel submodule is not available without oktopus installed, which requires a current version of autograd. See #1452 for details.
  warnings.warn(

In [17]:
# load data from .csv
table = pd.read_csv("TESS_M=0.4_RP=15.csv")

# convert parallax from mas to pc
table['distance_pc'] = 1000 / table['parallax']  

# filtered to have limit of G mag <16 and d<20
filtered = table[
    (table['phot_g_mean_mag'] <= 16) &
    (table['distance_pc'] <= 20)
]

# tells me total targets before and after filtering
print("Total sources before filtering:", len(table))
print("Sources after filtering:", len(filtered))
#print(filtered[['source_id','phot_g_mean_mag','distance_pc']].head())

subset = filtered.head(5)
#subset = filtered
rows = []

Total sources before filtering: 140813
Sources after filtering: 736

In [18]:
#UPDATE
def unwrap_scalar(x):
    """Convert 1-element array/Series/etc. into a scalar for cleaner CSV display."""
    if x is None:
        return None
    if isinstance(x, (str, bytes)):
        return x
    try:
        if hasattr(x, "__len__") and len(x) == 1:
            return x[0]
    except Exception:
        pass
    return x

# loops .csv
for i, (id, ra, dec) in enumerate(zip(subset['source_id'], subset['ra'], subset['dec']), start=1):
    print(f"{i}. Checking source_id {id} (RA={ra}, DEC={dec})")
    try:
        coord = f"{ra} {dec}"

        # ----------------------------
        # FFI (TESSCut) search
        # ----------------------------
        search_ffi = lk.search_tesscut(coord)
        ffi_avail = len(search_ffi) > 0

        # ----------------------------
        # SPOC (short cadence) search
        # ----------------------------
        spoc = lk.search_targetpixelfile(f"Gaia DR3 {id}", mission="TESS", author="SPOC")
        spoc_avail = len(spoc) > 0

        # If no FFI AND no SPOC, still record a row
        if (not ffi_avail) and (not spoc_avail):
            rows.append({
                "ID": id,
                "DataType": None,
                "Sector": None,
                "Exposure_Time": None,
                "FFI_Avail": False,
                "SPOC_Avail": False
            })
            continue

        # ----------------------------
        # Add rows for FFI products
        # ----------------------------
        if ffi_avail:
            for values in search_ffi:
                tab = values.table

                # sector (either sequence_number/sector)
                sector = None
                if "sequence_number" in tab.colnames:
                    sector = tab["sequence_number"][0]
                elif "sector" in tab.colnames:
                    sector = tab["sector"][0]

                # exposure time
                exptime = tab["exptime"][0] if "exptime" in tab.colnames else None

                sector = unwrap_scalar(sector)
                exptime = unwrap_scalar(exptime)

                rows.append({
                    "ID": id,
                    "DataType": "FFI",
                    "Sector": sector,
                    "Exposure_Time": exptime,
                    "FFI_Avail": True,
                    "SPOC_Avail": spoc_avail
                })
        else:
            # No FFI found
            rows.append({
                "ID": id,
                "DataType": "FFI",
                "Sector": None,
                "Exposure_Time": None,
                "FFI_Avail": False,
                "SPOC_Avail": spoc_avail
            })

        # ----------------------------
        # Add rows for SPOC products
        # ----------------------------
        if spoc_avail:
            for values in spoc:
                sector = getattr(values, "sector", None)
                exptime = getattr(values, "exptime", None)

                # Fallback to table columns if needed
                if sector is None or exptime is None:
                    tab = values.table
                    if sector is None and "sector" in tab.colnames:
                        sector = tab["sector"][0]
                    if exptime is None and "exptime" in tab.colnames:
                        exptime = tab["exptime"][0]

                sector = unwrap_scalar(sector)
                exptime = unwrap_scalar(exptime)

                rows.append({
                    "ID": id,
                    "DataType": "SPOC",
                    "Sector": sector,
                    "Exposure_Time": exptime,
                    "FFI_Avail": ffi_avail,
                    "SPOC_Avail": True
                })
        else:
            # No SPOC found
            rows.append({
                "ID": id,
                "DataType": "SPOC",
                "Sector": None,
                "Exposure_Time": None,
                "FFI_Avail": ffi_avail,
                "SPOC_Avail": False
            })

    except Exception as e:
        print(f"Error for {id}: {e}")
        rows.append({
            "ID": id,
            "DataType": None,
            "Sector": None,
            "Exposure_Time": None,
            "FFI_Avail": False,
            "SPOC_Avail": False
        })

out = pd.DataFrame(rows)
display(out)

# save spreadsheet .csv
#out.to_csv("tess_id_sector_exptime_G16d20_all_filtered.csv", index=False)
#print("Saved in tess_id_sector_exptime_G16d20_all_filtered.csv")

1. Checking source_id 769456276704128 (RA=47.51489911594037, DEC=2.572769511017299)
2. Checking source_id 16302463200535040 (RA=50.8422709188759, DEC=11.686387390947743)
3. Checking source_id 18986817760556416 (RA=39.82435828918509, DEC=7.470816071340625)
4. Checking source_id 35398295820372864 (RA=43.358915254728714, DEC=17.407883277761023)
5. Checking source_id 57739208163471744 (RA=51.68738385482385, DEC=19.243802626944703)

                   ID DataType  Sector Exposure_Time  FFI_Avail  SPOC_Avail
0     769456276704128      FFI     4.0   1425.599419       True        True
1     769456276704128      FFI    31.0     475.19979       True        True
2     769456276704128     SPOC     NaN       120.0 s       True        True
3     769456276704128     SPOC     NaN       120.0 s       True        True
4   16302463200535040      FFI    31.0     475.19979       True        True
5   16302463200535040      FFI    42.0    475.199778       True        True
6   16302463200535040      FFI    43.0     475.19979       True        True
7   16302463200535040      FFI    44.0     475.19979       True        True
8   16302463200535040      FFI    70.0    158.399927       True        True
9   16302463200535040      FFI    71.0     158.39993       True        True
10  16302463200535040     SPOC     NaN        20.0 s       True        True
11  16302463200535040     SPOC     NaN       120.0 s       True        True
12  16302463200535040     SPOC     NaN       120.0 s       True        True
13  16302463200535040     SPOC     NaN       120.0 s       True        True
14  16302463200535040     SPOC     NaN       120.0 s       True        True
15  18986817760556416      FFI     4.0   1425.599419       True        True
16  18986817760556416      FFI    31.0     475.19979       True        True
17  18986817760556416      FFI    42.0    475.199778       True        True
18  18986817760556416      FFI    43.0     475.19979       True        True
19  18986817760556416      FFI    70.0    158.399927       True        True
20  18986817760556416      FFI    71.0     158.39993       True        True
21  18986817760556416     SPOC     NaN       120.0 s       True        True
22  18986817760556416     SPOC     NaN       120.0 s       True        True
23  18986817760556416     SPOC     NaN       120.0 s       True        True
24  18986817760556416     SPOC     NaN       120.0 s       True        True
25  18986817760556416     SPOC     NaN       120.0 s       True        True
26  35398295820372864      FFI    42.0    475.199778       True       False
27  35398295820372864      FFI    43.0     475.19979       True       False
28  35398295820372864      FFI    44.0     475.19979       True       False
29  35398295820372864      FFI    70.0    158.399927       True       False
30  35398295820372864      FFI    71.0     158.39993       True       False
31  35398295820372864     SPOC     NaN          None       True       False
32  57739208163471744      FFI    42.0    475.199778       True        True
33  57739208163471744      FFI    43.0     475.19979       True        True
34  57739208163471744      FFI    70.0    158.399927       True        True
35  57739208163471744      FFI    71.0     158.39993       True        True
36  57739208163471744     SPOC     NaN       120.0 s       True        True
37  57739208163471744     SPOC     NaN       120.0 s       True        True

In [7]:
# loops .csv
for i, (id, ra, dec) in enumerate(zip(subset['source_id'], subset['ra'], subset['dec']), start=1):
    print(f"{i}. Checking source_id {id} (RA={ra}, DEC={dec})")
    try:
        # goes through TESS Full Frame Image (FFI)
        search = lk.search_tesscut('%s %s' % (ra, dec))

        # see if SPOC is available
        # SPOC pipeline used to process all short cadence data
        spoc = lk.search_targetpixelfile('%s %s' % (ra, dec), mission="TESS", author="SPOC")
        spoc_avail = len(spoc) > 0
        

        if len(search) == 0:
            # No FFI found
            rows.append({
                "ID": id,
                "Sector": None,
                "Exposure_Time": None,
                "FFI": False,
                "SPOC": spoc_avail
            })
            continue

        for values in search:
            tab = values.table

            # get sector (either sequence_number/sector)
            if "sequence_number" in tab.colnames:
                sector = tab["sequence_number"][0]
            elif "sector" in tab.colnames:
                sector = tab["sector"][0]

            # get exposure time
            exptime = tab["exptime"][0] 

            # append
            rows.append({
                "ID": id,
                "Sector": sector,
                "Exposure_Time": exptime,
                "FFI": True,
                "SPOC": spoc_avail
            })

    except Exception as e:
        print(f"Error for {id}: {e}")
        rows.append({
            "ID": id,
            "Sector": None,
            "Exposure_Time": None,
            "FFI": False,
            "SPOC": False
        })

out = pd.DataFrame(rows)
display(out)

#save spreadsheet .csv
out.to_csv("tess_id_sector_exptime_G16d20_all_filtered.csv", index=False)
print("Saved in tess_id_sector_exptime_G16d20_all_filtered.csv")

1. Checking source_id 769456276704128 (RA=47.51489911594037, DEC=2.572769511017299)

No data found for target "47.51489911594037 2.572769511017299".

2. Checking source_id 16302463200535040 (RA=50.8422709188759, DEC=11.686387390947743)
3. Checking source_id 18986817760556416 (RA=39.82435828918509, DEC=7.470816071340625)

No data found for target "39.82435828918509 7.470816071340625".

4. Checking source_id 35398295820372864 (RA=43.358915254728714, DEC=17.407883277761023)

No data found for target "43.358915254728714 17.407883277761023".

5. Checking source_id 57739208163471744 (RA=51.68738385482385, DEC=19.243802626944703)
6. Checking source_id 68553931516671488 (RA=54.87437762176911, DEC=24.96824115907829)
7. Checking source_id 72117556076986368 (RA=33.98650746472387, DEC=10.254962202598763)

No data found for target "33.98650746472387 10.254962202598763".

8. Checking source_id 72354810070468224 (RA=33.192827917024836, DEC=10.547975698321418)
9. Checking source_id 89593331327905536 (RA=39.183682325426595, DEC=22.67227965316612)

No data found for target "39.183682325426595 22.67227965316612".

10. Checking source_id 91196316201965184 (RA=29.56508818927173, DEC=18.12063665648874)
11. Checking source_id 97334889619799168 (RA=27.85070481391559, DEC=21.39275062405243)

No data found for target "27.85070481391559 21.39275062405243".

12. Checking source_id 97993497084921984 (RA=27.018206566174985, DEC=21.205767467992107)

No data found for target "27.018206566174985 21.205767467992107".

13. Checking source_id 117709729140217216 (RA=52.20764798129931, DEC=26.48616945277209)
14. Checking source_id 308828253324985984 (RA=19.459213398032063, DEC=28.669329862628036)

No data found for target "19.459213398032063 28.669329862628036".

15. Checking source_id 327944328126649856 (RA=34.29473704167926, DEC=35.44121898612927)

No data found for target "34.29473704167926 35.44121898612927".

16. Checking source_id 348020242217448576 (RA=24.208998277705287, DEC=41.39055046681678)

No data found for target "24.208998277705287 41.39055046681678".

17. Checking source_id 373838214051410816 (RA=14.504225894844094, DEC=39.31987471822514)
18. Checking source_id 569821974111727744 (RA=63.51645882603903, DEC=82.25759093058488)

No data found for target "63.51645882603903 82.25759093058488".

19. Checking source_id 598180646733241216 (RA=130.7186251598315, DEC=9.55037430644196)
20. Checking source_id 605079910398496640 (RA=134.08122584963937, DEC=12.662731415781227)
21. Checking source_id 615779464207025152 (RA=150.6775798896445, DEC=14.985896812309678)
22. Checking source_id 617982090939470464 (RA=144.87402457514528, DEC=14.646793438572836)
23. Checking source_id 619440661833351040 (RA=147.20907756971008, DEC=15.646815201966763)
24. Checking source_id 622339455521105280 (RA=153.97610368902318, DEC=17.490880663782907)
25. Checking source_id 628080246633611520 (RA=148.4782397121578, DEC=20.948079178895128)

No data found for target "148.4782397121578 20.948079178895128".

26. Checking source_id 628865130046268672 (RA=153.72046302348045, DEC=21.395135245402663)
27. Checking source_id 641821259671808896 (RA=149.11007978867167, DEC=22.64914689456202)

No data found for target "149.11007978867167 22.64914689456202".

28. Checking source_id 646255246469567232 (RA=143.20029276934693, DEC=26.994404086268727)

No data found for target "143.20029276934693 26.994404086268727".

29. Checking source_id 646818024623804416 (RA=145.97884036380384, DEC=26.96855261959639)

No data found for target "145.97884036380384 26.96855261959639".

30. Checking source_id 656328319169788032 (RA=125.48480046053642, DEC=17.816229744725995)

No data found for target "125.48480046053642 17.816229744725995".

31. Checking source_id 666988221840703232 (RA=118.10053540514112, DEC=16.20259810649539)

No data found for target "118.10053540514112 16.20259810649539".

32. Checking source_id 696501553469122304 (RA=144.84494415736484, DEC=29.72384628471681)

No data found for target "144.84494415736484 29.72384628471681".

33. Checking source_id 700732474214292096 (RA=140.62274853344667, DEC=31.462808505180774)
34. Checking source_id 704966762213039488 (RA=133.16783218849463, DEC=28.315252421854034)

No data found for target "133.16783218849463 28.315252421854034".

35. Checking source_id 706300980915871616 (RA=129.8558619958561, DEC=29.888835566188664)
36. Checking source_id 709563717249089792 (RA=130.06766840125894, DEC=31.45242630658037)
37. Checking source_id 741275934694972800 (RA=155.0009571782997, DEC=28.95264696593352)

No data found for target "155.0009571782997 28.95264696593352".

38. Checking source_id 753585104807022080 (RA=152.17654982392168, DEC=35.5475756414613)
39. Checking source_id 758200712885953280 (RA=167.96464803741873, DEC=33.53697074560677)
40. Checking source_id 763973668623022464 (RA=170.67963052649262, DEC=37.93015926691593)
41. Checking source_id 764072689093638528 (RA=171.01885964390104, DEC=38.13629424820036)
42. Checking source_id 765038614353808768 (RA=167.20415886992, DEC=39.9194772969731)

No data found for target "167.20415886992 39.9194772969731".

43. Checking source_id 772430527947893632 (RA=175.43249920718978, DEC=42.75157375642011)

No data found for target "175.43249920718978 42.75157375642011".

44. Checking source_id 788357434914248448 (RA=169.87953937654436, DEC=46.69261027622741)

No data found for target "169.87953937654436 46.69261027622741".

45. Checking source_id 795434510226597760 (RA=148.93144985906537, DEC=35.36021293511174)

No data found for target "148.93144985906537 35.36021293511174".

46. Checking source_id 806039471675754112 (RA=155.96718909727664, DEC=43.892552567095734)
47. Checking source_id 835748825612078848 (RA=161.3117904571487, DEC=49.690721671495034)
48. Checking source_id 844922257281519744 (RA=174.0685159675205, DEC=56.39999642341029)
49. Checking source_id 847330325186182912 (RA=156.51100654305094, DEC=50.45359969774126)
50. Checking source_id 868209703104242048 (RA=114.62216862501052, DEC=24.0019731597431)
51. Checking source_id 898506166187633280 (RA=112.98739022537632, DEC=36.22866483400494)

No data found for target "112.98739022537632 36.22866483400494".

52. Checking source_id 907066684548911872 (RA=121.70088015375909, DEC=36.75903456662503)

No data found for target "121.70088015375909 36.75903456662503".

53. Checking source_id 912087093295958144 (RA=132.2838763210011, DEC=39.605842131988005)

No data found for target "132.2838763210011 39.605842131988005".

54. Checking source_id 921952117778154240 (RA=121.72910641215296, DEC=42.29129375007699)

No data found for target "121.72910641215296 42.29129375007699".

55. Checking source_id 978338677527779200 (RA=106.90707091399624, DEC=48.68573489188429)
56. Checking source_id 982389862479141376 (RA=116.80766643936455, DEC=50.344381181505526)
57. Checking source_id 985610542491481984 (RA=113.84028667733696, DEC=54.849773078642905)
58. Checking source_id 1016640817918422272 (RA=135.93078072117314, DEC=52.04697454057216)

No data found for target "135.93078072117314 52.04697454057216".

59. Checking source_id 1017783146073299328 (RA=134.8975225560541, DEC=53.72986152233806)

No data found for target "134.8975225560541 53.72986152233806".

60. Checking source_id 1038195201485531776 (RA=139.44184149237842, DEC=58.417419402224134)

No data found for target "139.44184149237842 58.417419402224134".

61. Checking source_id 1041395708035677312 (RA=132.1273646145831, DEC=61.14977484752529)

No data found for target "132.1273646145831 61.14977484752529".

62. Checking source_id 1056860923195191936 (RA=179.45874784377168, DEC=66.56193013560468)
63. Checking source_id 1070519572033023232 (RA=150.52360646224852, DEC=69.75710578236257)
64. Checking source_id 1071851527289746176 (RA=149.9387380823067, DEC=72.20037314188153)
65. Checking source_id 1073206263054159104 (RA=158.84150877915906, DEC=69.446793871661)

No data found for target "158.84150877915906 69.446793871661".

66. Checking source_id 1083242222939300480 (RA=122.07423466781546, DEC=58.519009709876286)
67. Checking source_id 1117132130541140736 (RA=135.7225460569734, DEC=68.06446038566975)

No data found for target "135.7225460569734 68.06446038566975".

68. Checking source_id 1123681096674583552 (RA=134.9987609031543, DEC=72.95993278581588)

No data found for target "134.9987609031543 72.95993278581588".

69. Checking source_id 1125337098625077504 (RA=135.05447462137312, DEC=75.37236190179152)
70. Checking source_id 1134155113160270720 (RA=150.2915837503259, DEC=81.15484257034134)

No data found for target "150.2915837503259 81.15484257034134".

71. Checking source_id 1138963758544545280 (RA=123.42723031947163, DEC=79.30137045178125)

No data found for target "123.42723031947163 79.30137045178125".

72. Checking source_id 1139642706975159552 (RA=105.87490601885828, DEC=76.77275818273984)
73. Checking source_id 1149245394855341440 (RA=128.05827749211943, DEC=84.40965990897092)

No data found for target "128.05827749211943 84.40965990897092".

74. Checking source_id 1149727977380998784 (RA=109.99020696216758, DEC=84.07690200527787)
75. Checking source_id 1155910118945913728 (RA=229.9411845112153, DEC=4.660000235225668)
76. Checking source_id 1159745146784043264 (RA=225.33415504486476, DEC=5.546794272660181)

No data found for target "225.33415504486476 5.546794272660181".

77. Checking source_id 1165479168642900992 (RA=232.625560005462, DEC=9.434551385099413)
78. Checking source_id 1175938925836488448 (RA=216.2357318474915, DEC=8.888339518893313)

No data found for target "216.2357318474915 8.888339518893313".

79. Checking source_id 1188693088919917952 (RA=224.109214809204, DEC=17.91876929997926)

No data found for target "224.109214809204 17.91876929997926".

80. Checking source_id 1209432042883668480 (RA=233.71072951618376, DEC=18.00196306214209)

No data found for target "233.71072951618376 18.00196306214209".

81. Checking source_id 1212774313804554752 (RA=227.52009755174592, DEC=19.355624418458618)

No data found for target "227.52009755174592 19.355624418458618".

82. Checking source_id 1214076070761755008 (RA=229.63109374468223, DEC=20.60824922657203)
83. Checking source_id 1227705135863076864 (RA=217.0156415738216, DEC=13.934833566564166)

No data found for target "217.0156415738216 13.934833566564166".

84. Checking source_id 1235125877277843840 (RA=218.04584697379087, DEC=16.013385429054974)
85. Checking source_id 1256071505067560704 (RA=216.39418554867095, DEC=25.668004465226957)
86. Checking source_id 1276940648080594048 (RA=231.43145117487225, DEC=31.202217035964036)
87. Checking source_id 1282073374518833152 (RA=223.79801910728224, DEC=30.11225414386347)
88. Checking source_id 1282632682337912832 (RA=221.0710869095232, DEC=30.0357734179162)

No data found for target "221.0710869095232 30.0357734179162".

89. Checking source_id 1320545217653492864 (RA=240.4298070154365, DEC=30.181367389399146)

No data found for target "240.4298070154365 30.181367389399146".

90. Checking source_id 1320795047312113152 (RA=237.83964101743064, DEC=29.516446364274)

No data found for target "237.83964101743064 29.516446364274".

91. Checking source_id 1326893351115617024 (RA=251.6292959257543, DEC=34.580290245898446)

No data found for target "251.6292959257543 34.580290245898446".

92. Checking source_id 1327654969076730880 (RA=249.25489571253425, DEC=35.593526440532905)

No data found for target "249.25489571253425 35.593526440532905".

93. Checking source_id 1332966881549315456 (RA=247.8274448005916, DEC=40.86572384148289)

No data found for target "247.8274448005916 40.86572384148289".

94. Checking source_id 1341113541156480768 (RA=257.89598966788463, DEC=38.44254560681901)
95. Checking source_id 1350714133093019904 (RA=269.4622611288724, DEC=46.59121608783237)

No data found for target "269.4622611288724 46.59121608783237".

96. Checking source_id 1355264565043431040 (RA=257.3834721191679, DEC=43.680105808986085)

No data found for target "257.3834721191679 43.680105808986085".

97. Checking source_id 1372215976327300480 (RA=239.57754339419824, DEC=35.408158262718665)

No data found for target "239.57754339419824 35.408158262718665".

98. Checking source_id 1379500928055726848 (RA=241.20868366880867, DEC=39.16016523606519)

No data found for target "241.20868366880867 39.16016523606519".

99. Checking source_id 1388684770725399296 (RA=229.1684830144717, DEC=39.17983717431188)
100. Checking source_id 1409902905599851392 (RA=247.8661959969435, DEC=47.17314755249796)
101. Checking source_id 1412645602995521920 (RA=255.85040248888004, DEC=51.40906417008386)

No data found for target "255.85040248888004 51.40906417008386".

102. Checking source_id 1416123117756120960 (RA=259.41085537136235, DEC=52.40531634143529)
103. Checking source_id 1431176943768690816 (RA=248.57558060807455, DEC=57.16757381763237)
104. Checking source_id 1443068608699851008 (RA=202.9594075396803, DEC=23.389206653452536)
105. Checking source_id 1451197916638959872 (RA=209.71769182511895, DEC=27.87062339863821)
106. Checking source_id 1461049369026235904 (RA=197.8380339246302, DEC=28.542881140686458)

No data found for target "197.8380339246302 28.542881140686458".

107. Checking source_id 1461125613285603840 (RA=197.3939952563072, DEC=28.984194794735036)

No data found for target "197.3939952563072 28.984194794735036".

108. Checking source_id 1461507384337635840 (RA=199.13310731831825, DEC=27.87596984084402)

No data found for target "199.13310731831825 27.87596984084402".

109. Checking source_id 1466009540856759680 (RA=196.7105478174373, DEC=30.84621621605227)

No data found for target "196.7105478174373 30.84621621605227".

110. Checking source_id 1477762319428998400 (RA=214.94519097573385, DEC=31.617589844728105)
111. Checking source_id 1483977656798789120 (RA=213.98497602510355, DEC=36.27839269007434)
112. Checking source_id 1489294551432850560 (RA=223.06692178226328, DEC=41.32158904033235)

No data found for target "223.06692178226328 41.32158904033235".

113. Checking source_id 1495487688115551744 (RA=207.7132354836552, DEC=36.73846792755987)

No data found for target "207.7132354836552 36.73846792755987".

114. Checking source_id 1505209054532280960 (RA=214.34237220584717, DEC=45.42936021377157)
115. Checking source_id 1518564478676515712 (RA=189.11736017524785, DEC=35.19971562564376)

No data found for target "189.11736017524785 35.19971562564376".

116. Checking source_id 1534239391319888384 (RA=190.70457462086816, DEC=41.8966090688773)

No data found for target "190.70457462086816 41.8966090688773".

117. Checking source_id 1573896198753650944 (RA=181.4021839662666, DEC=56.394863843666194)
118. Checking source_id 1587576253706543232 (RA=228.15665054327465, DEC=45.73119308728785)

No data found for target "228.15665054327465 45.73119308728785".

119. Checking source_id 1595170236922937728 (RA=233.51466659726952, DEC=51.368562240881666)

No data found for target "233.51466659726952 51.368562240881666".

120. Checking source_id 1603272950424941440 (RA=233.8585360449291, DEC=60.08470833271646)

No data found for target "233.8585360449291 60.08470833271646".

121. Checking source_id 1603611493015735296 (RA=218.05659204654648, DEC=49.651165748848456)

No data found for target "218.05659204654648 49.651165748848456".

122. Checking source_id 1604901876901703168 (RA=215.76332804586107, DEC=51.77600462861712)

No data found for target "215.76332804586107 51.77600462861712".

123. Checking source_id 1616853430856547968 (RA=221.1035124404749, DEC=58.287786919281984)

No data found for target "221.1035124404749 58.287786919281984".

124. Checking source_id 1618330448634358400 (RA=216.78665388902056, DEC=60.941040648347105)
125. Checking source_id 1631591147276525696 (RA=253.2075718369321, DEC=63.07812356967455)
126. Checking source_id 1638180413086979840 (RA=269.3142709072523, DEC=70.70178301936559)

No data found for target "269.3142709072523 70.70178301936559".

127. Checking source_id 1648484868558988544 (RA=250.0827910688673, DEC=67.60294000951913)

No data found for target "250.0827910688673 67.60294000951913".

128. Checking source_id 1650819612781643392 (RA=262.0450109199984, DEC=71.14096957434231)
129. Checking source_id 1655482224982135040 (RA=255.4369477446704, DEC=74.19781368444308)
130. Checking source_id 1656076893269778432 (RA=265.6823444683212, DEC=75.62282031158797)

No data found for target "265.6823444683212 75.62282031158797".

131. Checking source_id 1669449084967071872 (RA=220.58662378500725, DEC=66.05561864866871)
132. Checking source_id 1678489647527832320 (RA=198.5949485165658, DEC=66.37603764196513)

No data found for target "198.5949485165658 66.37603764196513".

133. Checking source_id 1683228851880827136 (RA=185.44336261603965, DEC=68.2687045566608)

No data found for target "185.44336261603965 68.2687045566608".

134. Checking source_id 1683609076745527680 (RA=181.3678591223992, DEC=69.53936644393914)

No data found for target "181.3678591223992 69.53936644393914".

135. Checking source_id 1683677624423753472 (RA=181.73532846482885, DEC=70.13042280787634)
136. Checking source_id 1701585301586363904 (RA=219.30529832556255, DEC=75.61151710152384)
137. Checking source_id 1701602958196086528 (RA=217.80244124264595, DEC=75.44491958012206)
138. Checking source_id 1710948192852697600 (RA=262.8122775792793, DEC=82.09105560054718)

No data found for target "262.8122775792793 82.09105560054718".

139. Checking source_id 1714831771000745344 (RA=208.41629245213292, DEC=77.61886343809084)
140. Checking source_id 1735245338242513536 (RA=310.8514381606976, DEC=4.764685971871537)

No data found for target "310.8514381606976 4.764685971871537".

141. Checking source_id 1768825106253209984 (RA=327.9522183313725, DEC=13.603838612745625)
142. Checking source_id 1773485214494929536 (RA=326.0387863765124, DEC=17.059722272765484)
143. Checking source_id 1773497412196823680 (RA=326.0343872670299, DEC=17.077038166155283)
144. Checking source_id 1776179945695834368 (RA=331.59592583103495, DEC=17.372810486070932)

No data found for target "331.59592583103495 17.372810486070932".

145. Checking source_id 1890425839540910848 (RA=341.97779535087403, DEC=31.871783828604855)

No data found for target "341.97779535087403 31.871783828604855".

146. Checking source_id 1893189736896880640 (RA=330.306566078579, DEC=28.30710892040449)

No data found for target "330.306566078579 28.30710892040449".

147. Checking source_id 2110165780975185792 (RA=278.6530518091756, DEC=40.12307795291824)
148. Checking source_id 2118429538570209920 (RA=278.86660840698516, DEC=45.762979999016885)

No data found for target "278.86660840698516 45.762979999016885".

149. Checking source_id 2256631484392164736 (RA=277.8407516553966, DEC=64.9039850767494)
150. Checking source_id 2257597439718033536 (RA=274.74325647947336, DEC=66.19061665488063)

No data found for target "274.74325647947336 66.19061665488063".

151. Checking source_id 2294281163411732736 (RA=278.9690777068371, DEC=80.09526285745366)
152. Checking source_id 2302668860880387072 (RA=289.10161012405797, DEC=84.22869527150492)
153. Checking source_id 2312376723918929920 (RA=356.6576476677058, DEC=-34.16710787919001)

No data found for target "356.6576476677058 -34.16710787919001".

154. Checking source_id 2325083848520121856 (RA=352.65810345342345, DEC=-33.30768786716094)
155. Checking source_id 2368212771939556992 (RA=3.9914280244393505, DEC=-16.61597822404432)
156. Checking source_id 2393563872239260928 (RA=351.86040963011595, DEC=-17.69494218902131)

No data found for target "351.86040963011595 -17.69494218902131".

157. Checking source_id 2395413147718069504 (RA=354.53268726381896, DEC=-16.23651363027235)
158. Checking source_id 2400808245117576704 (RA=339.69068815030255, DEC=-20.614689446269768)

No data found for target "339.69068815030255 -20.614689446269768".

159. Checking source_id 2407340615496379008 (RA=352.10236185712836, DEC=-15.924966875091195)
160. Checking source_id 2407573643242037888 (RA=351.0712300150862, DEC=-15.373269236906095)
161. Checking source_id 2414623952318068224 (RA=1.2404631704419242, DEC=-17.160303653461234)
162. Checking source_id 2420649585275393920 (RA=356.83925393911727, DEC=-12.343968535630694)

No data found for target "356.83925393911727 -12.343968535630694".

163. Checking source_id 2421080250237097344 (RA=359.33671447287855, DEC=-12.980168707826213)
164. Checking source_id 2421080250237474176 (RA=359.3316119129798, DEC=-12.977870560152498)
165. Checking source_id 2450599697900838912 (RA=23.49187379987124, DEC=-17.640773463135556)
166. Checking source_id 2451701339832959232 (RA=22.623854394641025, DEC=-16.40544797329293)
167. Checking source_id 2452167910719793664 (RA=22.16461895808497, DEC=-14.96810617489612)
168. Checking source_id 2453195851012123904 (RA=26.781623953195012, DEC=-14.411598506271671)
169. Checking source_id 2457862762476854656 (RA=20.825063748419577, DEC=-12.938209952737276)

No data found for target "20.825063748419577 -12.938209952737276".

170. Checking source_id 2461728194387221504 (RA=30.434023239076055, DEC=-10.290317824118802)

No data found for target "30.434023239076055 -10.290317824118802".

171. Checking source_id 2467242352575094784 (RA=25.994623558557567, DEC=-6.913531290688611)
172. Checking source_id 2467732906559754496 (RA=27.769525129441792, DEC=-6.119239184112927)

No data found for target "27.769525129441792 -6.119239184112927".

173. Checking source_id 2468929243931522304 (RA=17.57395028608209, DEC=-11.855370704147928)

No data found for target "17.57395028608209 -11.855370704147928".

174. Checking source_id 2486388560866377728 (RA=33.1190109988742, DEC=-8.071574920874733)

No data found for target "33.1190109988742 -8.071574920874733".

175. Checking source_id 2492866780297999232 (RA=33.554613532263986, DEC=-3.96280045849318)

No data found for target "33.554613532263986 -3.96280045849318".

176. Checking source_id 2497858563088120448 (RA=44.01738337380463, DEC=-0.608877262589059)
177. Checking source_id 2507016253701863040 (RA=33.23006351010599, DEC=0.0048112291822607)

No data found for target "33.23006351010599 0.0048112291822607".

178. Checking source_id 2514052131687080192 (RA=35.19339905103572, DEC=2.9757995116747007)

No data found for target "35.19339905103572 2.9757995116747007".

179. Checking source_id 2526788363283721984 (RA=8.93379610467678, DEC=-5.687454587970094)
180. Checking source_id 2528227035593363840 (RA=8.221728419110557, DEC=-4.569270815894982)
181. Checking source_id 2537831170877143552 (RA=17.050154984643736, DEC=0.4641340321772402)

No data found for target "17.050154984643736 0.4641340321772402".

182. Checking source_id 2614071100988460544 (RA=331.39766600457193, DEC=-11.075490632741356)

No data found for target "331.39766600457193 -11.075490632741356".

183. Checking source_id 2616132101175335936 (RA=334.3256811695789, DEC=-8.806486660337637)

No data found for target "334.3256811695789 -8.806486660337637".

184. Checking source_id 2618333804489940992 (RA=329.3036181978969, DEC=-9.05802459659516)
185. Checking source_id 2620145937091715072 (RA=331.54090391057207, DEC=-7.394198350555103)
186. Checking source_id 2631857350835259392 (RA=348.9785213795388, DEC=-6.463096715840339)

No data found for target "348.9785213795388 -6.463096715840339".

187. Checking source_id 2668249051115631232 (RA=326.2524726236367, DEC=-5.788973523692696)

No data found for target "326.2524726236367 -5.788973523692696".

188. Checking source_id 2669873515120908544 (RA=326.82387294144644, DEC=-4.744613685896646)
189. Checking source_id 2670661109044300160 (RA=323.4543418919189, DEC=-6.8551113020513075)

No data found for target "323.4543418919189 -6.8551113020513075".

190. Checking source_id 2673992663636347520 (RA=327.8635523883638, DEC=-1.4538921085791252)
191. Checking source_id 2681122098893985408 (RA=326.6718481188171, DEC=-0.1755173375144743)

No data found for target "326.6718481188171 -0.1755173375144743".

192. Checking source_id 2683209044978079616 (RA=331.6251935434858, DEC=2.375809039939923)
193. Checking source_id 2683714304930755712 (RA=331.69527845431674, DEC=3.4163173765574197)

No data found for target "331.69527845431674 3.4163173765574197".

194. Checking source_id 2688566793341935360 (RA=323.4546452148779, DEC=1.7791345250832382)

No data found for target "323.4546452148779 1.7791345250832382".

195. Checking source_id 2705611005983192320 (RA=338.6921084252097, DEC=4.044371189279514)
196. Checking source_id 2708839657453920256 (RA=335.0565229770535, DEC=6.72679864112854)

No data found for target "335.0565229770535 6.72679864112854".

197. Checking source_id 2710189960812052736 (RA=336.76251116872623, DEC=6.825575040979833)
198. Checking source_id 2719512513745949184 (RA=342.0961253423981, DEC=12.536167811623086)

No data found for target "342.0961253423981 12.536167811623086".

199. Checking source_id 2775987485397299072 (RA=11.08183889277884, DEC=12.616598050741125)

No data found for target "11.08183889277884 12.616598050741125".

200. Checking source_id 2799992744809482112 (RA=6.985243946351337, DEC=22.324902794590333)
201. Checking source_id 2800823799506215168 (RA=6.33469184849611, DEC=22.884358347500047)

No data found for target "6.33469184849611 22.884358347500047".

202. Checking source_id 2801216123294143360 (RA=5.8655364124677485, DEC=24.30736066735532)
203. Checking source_id 2819781274051096192 (RA=354.4016087764225, DEC=16.367299189308994)

No data found for target "354.4016087764225 16.367299189308994".

204. Checking source_id 2824770686019004032 (RA=352.9716753030632, DEC=19.937313746866927)

No data found for target "352.9716753030632 19.937313746866927".

205. Checking source_id 2830318679957189632 (RA=342.22734755350785, DEC=18.332476624663535)
206. Checking source_id 2836510961942677376 (RA=340.84852132214786, DEC=22.138349954479125)

No data found for target "340.84852132214786 22.138349954479125".

207. Checking source_id 2856874535763703680 (RA=4.725287520277892, DEC=27.813355639663538)

No data found for target "4.725287520277892 27.813355639663538".

208. Checking source_id 2859027409595355776 (RA=6.148344264210615, DEC=30.041581512034053)

No data found for target "6.148344264210615 30.041581512034053".

209. Checking source_id 2863419584886542080 (RA=5.128239996638605, DEC=33.08128045387165)
210. Checking source_id 2864382138598091648 (RA=353.76630482328295, DEC=25.250191671633328)
211. Checking source_id 2866851710433326208 (RA=356.5590246187754, DEC=28.43471215134376)
212. Checking source_id 2868199402451064064 (RA=355.7180385472229, DEC=30.82137349573688)

No data found for target "355.7180385472229 30.82137349573688".

213. Checking source_id 2872988394066393344 (RA=355.0954866644879, DEC=34.55437676255151)

No data found for target "355.0954866644879 34.55437676255151".

214. Checking source_id 2881313793031884544 (RA=358.71365830063576, DEC=38.52633962632873)
215. Checking source_id 2886233695250041216 (RA=91.21742524933885, DEC=-34.558412822381825)

No data found for target "91.21742524933885 -34.558412822381825".

216. Checking source_id 2891695137006940544 (RA=94.44578372665914, DEC=-34.01941716022002)
217. Checking source_id 2905516483501493120 (RA=82.7698222187872, DEC=-30.19782913482597)

No data found for target "82.7698222187872 -30.19782913482597".

218. Checking source_id 2907884728469088384 (RA=86.45936920758024, DEC=-27.16289618149821)
219. Checking source_id 2911981886751531648 (RA=91.9313221336463, DEC=-25.745763611837013)
220. Checking source_id 2954555801611979648 (RA=79.65245423379399, DEC=-28.69991906819153)

No data found for target "79.65245423379399 -28.69991906819153".

221. Checking source_id 3013672487388307456 (RA=83.84028163560048, DEC=-9.519503846133947)

No data found for target "83.84028163560048 -9.519503846133947".

222. Checking source_id 3015684005638599168 (RA=84.00082080161667, DEC=-7.64749055072158)

No data found for target "84.00082080161667 -7.64749055072158".

223. Checking source_id 3073508528645520000 (RA=128.60888691505394, DEC=-1.1461842748957634)

No data found for target "128.60888691505394 -1.1461842748957634".

224. Checking source_id 3080039799513337216 (RA=129.37618554147426, DEC=3.56196898899723)
225. Checking source_id 3171631420210205056 (RA=68.81802669744249, DEC=-16.114491965535613)

No data found for target "68.81802669744249 -16.114491965535613".

226. Checking source_id 3181367767472670080 (RA=73.01496562474308, DEC=-10.973690528268827)

No data found for target "73.01496562474308 -10.973690528268827".

227. Checking source_id 3183748278864953856 (RA=76.55698495755243, DEC=-8.119530513718672)
228. Checking source_id 3197487123332369536 (RA=61.52874997880343, DEC=-5.579705448233032)
229. Checking source_id 3198812859478372480 (RA=65.86135866378902, DEC=-7.397152593091982)
230. Checking source_id 3200303384927512960 (RA=70.09847133151465, DEC=-5.501688546295259)

No data found for target "70.09847133151465 -5.501688546295259".

231. Checking source_id 3230306548988683392 (RA=68.68850665695317, DEC=-0.4472776491451271)
232. Checking source_id 3266937637860051840 (RA=47.81499313101462, DEC=1.108502371089936)
233. Checking source_id 3278137572540701056 (RA=56.08602675057091, DEC=7.698683077306292)
234. Checking source_id 3288082758293022848 (RA=73.02457095863625, DEC=6.47519220606572)

No data found for target "73.02457095863625 6.47519220606572".

235. Checking source_id 3459586677937737088 (RA=182.3476049914616, DEC=-38.26276233724284)
236. Checking source_id 3464485826872541440 (RA=175.34234990922278, DEC=-36.40821490897027)

No data found for target "175.34234990922278 -36.40821490897027".

237. Checking source_id 3479221035031532416 (RA=178.2958474507511, DEC=-31.39953502009418)

No data found for target "178.2958474507511 -31.39953502009418".

238. Checking source_id 3489874340631095936 (RA=183.5363721475547, DEC=-23.75432290382595)
239. Checking source_id 3493736924979792768 (RA=178.92674906227322, DEC=-22.4171647007583)

No data found for target "178.92674906227322 -22.4171647007583".

240. Checking source_id 3496355755520065408 (RA=189.8989000476626, DEC=-26.97054952279352)

No data found for target "189.8989000476626 -26.97054952279352".

241. Checking source_id 3499296429434610304 (RA=194.05414981104076, DEC=-22.08421085269118)

No data found for target "194.05414981104076 -22.08421085269118".

242. Checking source_id 3502592975744957824 (RA=192.7215172935436, DEC=-21.35524787955247)

No data found for target "192.7215172935436 -21.35524787955247".

243. Checking source_id 3517619520125627904 (RA=182.07620531885144, DEC=-21.01936118449221)
244. Checking source_id 3517841140438425600 (RA=182.81963496571075, DEC=-19.973535053310865)
245. Checking source_id 3517841209157902720 (RA=182.79799193877028, DEC=-19.96139412325039)
246. Checking source_id 3530383784971799680 (RA=191.00091142330737, DEC=-11.175787631619018)

No data found for target "191.00091142330737 -11.175787631619018".

247. Checking source_id 3531294008802299392 (RA=169.1543575390885, DEC=-27.95891105546361)

No data found for target "169.1543575390885 -27.95891105546361".

248. Checking source_id 3536327366875661056 (RA=167.47217753029176, DEC=-24.24941832570553)
249. Checking source_id 3539057213728669184 (RA=166.27825468370008, DEC=-22.216074598403548)

No data found for target "166.27825468370008 -22.216074598403548".

250. Checking source_id 3546332682170832128 (RA=170.98588570400648, DEC=-18.363746221389203)

No data found for target "170.98588570400648 -18.363746221389203".

251. Checking source_id 3566338949070993536 (RA=169.2751391986689, DEC=-11.37435916898148)

No data found for target "169.2751391986689 -11.37435916898148".

252. Checking source_id 3574445407785255296 (RA=182.18346204777117, DEC=-11.564004075631765)

No data found for target "182.18346204777117 -11.564004075631765".

253. Checking source_id 3582675080520660992 (RA=185.96594679923768, DEC=-8.979976175598768)

No data found for target "185.96594679923768 -8.979976175598768".

254. Checking source_id 3584226658929871232 (RA=184.64361569925163, DEC=-6.423305459754171)

No data found for target "184.64361569925163 -6.423305459754171".

255. Checking source_id 3592769731134725248 (RA=172.6726859278835, DEC=-8.094129760812047)

No data found for target "172.6726859278835 -8.094129760812047".

256. Checking source_id 3602406744394215936 (RA=179.44156853878948, DEC=-1.8183858067070635)

No data found for target "179.44156853878948 -1.8183858067070635".

257. Checking source_id 3608334005420675584 (RA=200.4743550952303, DEC=-14.402375689120356)
258. Checking source_id 3610474857638415616 (RA=204.6710209109411, DEC=-11.535869729632498)
259. Checking source_id 3612684120096472192 (RA=209.5658446545277, DEC=-12.049543189658584)

No data found for target "209.5658446545277 -12.049543189658584".

260. Checking source_id 3637468383496879104 (RA=204.72131158745523, DEC=-2.2634740111610667)

No data found for target "204.72131158745523 -2.2634740111610667".

261. Checking source_id 3652910371473481344 (RA=216.9820370876051, DEC=-0.3751301143973934)

No data found for target "216.9820370876051 -0.3751301143973934".

262. Checking source_id 3652910405833716864 (RA=216.98338440234295, DEC=-0.3717579253833862)

No data found for target "216.98338440234295 -0.3717579253833862".

263. Checking source_id 3669916071144145920 (RA=217.0715724608264, DEC=5.31243130716067)

No data found for target "217.0715724608264 5.31243130716067".

264. Checking source_id 3669916380381791104 (RA=217.08799771619425, DEC=5.3167596985937795)

No data found for target "217.08799771619425 5.3167596985937795".

265. Checking source_id 3677448412989388032 (RA=195.0149340750512, DEC=-5.6297508059701755)

No data found for target "195.0149340750512 -5.6297508059701755".

266. Checking source_id 3713826030072008192 (RA=207.2025218306175, DEC=4.099847002145388)
267. Checking source_id 3758629475341196672 (RA=164.61574644090516, DEC=-10.775511452309788)
268. Checking source_id 3759774208680370688 (RA=163.89244055921364, DEC=-9.355205624410983)

No data found for target "163.89244055921364 -9.355205624410983".

269. Checking source_id 3762071530853756928 (RA=158.75568416720952, DEC=-9.41153944861764)
270. Checking source_id 3793898411041910144 (RA=175.55398369123793, DEC=-1.3687129840118293)

No data found for target "175.55398369123793 -1.3687129840118293".

271. Checking source_id 3793898479761174656 (RA=175.55387781734504, DEC=-1.3651467411429208)
272. Checking source_id 3794437034301022720 (RA=177.98105299187364, DEC=-1.5263271044381868)
273. Checking source_id 3795993633527490304 (RA=176.92404164490358, DEC=0.2512338759265444)

No data found for target "176.92404164490358 0.2512338759265444".

274. Checking source_id 3795993633527490560 (RA=176.9183832811517, DEC=0.2551360375501735)

No data found for target "176.9183832811517 0.2551360375501735".

275. Checking source_id 3836344438956110208 (RA=149.96815413261183, DEC=2.7805250971078017)
276. Checking source_id 3838384617141390208 (RA=140.4513282977866, DEC=-2.328676307427825)
277. Checking source_id 3845035696121944576 (RA=139.04266578605825, DEC=1.8853361511850135)
278. Checking source_id 3850237416912716928 (RA=149.7346148256968, DEC=5.966340551968416)
279. Checking source_id 3862117335108574848 (RA=158.13634891696773, DEC=6.5012502773544405)
280. Checking source_id 3920481233377933824 (RA=182.518368136087, DEC=12.73595016486881)
281. Checking source_id 3927886100593557888 (RA=193.71037814037763, DEC=11.985615985802268)

No data found for target "193.71037814037763 11.985615985802268".

282. Checking source_id 3931880591977203584 (RA=188.82234404657177, DEC=13.30249052683408)
283. Checking source_id 3965764619767224832 (RA=171.2218237122872, DEC=13.38089075564062)
284. Checking source_id 3968118399284369280 (RA=165.83769461159238, DEC=13.632847157123214)
285. Checking source_id 3978179338700027008 (RA=168.80258887774315, DEC=19.45118404016304)

No data found for target "168.80258887774315 19.45118404016304".

286. Checking source_id 3987041475434695936 (RA=159.03739434658837, DEC=19.39015001792424)

No data found for target "159.03739434658837 19.39015001792424".

287. Checking source_id 3997576171218205312 (RA=170.4794132895151, DEC=26.830263459667865)

No data found for target "170.4794132895151 26.830263459667865".

288. Checking source_id 4004586348119642240 (RA=178.23977721633167, DEC=24.479688541188125)

No data found for target "178.23977721633167 24.479688541188125".

289. Checking source_id 4188996885011268608 (RA=299.3487765276967, DEC=-12.566252961830063)

No data found for target "299.3487765276967 -12.566252961830063".

290. Checking source_id 4229940258487034368 (RA=307.50854656595607, DEC=0.39871746938847)
291. Checking source_id 4349305645979265920 (RA=242.74321092251347, DEC=-6.526530784784987)

No data found for target "242.74321092251347 -6.526530784784987".
No data found for target "242.74321092251347 -6.526530784784987".

292. Checking source_id 4353476020565733632 (RA=252.72077443405544, DEC=-4.844117679510572)

No data found for target "252.72077443405544 -4.844117679510572".
No data found for target "252.72077443405544 -4.844117679510572".

293. Checking source_id 4365609170043180416 (RA=254.27604768745735, DEC=-4.350649323558728)

No data found for target "254.27604768745735 -4.350649323558728".
No data found for target "254.27604768745735 -4.350649323558728".

294. Checking source_id 4366633811793952896 (RA=258.01634026214566, DEC=-3.3925453464829833)

No data found for target "258.01634026214566 -3.3925453464829833".
No data found for target "258.01634026214566 -3.3925453464829833".

295. Checking source_id 4383790518216171264 (RA=250.02571538084769, DEC=0.7045342401421566)

No data found for target "250.02571538084769 0.7045342401421566".
No data found for target "250.02571538084769 0.7045342401421566".

296. Checking source_id 4393265392168829056 (RA=258.8314799887317, DEC=4.960575338342743)

No data found for target "258.8314799887317 4.960575338342743".
No data found for target "258.8314799887317 4.960575338342743".

297. Checking source_id 4405150047715392128 (RA=243.60495984709544, DEC=-2.848575653404131)

No data found for target "243.60495984709544 -2.848575653404131".
No data found for target "243.60495984709544 -2.848575653404131".

298. Checking source_id 4410702581435191296 (RA=237.5475233257174, DEC=0.958881993576492)
299. Checking source_id 4412417304175836544 (RA=240.6727825640195, DEC=1.530347271225057)

No data found for target "240.6727825640195 1.530347271225057".

300. Checking source_id 4423007800173036544 (RA=236.8120142223106, DEC=1.82248062760857)
301. Checking source_id 4443110789740420480 (RA=255.25771984966343, DEC=8.206529331440088)

No data found for target "255.25771984966343 8.206529331440088".
No data found for target "255.25771984966343 8.206529331440088".

302. Checking source_id 4446207564241339520 (RA=249.02120996412984, DEC=8.812978058517322)

No data found for target "249.02120996412984 8.812978058517322".
No data found for target "249.02120996412984 8.812978058517322".

303. Checking source_id 4446574040918651904 (RA=248.2212020132817, DEC=9.841238219932931)

No data found for target "248.2212020132817 9.841238219932931".
No data found for target "248.2212020132817 9.841238219932931".

304. Checking source_id 4454532237354157568 (RA=239.45174547990845, DEC=9.01878131907999)
305. Checking source_id 4540481374832743040 (RA=259.4321138774718, DEC=11.668137650695137)

No data found for target "259.4321138774718 11.668137650695137".
No data found for target "259.4321138774718 11.668137650695137".

306. Checking source_id 4540984195244025088 (RA=257.46817080562016, DEC=11.925767768358645)

No data found for target "257.46817080562016 11.925767768358645".
No data found for target "257.46817080562016 11.925767768358645".

307. Checking source_id 4549983418742839808 (RA=263.4709486275802, DEC=16.919716366320987)
308. Checking source_id 4554019214828782848 (RA=262.59454686161763, DEC=19.208516712601973)

No data found for target "262.59454686161763 19.208516712601973".

309. Checking source_id 4566158991430299520 (RA=252.741579155228, DEC=22.45335201410153)

No data found for target "252.741579155228 22.45335201410153".

310. Checking source_id 4567274927017734400 (RA=260.47682518226895, DEC=21.43091558237368)
311. Checking source_id 4568060562432051584 (RA=256.77899349986836, DEC=21.553906093733755)

No data found for target "256.77899349986836 21.553906093733755".

312. Checking source_id 4574048021719712640 (RA=259.9695666590066, DEC=26.502318754868263)

No data found for target "259.9695666590066 26.502318754868263".

313. Checking source_id 4594186745414679680 (RA=263.80474400128486, DEC=26.578452534570733)

No data found for target "263.80474400128486 26.578452534570733".

314. Checking source_id 4609151442264875648 (RA=267.89764258006653, DEC=37.82801852429099)

No data found for target "267.89764258006653 37.82801852429099".

315. Checking source_id 4620448786799883136 (RA=43.437287895891245, DEC=-79.98664426166238)
316. Checking source_id 4646616923022587136 (RA=41.51227837952512, DEC=-70.40213295868823)
317. Checking source_id 4654435618927743872 (RA=65.05548915027946, DEC=-70.09683448950774)

No data found for target "65.05548915027946 -70.09683448950774".

318. Checking source_id 4665366619931917824 (RA=74.88261512661207, DEC=-61.88437139795797)
319. Checking source_id 4672462936698379520 (RA=50.21568535473568, DEC=-63.86585958449603)
320. Checking source_id 4676145235499604096 (RA=61.51584482379152, DEC=-64.09722087351366)
321. Checking source_id 4677345043203760896 (RA=67.025472974701, DEC=-62.15543452946297)

No data found for target "67.025472974701 -62.15543452946297".

322. Checking source_id 4689958778035794048 (RA=7.773722280188864, DEC=-72.01767831001747)

No data found for target "7.773722280188864 -72.01767831001747".

323. Checking source_id 4690736923033593728 (RA=18.27130621215673, DEC=-70.84376343995396)
324. Checking source_id 4705628051386514304 (RA=16.02568403467347, DEC=-65.37498961991618)

No data found for target "16.02568403467347 -65.37498961991618".

325. Checking source_id 4706483132131647232 (RA=3.93774642370424, DEC=-67.99395121635692)

No data found for target "3.93774642370424 -67.99395121635692".

326. Checking source_id 4708990018643008896 (RA=14.305598383824345, DEC=-64.25584867932709)

No data found for target "14.305598383824345 -64.25584867932709".

327. Checking source_id 4714117865996976768 (RA=34.366362901437554, DEC=-59.38085727536495)

No data found for target "34.366362901437554 -59.38085727536495".

328. Checking source_id 4719430087707860736 (RA=30.160435097325607, DEC=-55.96826051259185)
329. Checking source_id 4726357491998516480 (RA=39.47063857709459, DEC=-58.75214686390397)
330. Checking source_id 4733113441195646592 (RA=54.73403875235281, DEC=-52.568615867333605)
331. Checking source_id 4757687388639045504 (RA=84.41696430616265, DEC=-61.90996787478893)

No data found for target "84.41696430616265 -61.90996787478893".

332. Checking source_id 4772342676044749952 (RA=81.87712822395483, DEC=-51.48627898796885)

No data found for target "81.87712822395483 -51.48627898796885".

333. Checking source_id 4785886941312921344 (RA=76.30968124678876, DEC=-47.937535542918475)
334. Checking source_id 4805600119646735616 (RA=83.3667058276365, DEC=-42.95553305572998)
335. Checking source_id 4838250838987898880 (RA=62.384660594435694, DEC=-44.5937681602659)
336. Checking source_id 4846689899968623744 (RA=53.23079051788499, DEC=-44.701350214389144)

No data found for target "53.23079051788499 -44.701350214389144".

337. Checking source_id 4860376345833699840 (RA=54.898570206777336, DEC=-35.42759363988114)

No data found for target "54.898570206777336 -35.42759363988114".

338. Checking source_id 4864160624337973248 (RA=68.17902996429045, DEC=-39.79100877620122)

No data found for target "68.17902996429045 -39.79100877620122".

339. Checking source_id 4872659466967320576 (RA=67.3272896118439, DEC=-31.39865271628241)
340. Checking source_id 4879015915487168384 (RA=69.23691490050261, DEC=-29.0569204851486)

No data found for target "69.23691490050261 -29.0569204851486".

341. Checking source_id 4883809068925124224 (RA=62.23165947039066, DEC=-31.482746317950557)
342. Checking source_id 4884761177275202176 (RA=66.63566693368529, DEC=-30.802598323056248)

No data found for target "66.63566693368529 -30.802598323056248".

343. Checking source_id 4894315447987680640 (RA=68.90113171549795, DEC=-25.46047870256822)
344. Checking source_id 4896480390678599168 (RA=66.04804319730742, DEC=-23.943154274248094)
345. Checking source_id 4912898156569562624 (RA=26.623503842306945, DEC=-53.65951511605823)
346. Checking source_id 4914733005253271040 (RA=18.321365594968658, DEC=-54.486623674742)

No data found for target "18.321365594968658 -54.486623674742".

347. Checking source_id 4919497979411495296 (RA=2.0695188524464223, DEC=-57.09822684087826)

No data found for target "2.0695188524464223 -57.09822684087826".

348. Checking source_id 4929042942932181888 (RA=17.94604714801365, DEC=-49.13780173027396)

No data found for target "17.94604714801365 -49.13780173027396".

349. Checking source_id 4941774600386872960 (RA=28.211506635601257, DEC=-48.095754425177795)

No data found for target "28.211506635601257 -48.095754425177795".

350. Checking source_id 4947513157730843136 (RA=41.29488660260175, DEC=-43.74395570978885)

No data found for target "41.29488660260175 -43.74395570978885".

351. Checking source_id 4960651016012601856 (RA=24.841366809333778, DEC=-39.60350836178757)
352. Checking source_id 4965689356248347648 (RA=37.034810770953925, DEC=-36.472406047033026)

No data found for target "37.034810770953925 -36.472406047033026".

353. Checking source_id 4966072879648455296 (RA=37.489187626886974, DEC=-36.11070763794735)

No data found for target "37.489187626886974 -36.11070763794735".

354. Checking source_id 4975284347548097152 (RA=11.424370322965071, DEC=-47.558161328122075)

No data found for target "11.424370322965071 -47.558161328122075".

355. Checking source_id 4975847194422433280 (RA=8.30811225525422, DEC=-47.55395581377568)

No data found for target "8.30811225525422 -47.55395581377568".

356. Checking source_id 4995796699034222464 (RA=2.4392791777364233, DEC=-42.02765540973986)
357. Checking source_id 5020179503252128768 (RA=31.449610334078532, DEC=-30.17617825921)

No data found for target "31.449610334078532 -30.17617825921".

358. Checking source_id 5039735554502890752 (RA=20.68377378657759, DEC=-25.78542674151736)
359. Checking source_id 5041034524411980288 (RA=17.329387245051528, DEC=-24.5073953704236)

No data found for target "17.329387245051528 -24.5073953704236".

360. Checking source_id 5055805741577757824 (RA=52.87633565748463, DEC=-30.71257633526702)

No data found for target "52.87633565748463 -30.71257633526702".

361. Checking source_id 5059643002799575424 (RA=46.97079038744201, DEC=-28.23657947424524)

No data found for target "46.97079038744201 -28.23657947424524".

362. Checking source_id 5075243629687810560 (RA=48.57727876178081, DEC=-23.15750510834894)

No data found for target "48.57727876178081 -23.15750510834894".

363. Checking source_id 5079067147013772288 (RA=43.66648548412693, DEC=-22.266581909507593)

No data found for target "43.66648548412693 -22.266581909507593".

364. Checking source_id 5082514940600694272 (RA=60.12104814020346, DEC=-25.87995956135253)

No data found for target "60.12104814020346 -25.87995956135253".

365. Checking source_id 5110641302736199424 (RA=58.583405672029585, DEC=-14.626996430366534)
366. Checking source_id 5123785831102567680 (RA=34.08872967380762, DEC=-22.012448796550615)
367. Checking source_id 5131300889999108608 (RA=36.875530606173776, DEC=-19.12877052888649)

No data found for target "36.875530606173776 -19.12877052888649".

368. Checking source_id 5142787797211936640 (RA=28.533593959764787, DEC=-15.607511219843047)
369. Checking source_id 5159273530961537280 (RA=44.543868419797654, DEC=-12.882602840627078)

No data found for target "44.543868419797654 -12.882602840627078".

370. Checking source_id 5183110874332308480 (RA=47.9036106160578, DEC=-4.278627146775743)

No data found for target "47.9036106160578 -4.278627146775743".

371. Checking source_id 5185165891628969984 (RA=40.314644601412986, DEC=-4.538542485444145)

No data found for target "40.314644601412986 -4.538542485444145".

372. Checking source_id 5189170557793054848 (RA=159.68433024045862, DEC=-86.54629290223104)
373. Checking source_id 5213167330349528064 (RA=117.3008524617764, DEC=-76.70272278517169)
374. Checking source_id 5260759175761502976 (RA=98.43896955100809, DEC=-75.62380392415764)

No data found for target "98.43896955100809 -75.62380392415764".

375. Checking source_id 5266917261213622144 (RA=100.87412359188694, DEC=-70.05487868120974)
376. Checking source_id 5287046368477870848 (RA=104.98256254599588, DEC=-61.74878384014599)
377. Checking source_id 5292028393100840320 (RA=110.21409706569334, DEC=-62.16902108648849)

No data found for target "110.21409706569334 -62.16902108648849".

378. Checking source_id 5381146215717550336 (RA=176.39577945210556, DEC=-40.933493409092144)

No data found for target "176.39577945210556 -40.933493409092144".

379. Checking source_id 5468091231551021184 (RA=159.43763962372515, DEC=-27.776254901109976)

No data found for target "159.43763962372515 -27.776254901109976".

380. Checking source_id 5471516004114550784 (RA=161.46467275513655, DEC=-23.15077023592966)
381. Checking source_id 5481843025342799104 (RA=96.4834930044876, DEC=-60.05701848235131)
382. Checking source_id 5486916932205092352 (RA=107.40960930410569, DEC=-57.06023470133151)

No data found for target "107.40960930410569 -57.06023470133151".

383. Checking source_id 5550620058937466880 (RA=95.27757860461126, DEC=-49.09274147732291)
384. Checking source_id 5571142580908768384 (RA=92.7211184738034, DEC=-43.40164255784951)

No data found for target "92.7211184738034 -43.40164255784951".

385. Checking source_id 5657274198660921472 (RA=148.8489090294773, DEC=-27.262009487759073)
386. Checking source_id 5677606810060597248 (RA=145.6464031860283, DEC=-19.235729064940955)

No data found for target "145.6464031860283 -19.235729064940955".

387. Checking source_id 5682008056323530368 (RA=142.8412957234274, DEC=-17.295762704607554)

No data found for target "142.8412957234274 -17.295762704607554".

388. Checking source_id 5683119044103789440 (RA=140.69502164812556, DEC=-15.791134557336749)

No data found for target "140.69502164812556 -15.791134557336749".

389. Checking source_id 5686163724944033792 (RA=148.1735302257391, DEC=-15.60441952077654)
390. Checking source_id 5690846274384548864 (RA=146.2242946880038, DEC=-12.348259270729132)

No data found for target "146.2242946880038 -12.348259270729132".

391. Checking source_id 5761985432616501376 (RA=133.39836837028676, DEC=-3.4931644292214545)

No data found for target "133.39836837028676 -3.4931644292214545".

392. Checking source_id 5776161813992756992 (RA=262.3503788640829, DEC=-80.14714892351998)

No data found for target "262.3503788640829 -80.14714892351998".

393. Checking source_id 5802998414627069696 (RA=267.1169966232858, DEC=-74.462112650771)
394. Checking source_id 5802998414627070080 (RA=267.1154248644766, DEC=-74.46618671420113)
395. Checking source_id 6113324752547911040 (RA=205.9239625297205, DEC=-40.04188776687056)
396. Checking source_id 6114232433761438208 (RA=209.53254015680207, DEC=-39.63592927128449)
397. Checking source_id 6119528334597735296 (RA=216.07789507666112, DEC=-35.242767894759034)
398. Checking source_id 6140884286374656000 (RA=197.33924464935492, DEC=-40.16195152209893)

No data found for target "197.33924464935492 -40.16195152209893".

399. Checking source_id 6160315989731008768 (RA=189.3413879822573, DEC=-32.01211771374125)

No data found for target "189.3413879822573 -32.01211771374125".

400. Checking source_id 6171593062022433920 (RA=206.69006617532065, DEC=-31.82305317678408)

No data found for target "206.69006617532065 -31.82305317678408".

401. Checking source_id 6173812151364882688 (RA=209.30431353578368, DEC=-29.375884964103)

No data found for target "209.30431353578368 -29.375884964103".

402. Checking source_id 6203502160773159424 (RA=221.02688491852965, DEC=-34.44835557219465)

No data found for target "221.02688491852965 -34.44835557219465".

403. Checking source_id 6213248060043565184 (RA=230.55627655949743, DEC=-27.825797312308065)

No data found for target "230.55627655949743 -27.825797312308065".

404. Checking source_id 6221167631840454400 (RA=216.5238030463142, DEC=-29.781111592648628)
405. Checking source_id 6235533167875990272 (RA=238.1869310006881, DEC=-26.38915421137295)

No data found for target "238.1869310006881 -26.38915421137295".

406. Checking source_id 6242063304871870592 (RA=241.6211962565556, DEC=-24.122605217741636)

No data found for target "241.6211962565556 -24.122605217741636".

407. Checking source_id 6274832977622107264 (RA=210.69268639294623, DEC=-24.528814983299633)

No data found for target "210.69268639294623 -24.528814983299633".

408. Checking source_id 6290519435137636224 (RA=209.7907314283468, DEC=-19.835179948860276)

No data found for target "209.7907314283468 -19.835179948860276".

409. Checking source_id 6302599662016881664 (RA=209.5831773084932, DEC=-13.273879021103491)

No data found for target "209.5831773084932 -13.273879021103491".

410. Checking source_id 6302909449418261120 (RA=213.94124035505024, DEC=-13.493135958190171)

No data found for target "213.94124035505024 -13.493135958190171".

411. Checking source_id 6311012064136913920 (RA=220.44099075609032, DEC=-14.45563075942006)
412. Checking source_id 6324308389531786112 (RA=217.7529796815058, DEC=-12.297869679498262)

No data found for target "217.7529796815058 -12.297869679498262".

413. Checking source_id 6337717243069148032 (RA=220.75503345248413, DEC=-5.654254209998345)

No data found for target "220.75503345248413 -5.654254209998345".

414. Checking source_id 6342940473056949120 (RA=326.6919266604704, DEC=-85.71878034422768)

No data found for target "326.6919266604704 -85.71878034422768".

415. Checking source_id 6343789261675614464 (RA=346.8620932514289, DEC=-84.86803600287753)

No data found for target "346.8620932514289 -84.86803600287753".

416. Checking source_id 6343965492773694464 (RA=352.6454136504384, DEC=-84.92220191651951)
417. Checking source_id 6359521108406068992 (RA=282.2114626702034, DEC=-82.24624920519395)
418. Checking source_id 6366571314402539008 (RA=304.05133275745055, DEC=-75.51775999531469)
419. Checking source_id 6367463327570835328 (RA=292.41454163597473, DEC=-74.74499106636954)
420. Checking source_id 6371660537113102976 (RA=321.98723385002035, DEC=-72.28794764107055)
421. Checking source_id 6381623044470172672 (RA=340.4960624875462, DEC=-75.00821792446833)
422. Checking source_id 6383229053001389312 (RA=332.5622450415509, DEC=-71.76929995017014)

No data found for target "332.5622450415509 -71.76929995017014".

423. Checking source_id 6386280060329151616 (RA=358.3593934660763, DEC=-70.94461574811649)

No data found for target "358.3593934660763 -70.94461574811649".

424. Checking source_id 6398188767690594048 (RA=336.09392717197517, DEC=-65.97694057827437)
425. Checking source_id 6402860489518406144 (RA=327.36082199142527, DEC=-63.11246709845328)

No data found for target "327.36082199142527 -63.11246709845328".

426. Checking source_id 6405457982659103872 (RA=333.46143166945996, DEC=-63.702023164643734)
427. Checking source_id 6408509574103239552 (RA=336.1020654088805, DEC=-58.4372924747797)
428. Checking source_id 6415630939116638464 (RA=292.7596556224023, DEC=-73.61878815166652)
429. Checking source_id 6421374031949679744 (RA=284.01803778313814, DEC=-69.36730317347698)
430. Checking source_id 6424217300298269568 (RA=301.7005986943156, DEC=-67.6140994648447)
431. Checking source_id 6437366909611503104 (RA=276.58219550905926, DEC=-65.79742068685235)

No data found for target "276.58219550905926 -65.79742068685235".

432. Checking source_id 6446274293824799488 (RA=289.91952257165434, DEC=-59.92317486728616)

No data found for target "289.91952257165434 -59.92317486728616".

433. Checking source_id 6456884409233519360 (RA=315.805198569885, DEC=-56.96185322955984)

No data found for target "315.805198569885 -56.96185322955984".

434. Checking source_id 6462049502543522688 (RA=323.9144197383885, DEC=-53.42468721801943)
435. Checking source_id 6468337884421010048 (RA=304.9573471563971, DEC=-58.28012185634601)

No data found for target "304.9573471563971 -58.28012185634601".

436. Checking source_id 6469383588698276480 (RA=306.90363380423844, DEC=-54.88222294269785)

No data found for target "306.90363380423844 -54.88222294269785".

437. Checking source_id 6472836050915560448 (RA=302.1006290894661, DEC=-55.357946447725794)
438. Checking source_id 6478328150150225664 (RA=315.27888909461694, DEC=-49.12456979699407)

No data found for target "315.27888909461694 -49.12456979699407".

439. Checking source_id 6487483783474213632 (RA=359.6844071176511, DEC=-62.761415023739694)

No data found for target "359.6844071176511 -62.761415023739694".

440. Checking source_id 6487693790194944128 (RA=358.6747226512832, DEC=-61.58699736797349)

No data found for target "358.6747226512832 -61.58699736797349".

441. Checking source_id 6522188390538224640 (RA=356.6320742231057, DEC=-50.7263749471709)

No data found for target "356.6320742231057 -50.7263749471709".

442. Checking source_id 6554995893362365952 (RA=348.7598304428063, DEC=-35.472806727469305)

No data found for target "348.7598304428063 -35.472806727469305".

443. Checking source_id 6561146458331160320 (RA=328.6866968776705, DEC=-46.99435689427491)

No data found for target "328.6866968776705 -46.99435689427491".

444. Checking source_id 6572811211549713792 (RA=327.88311437897886, DEC=-40.290948939179614)

No data found for target "327.88311437897886 -40.290948939179614".

445. Checking source_id 6575069780231675264 (RA=330.6269230434408, DEC=-37.08193913674626)

No data found for target "330.6269230434408 -37.08193913674626".

446. Checking source_id 6599565765426015232 (RA=334.33070901737386, DEC=-34.73633155418452)

No data found for target "334.33070901737386 -34.73633155418452".

447. Checking source_id 6600863910701061632 (RA=339.71603972979403, DEC=-32.27585374173224)
448. Checking source_id 6608187792013181312 (RA=339.6059287587044, DEC=-29.35802125906652)
449. Checking source_id 6612817217002464128 (RA=329.70705396749236, DEC=-32.47323280840755)

No data found for target "329.70705396749236 -32.47323280840755".

450. Checking source_id 6612817835477756160 (RA=329.70265125152406, DEC=-32.44203323266612)

No data found for target "329.70265125152406 -32.44203323266612".

451. Checking source_id 6613969195950456448 (RA=334.858951355117, DEC=-31.061723984283592)

No data found for target "334.858951355117 -31.061723984283592".

452. Checking source_id 6623351805412369024 (RA=342.0203381724408, DEC=-24.369627417603155)

No data found for target "342.0203381724408 -24.369627417603155".

453. Checking source_id 6637017330494491648 (RA=283.70836681424106, DEC=-57.07969410501362)

No data found for target "283.70836681424106 -57.07969410501362".

454. Checking source_id 6645504151509887744 (RA=293.5167610204471, DEC=-52.42173789201841)
455. Checking source_id 6650117736660187136 (RA=280.7780058472517, DEC=-54.61562415094667)

No data found for target "280.7780058472517 -54.61562415094667".

456. Checking source_id 6658123517042686464 (RA=288.164090058716, DEC=-50.271765612752674)
457. Checking source_id 6671213104189712000 (RA=298.49966039519774, DEC=-47.8150277282357)

No data found for target "298.49966039519774 -47.8150277282357".

458. Checking source_id 6672112470338969856 (RA=302.4651437572208, DEC=-47.527716567604266)

No data found for target "302.4651437572208 -47.527716567604266".

459. Checking source_id 6674554829263069440 (RA=309.34041351902783, DEC=-46.73127945877358)
460. Checking source_id 6742962972412390912 (RA=290.5241642082332, DEC=-35.063462184524234)
461. Checking source_id 6744957928883188736 (RA=294.61464248866554, DEC=-32.52523817811287)

No data found for target "294.61464248866554 -32.52523817811287".

462. Checking source_id 6768500538717144064 (RA=296.2257504183332, DEC=-23.633980573875828)

No data found for target "296.2257504183332 -23.633980573875828".

463. Checking source_id 6773453838597541760 (RA=315.2680353695968, DEC=-41.24370426778464)

No data found for target "315.2680353695968 -41.24370426778464".

464. Checking source_id 6779821003058453120 (RA=312.5691416793731, DEC=-34.413153176093374)

No data found for target "312.5691416793731 -34.413153176093374".

465. Checking source_id 6805970245721550080 (RA=314.1147209082977, DEC=-24.00400432430843)

No data found for target "314.1147209082977 -24.00400432430843".

466. Checking source_id 6817950657560102016 (RA=326.69107096359306, DEC=-21.29660962151476)
467. Checking source_id 6823449766182657280 (RA=328.76028235110175, DEC=-20.24027219429661)
468. Checking source_id 6851779920225659136 (RA=301.1288564266629, DEC=-23.70213617627802)

No data found for target "301.1288564266629 -23.70213617627802".

469. Checking source_id 6853658057885526912 (RA=301.3968679556646, DEC=-22.304962207672475)
470. Checking source_id 6856077189625042688 (RA=308.40224210084426, DEC=-21.336459771050528)
471. Checking source_id 6858958940879829248 (RA=312.4711253064467, DEC=-17.26945706554899)

No data found for target "312.4711253064467 -17.26945706554899".

472. Checking source_id 6868107358662346112 (RA=295.50308205557945, DEC=-21.069272230763502)
473. Checking source_id 6868221463056407168 (RA=295.553370876108, DEC=-20.764012353990857)

No data found for target "295.553370876108 -20.764012353990857".

474. Checking source_id 6895572437565417856 (RA=317.85070768221846, DEC=-9.677453339060431)

No data found for target "317.85070768221846 -9.677453339060431".

475. Checking source_id 6900333494712655616 (RA=311.68342967315823, DEC=-11.80400321707132)

No data found for target "311.68342967315823 -11.80400321707132".

476. Checking source_id 6914281796143286784 (RA=310.68929166017307, DEC=-5.004806087747568)
477. Checking source_id 6916929660661726208 (RA=313.28984955557723, DEC=-1.552171010067834)

No data found for target "313.28984955557723 -1.552171010067834".

478. Checking source_id 121254932585133568 (RA=54.03685781019895, DEC=31.31038873961227)
479. Checking source_id 144312344255035392 (RA=68.39367443219042, DEC=20.74463639402465)

No data found for target "68.39367443219042 20.74463639402465".

480. Checking source_id 150510158159630848 (RA=65.74709242385883, DEC=25.986214128203905)
481. Checking source_id 156150240492946816 (RA=77.66340440529314, DEC=29.78023889010632)
482. Checking source_id 179700710496485504 (RA=67.60697228135813, DEC=39.84732582326925)

No data found for target "67.60697228135813 39.84732582326925".

483. Checking source_id 200296663143599104 (RA=73.15109158635963, DEC=40.70183928537737)

No data found for target "73.15109158635963 40.70183928537737".

484. Checking source_id 205533465225342208 (RA=76.27525560161628, DEC=44.23424149518413)
485. Checking source_id 207033680124098048 (RA=76.39343357193754, DEC=46.79953911392597)
486. Checking source_id 230171768457140736 (RA=59.3320361570653, DEC=41.12839689730314)
487. Checking source_id 258996015538087680 (RA=71.58398349941925, DEC=48.74489866356334)

No data found for target "71.58398349941925 48.74489866356334".

488. Checking source_id 260343123440688128 (RA=72.26910056105879, DEC=51.643088269642206)

No data found for target "72.26910056105879 51.643088269642206".

489. Checking source_id 265201384281320448 (RA=87.85441435895838, DEC=55.18811792034226)
490. Checking source_id 269066953631488384 (RA=89.98201323957848, DEC=58.56976827470822)
491. Checking source_id 353610331133759744 (RA=35.5628493353625, DEC=45.70035456975228)

No data found for target "35.5628493353625 45.70035456975228".

492. Checking source_id 358249819229900672 (RA=32.225052363016104, DEC=49.44771631277939)

No data found for target "32.225052363016104 49.44771631277939".

493. Checking source_id 358269546017619840 (RA=31.76767495536706, DEC=49.643504110332174)

No data found for target "31.76767495536706 49.643504110332174".

494. Checking source_id 393155984814848128 (RA=2.025945508249953, DEC=47.95067855186984)
495. Checking source_id 393621524910343296 (RA=2.2322728822606455, DEC=49.31654365243212)

No data found for target "2.2322728822606455 49.31654365243212".
No data found for target "2.2322728822606455 49.31654365243212".

496. Checking source_id 411311395692644224 (RA=15.495585706669338, DEC=54.18217771927336)

No data found for target "15.495585706669338 54.18217771927336".

497. Checking source_id 415665118140313472 (RA=9.63951695492825, DEC=51.46623313406483)
498. Checking source_id 418363560198079616 (RA=9.826094856422966, DEC=55.13591102822271)

No data found for target "9.826094856422966 55.13591102822271".

499. Checking source_id 419624356438705152 (RA=6.314208313156801, DEC=54.380246070851605)

No data found for target "6.314208313156801 54.380246070851605".

500. Checking source_id 423027104407576576 (RA=2.874734923550554, DEC=59.13922658078038)
501. Checking source_id 439595542043685888 (RA=44.527654103364355, DEC=50.2384703559099)

No data found for target "44.527654103364355 50.2384703559099".

502. Checking source_id 445100418805396608 (RA=52.70255404316823, DEC=54.231972478973546)
503. Checking source_id 459215468053012096 (RA=34.98428465514067, DEC=59.32335305221488)
504. Checking source_id 466652427262218240 (RA=45.012514355122065, DEC=62.86500045511667)
505. Checking source_id 474987206435652608 (RA=58.29378718240847, DEC=62.56771136910784)
506. Checking source_id 476809509515283712 (RA=63.07602734404104, DEC=64.73018080218111)

No data found for target "63.07602734404104 64.73018080218111".

507. Checking source_id 477826420331704064 (RA=73.41994024991934, DEC=62.31662864915945)

No data found for target "73.41994024991934 62.31662864915945".

508. Checking source_id 482089261274984064 (RA=73.62491412218532, DEC=65.07763013001318)
509. Checking source_id 505516521175942784 (RA=29.850702638903563, DEC=58.52028397205597)
510. Checking source_id 515045129459646080 (RA=31.795389122280643, DEC=64.28574993877805)
511. Checking source_id 522864272041351296 (RA=15.83964458528098, DEC=62.36589259248621)
512. Checking source_id 532266024164292352 (RA=23.291015466764694, DEC=69.96894582310217)
513. Checking source_id 549007291282705024 (RA=44.339286532301905, DEC=76.55134902167823)

No data found for target "44.339286532301905 76.55134902167823".

514. Checking source_id 555032443207370880 (RA=61.66178755097324, DEC=79.2652664645624)

No data found for target "61.66178755097324 79.2652664645624".

515. Checking source_id 671436777166606976 (RA=114.71207091660123, DEC=18.488193351242423)
516. Checking source_id 890284258753196544 (RA=109.07456243442758, DEC=33.150948447796246)

No data found for target "109.07456243442758 33.150948447796246".

517. Checking source_id 939599584345993984 (RA=105.84622747575096, DEC=34.698233312449034)
518. Checking source_id 970354749937140736 (RA=90.62210758518228, DEC=49.86182103675996)

No data found for target "90.62210758518228 49.86182103675996".

519. Checking source_id 971499272821709440 (RA=93.5071616638108, DEC=51.668469680157074)

No data found for target "93.5071616638108 51.668469680157074".

520. Checking source_id 997801721262070912 (RA=96.4717182937526, DEC=56.17135899080708)

No data found for target "96.4717182937526 56.17135899080708".

521. Checking source_id 1104878103513141760 (RA=90.61043756165334, DEC=66.34230092025918)

No data found for target "90.61043756165334 66.34230092025918".

522. Checking source_id 1752189568342546048 (RA=305.84222990657156, DEC=8.003250060157944)
523. Checking source_id 1762523981210977664 (RA=311.1575675254911, DEC=15.292303822792627)

No data found for target "311.1575675254911 15.292303822792627".

524. Checking source_id 1810616448010879488 (RA=310.14718809392286, DEC=15.502590198203675)

No data found for target "310.14718809392286 15.502590198203675".

525. Checking source_id 1862034696988864896 (RA=305.5638248021488, DEC=31.295355736427048)

No data found for target "305.5638248021488 31.295355736427048".

526. Checking source_id 1905816425352678656 (RA=336.25690873315784, DEC=35.668126158187434)
527. Checking source_id 1923896622760418176 (RA=352.34657450570336, DEC=41.46426656329359)

No data found for target "352.34657450570336 41.46426656329359".

528. Checking source_id 1934862945577481344 (RA=345.7178593481215, DEC=43.6376403112615)
529. Checking source_id 1941011930001137280 (RA=358.73570743127874, DEC=50.60416096368615)
530. Checking source_id 1952802469918554368 (RA=326.5928819418585, DEC=38.21751708114409)
531. Checking source_id 1958030617647715328 (RA=332.8501471342748, DEC=40.999937747390554)
532. Checking source_id 1965478468902062464 (RA=321.13780325406816, DEC=40.06853292389345)

No data found for target "321.13780325406816 40.06853292389345".

533. Checking source_id 1974606167761195904 (RA=326.7361495066119, DEC=46.635039174978616)
534. Checking source_id 2001345397199713152 (RA=336.2346972856473, DEC=52.007111377537385)

No data found for target "336.2346972856473 52.007111377537385".

535. Checking source_id 2012619720701400192 (RA=355.96646640493077, DEC=61.03541809766475)

No data found for target "355.96646640493077 61.03541809766475".

536. Checking source_id 2014653404891943936 (RA=343.5831299528126, DEC=60.9948603958803)

No data found for target "343.5831299528126 60.9948603958803".

537. Checking source_id 2022893621784904064 (RA=291.50765658547584, DEC=24.438522554529968)
538. Checking source_id 2042871958509344896 (RA=287.1236406175739, DEC=32.28000653137807)
539. Checking source_id 2045458628362127360 (RA=294.6829962716154, DEC=33.19441313934374)
540. Checking source_id 2047690533883897856 (RA=297.17034072865096, DEC=35.92017560607515)
541. Checking source_id 2050589430625453824 (RA=288.1237527690882, DEC=35.56394945542676)
542. Checking source_id 2054269874008075904 (RA=305.578413996564, DEC=32.287514824881384)
543. Checking source_id 2056115198113182208 (RA=307.0937101191311, DEC=34.20220748536728)

No data found for target "307.0937101191311 34.20220748536728".

544. Checking source_id 2063967910147595008 (RA=309.1927827933898, DEC=38.84173999457955)
545. Checking source_id 2066768499405895296 (RA=313.2412180042452, DEC=43.17197818114904)

No data found for target "313.2412180042452 43.17197818114904".

546. Checking source_id 2080285727861817088 (RA=297.79001858504904, DEC=46.48457360658962)

No data found for target "297.79001858504904 46.48457360658962".

547. Checking source_id 2090085056523454464 (RA=280.4944113394081, DEC=31.83052644422543)
548. Checking source_id 2091177593123254016 (RA=278.90744884954285, DEC=32.994787158699616)

No data found for target "278.90744884954285 32.994787158699616".

549. Checking source_id 2098413719661573248 (RA=280.4043356891839, DEC=39.70257169518205)

No data found for target "280.4043356891839 39.70257169518205".

550. Checking source_id 2098514324976071424 (RA=280.8414837270263, DEC=40.67522342269669)

No data found for target "280.8414837270263 40.67522342269669".

551. Checking source_id 2105033123258653056 (RA=283.7690701880948, DEC=42.99751921986174)
552. Checking source_id 2107257297843283584 (RA=284.1100119283428, DEC=46.382926799980986)

No data found for target "284.1100119283428 46.382926799980986".

553. Checking source_id 2119686379142441472 (RA=282.6902545804929, DEC=47.97148162043484)
554. Checking source_id 2125777643503392640 (RA=291.8257765035261, DEC=42.53079017110482)

No data found for target "291.8257765035261 42.53079017110482".

555. Checking source_id 2135110259540829824 (RA=294.0599087081086, DEC=50.22063557211082)
556. Checking source_id 2173367633501430272 (RA=324.5723456671, DEC=52.955345203478224)
557. Checking source_id 2185710338703934976 (RA=301.25028584217137, DEC=54.43021426747369)

No data found for target "301.25028584217137 54.43021426747369".

558. Checking source_id 2188318517720321664 (RA=306.5243172601894, DEC=58.57537971545967)

No data found for target "306.5243172601894 58.57537971545967".

559. Checking source_id 2213428064767263360 (RA=346.8886073691008, DEC=68.66835203448122)

No data found for target "346.8886073691008 68.66835203448122".

560. Checking source_id 2218904319868065408 (RA=333.85898858277557, DEC=66.22529504635877)
561. Checking source_id 2222540228723911168 (RA=326.67209809426436, DEC=66.80387671285244)

No data found for target "326.67209809426436 66.80387671285244".

562. Checking source_id 2247535151679497472 (RA=299.56795496573375, DEC=65.04026975891064)

No data found for target "299.56795496573375 65.04026975891064".

563. Checking source_id 2281046483684995840 (RA=336.79143736412533, DEC=77.86718788883624)

No data found for target "336.79143736412533 77.86718788883624".

564. Checking source_id 2282790893241302144 (RA=350.7290232368062, DEC=78.79433614628547)
565. Checking source_id 2913314288686472576 (RA=93.44641834723038, DEC=-23.906400629805045)
566. Checking source_id 2913411183147100416 (RA=93.43901141965836, DEC=-23.86821581115909)

No data found for target "93.43901141965836 -23.86821581115909".

567. Checking source_id 2918040883015489408 (RA=90.59401922772396, DEC=-20.32646095303724)

No data found for target "90.59401922772396 -20.32646095303724".

568. Checking source_id 2920124904228150144 (RA=100.91781659682088, DEC=-26.412851737979935)

No data found for target "100.91781659682088 -26.412851737979935".

569. Checking source_id 2926033267402660224 (RA=101.67024419717264, DEC=-21.83802845727015)
570. Checking source_id 2999254213453678720 (RA=89.16931209956947, DEC=-10.309936799168852)
571. Checking source_id 3005440443830195968 (RA=90.72650698393748, DEC=-9.253679424751372)

No data found for target "90.72650698393748 -9.253679424751372".

572. Checking source_id 3007559370624135424 (RA=94.836432883577, DEC=-6.658919729456425)

No data found for target "94.836432883577 -6.658919729456425".

573. Checking source_id 3023121827755777280 (RA=85.55220113669213, DEC=-5.461181586870268)

No data found for target "85.55220113669213 -5.461181586870268".

574. Checking source_id 3026511175437908096 (RA=112.05454567294036, DEC=-18.790322998386273)
575. Checking source_id 3046640175314154624 (RA=106.30041622285356, DEC=-10.131001534433214)
576. Checking source_id 3051343817347672576 (RA=107.63069808891784, DEC=-8.712967693425067)
577. Checking source_id 3059182338820698624 (RA=108.29665561709618, DEC=-5.198202455814469)
578. Checking source_id 3059246454092369024 (RA=109.32310142871492, DEC=-5.0193865914700995)

No data found for target "109.32310142871492 -5.0193865914700995".

579. Checking source_id 3060641356390249728 (RA=112.19128658651584, DEC=-3.301647006516706)

No data found for target "112.19128658651584 -3.301647006516706".

580. Checking source_id 3080857458209146368 (RA=117.42488030146365, DEC=-3.3430177047924063)
581. Checking source_id 3089829644889680256 (RA=122.7004539534854, DEC=1.1540989604627692)
582. Checking source_id 3104733181410232576 (RA=98.87393995438822, DEC=-4.0547741963145425)
583. Checking source_id 3127503620545728128 (RA=100.54682814138062, DEC=3.5801351731802407)
584. Checking source_id 3134682194522547968 (RA=113.57319136841932, DEC=0.9832433944126404)

No data found for target "113.57319136841932 0.9832433944126404".

585. Checking source_id 3136232952593850496 (RA=112.87192845713916, DEC=2.819034946832578)
586. Checking source_id 3136952686035250688 (RA=116.1658359308822, DEC=3.5504844454883244)

No data found for target "116.1658359308822 3.5504844454883244".

587. Checking source_id 3143635723866162432 (RA=117.96608429205932, DEC=5.5473917843088385)

No data found for target "117.96608429205932 5.5473917843088385".

588. Checking source_id 3144499458967932672 (RA=119.53643234079507, DEC=7.283595270088088)

No data found for target "119.53643234079507 7.283595270088088".

589. Checking source_id 3154550541435395200 (RA=106.30160565523498, DEC=8.429349117067947)

No data found for target "106.30160565523498 8.429349117067947".

590. Checking source_id 3316364602541746048 (RA=90.01597644159976, DEC=2.7063740799024933)

No data found for target "90.01597644159976 2.7063740799024933".

591. Checking source_id 3317901440625203968 (RA=94.29340278756932, DEC=5.118125291285412)

No data found for target "94.29340278756932 5.118125291285412".

592. Checking source_id 3325157736332326784 (RA=92.8333873160516, DEC=7.184300019759825)
593. Checking source_id 3336130626153639424 (RA=85.22382048241539, DEC=8.905037560985615)
594. Checking source_id 3339914973377653760 (RA=84.16024229906046, DEC=11.296613294698856)
595. Checking source_id 3341624061123288448 (RA=83.71660430393523, DEC=13.87787924781139)

No data found for target "83.71660430393523 13.87787924781139".

596. Checking source_id 3348805143361118464 (RA=89.00194337351587, DEC=15.766279215720711)
597. Checking source_id 3352081447497931264 (RA=100.42870725855788, DEC=12.445392442104405)
598. Checking source_id 3352091927220152320 (RA=99.02567810888785, DEC=11.613741303546275)

No data found for target "99.02567810888785 11.613741303546275".

599. Checking source_id 3361034083487398016 (RA=106.14366570307368, DEC=16.956605362921632)
600. Checking source_id 3390044040652614656 (RA=82.65453223954857, DEC=15.24064022866458)
601. Checking source_id 3394484074763973504 (RA=80.44960452985814, DEC=17.343472744693543)
602. Checking source_id 3410478399832994688 (RA=68.65672101895085, DEC=19.10111134882547)
603. Checking source_id 3411398347466374144 (RA=70.73293563415463, DEC=21.473566186536463)
604. Checking source_id 3418324583527645440 (RA=75.32477273200419, DEC=22.61536006911671)

No data found for target "75.32477273200419 22.61536006911671".

605. Checking source_id 3428298528382128000 (RA=88.25801375874899, DEC=25.12803987623394)
606. Checking source_id 3435919896308345856 (RA=98.6395067289538, DEC=31.50140313353504)
607. Checking source_id 3449170488894369792 (RA=83.2148749335413, DEC=33.827735578720784)

No data found for target "83.2148749335413 33.827735578720784".

608. Checking source_id 4038724053950164096 (RA=271.5994368768923, DEC=-36.02315817876133)

No data found for target "271.5994368768923 -36.02315817876133".

609. Checking source_id 4040839376832467584 (RA=268.5107931154532, DEC=-34.67277670489463)

No data found for target "268.5107931154532 -34.67277670489463".

610. Checking source_id 4055579464064558592 (RA=266.6704915930946, DEC=-32.23412636909977)
611. Checking source_id 4078319494857310336 (RA=280.54710817071043, DEC=-23.484031970853025)
612. Checking source_id 4092990622155744000 (RA=276.6302402477138, DEC=-19.39395723243286)

No data found for target "276.6302402477138 -19.39395723243286".

613. Checking source_id 4095396422225930624 (RA=270.90095793365253, DEC=-18.98205434475698)

No data found for target "270.90095793365253 -18.98205434475698".

614. Checking source_id 4101968375059565568 (RA=282.00420159430814, DEC=-14.581942889145273)

No data found for target "282.00420159430814 -14.581942889145273".

615. Checking source_id 4110023156763233408 (RA=261.8107667727851, DEC=-25.162126124890616)

No data found for target "261.8107667727851 -25.162126124890616".

616. Checking source_id 4127182375667696128 (RA=254.13911786858904, DEC=-20.77796755384291)
617. Checking source_id 4130971047908354304 (RA=249.4304219999168, DEC=-20.226456686831902)
618. Checking source_id 4165561928540617856 (RA=266.6220201822353, DEC=-8.712042478984)

No data found for target "266.6220201822353 -8.712042478984".
No data found for target "266.6220201822353 -8.712042478984".

619. Checking source_id 4168368844280868992 (RA=263.5353570622817, DEC=-8.832425873814643)

No data found for target "263.5353570622817 -8.832425873814643".
No data found for target "263.5353570622817 -8.832425873814643".

620. Checking source_id 4177911333902753280 (RA=272.2238175099148, DEC=-2.1159832414070445)
621. Checking source_id 4192723988912416256 (RA=300.9931913964132, DEC=-8.130958023358552)

No data found for target "300.9931913964132 -8.130958023358552".

622. Checking source_id 4202659377841518720 (RA=285.81106903339054, DEC=-9.535830690792572)
623. Checking source_id 4213581106021661184 (RA=292.77003917182395, DEC=-3.102897138507079)

No data found for target "292.77003917182395 -3.102897138507079".

624. Checking source_id 4223813264304668288 (RA=302.32583654605094, DEC=-1.2289714355165018)

No data found for target "302.32583654605094 -1.2289714355165018".

625. Checking source_id 4242728884389090944 (RA=303.2508406645244, DEC=1.2158307317171082)
626. Checking source_id 4247106761739962880 (RA=301.23744889203846, DEC=3.350649778524621)

No data found for target "301.23744889203846 3.350649778524621".

627. Checking source_id 4257891802569298048 (RA=277.6634404154124, DEC=-3.9390440317740865)

No data found for target "277.6634404154124 -3.9390440317740865".

628. Checking source_id 4276632394156013440 (RA=276.022285849461, DEC=1.6867594792255736)
629. Checking source_id 4277318077096011264 (RA=274.0739324349659, DEC=1.5214295166369465)

No data found for target "274.0739324349659 1.5214295166369465".

630. Checking source_id 4279261876207080576 (RA=283.3570176109194, DEC=2.8470624550523547)

No data found for target "283.3570176109194 2.8470624550523547".

631. Checking source_id 4286249341336984576 (RA=282.0747587449577, DEC=7.690323894810538)

No data found for target "282.0747587449577 7.690323894810538".

632. Checking source_id 4311982650767794176 (RA=283.5714196687941, DEC=10.969734789639295)
633. Checking source_id 4361639417663824768 (RA=259.0868121132202, DEC=-5.398155460437159)

No data found for target "259.0868121132202 -5.398155460437159".
No data found for target "259.0868121132202 -5.398155460437159".

634. Checking source_id 4363875373342033664 (RA=261.5634344754104, DEC=-3.192392272704998)

No data found for target "261.5634344754104 -3.192392272704998".
No data found for target "261.5634344754104 -3.192392272704998".

635. Checking source_id 4470812298018311296 (RA=274.13072292110206, DEC=4.881193235821266)

No data found for target "274.13072292110206 4.881193235821266".

636. Checking source_id 4475881317196185728 (RA=268.5686657879008, DEC=7.377832327281468)

No data found for target "268.5686657879008 7.377832327281468".
No data found for target "268.5686657879008 7.377832327281468".

637. Checking source_id 4489306942580947584 (RA=265.4751620316947, DEC=9.680499876229684)

No data found for target "265.4751620316947 9.680499876229684".
No data found for target "265.4751620316947 9.680499876229684".

638. Checking source_id 4496383055821714816 (RA=269.59373567871177, DEC=12.760552335950688)

No data found for target "269.59373567871177 12.760552335950688".

639. Checking source_id 4498055584805914752 (RA=271.16198277595925, DEC=13.904135825968742)
640. Checking source_id 4502369583096912896 (RA=271.7024404523592, DEC=17.347173925497184)
641. Checking source_id 4505805591300126080 (RA=280.6872687939103, DEC=13.906220985923316)

No data found for target "280.6872687939103 13.906220985923316".

642. Checking source_id 4508377078422114944 (RA=279.0809524821553, DEC=13.608565199505213)

No data found for target "279.0809524821553 13.608565199505213".

643. Checking source_id 4512525016089353472 (RA=281.34496634633183, DEC=18.865092511988657)
644. Checking source_id 4519789081415296128 (RA=286.8027296402767, DEC=20.875538401484672)

No data found for target "286.8027296402767 20.875538401484672".

645. Checking source_id 4519789321942643072 (RA=286.7709107522999, DEC=20.88648751787881)

No data found for target "286.7709107522999 20.88648751787881".

646. Checking source_id 4525711600783788160 (RA=279.38295544494116, DEC=20.51039866122592)
647. Checking source_id 4534214948839463040 (RA=282.9185149722373, DEC=24.458792373775765)

No data found for target "282.9185149722373 24.458792373775765".

648. Checking source_id 4535928365908540416 (RA=280.2931336884971, DEC=24.787728362716255)

No data found for target "280.2931336884971 24.787728362716255".

649. Checking source_id 4535928365908541440 (RA=280.2932736323553, DEC=24.78903471867591)

No data found for target "280.2932736323553 24.78903471867591".

650. Checking source_id 4579825847951057792 (RA=273.2784750722023, DEC=26.030906428526674)
651. Checking source_id 4586421272746553472 (RA=275.86767226420693, DEC=28.166943770663465)
652. Checking source_id 4587614930058979584 (RA=279.8882509500303, DEC=29.870257114332887)
653. Checking source_id 5199087706000356096 (RA=161.9002962835104, DEC=-79.46369785139531)

No data found for target "161.9002962835104 -79.46369785139531".

654. Checking source_id 5222018879990530304 (RA=133.76679892825808, DEC=-71.59438347686567)

No data found for target "133.76679892825808 -71.59438347686567".

655. Checking source_id 5225863906515477376 (RA=163.8163930280901, DEC=-73.9368211911611)
656. Checking source_id 5241011156681563136 (RA=166.13864488936107, DEC=-62.54316032322312)
657. Checking source_id 5249254676369630336 (RA=144.214659619105, DEC=-65.23023843939158)
658. Checking source_id 5249863805819472640 (RA=145.71175224473672, DEC=-63.63190837805288)

No data found for target "145.71175224473672 -63.63190837805288".

659. Checking source_id 5271055243163629056 (RA=124.53289609935436, DEC=-68.31451297878304)

No data found for target "124.53289609935436 -68.31451297878304".

660. Checking source_id 5274724279106403968 (RA=120.63020270507428, DEC=-66.0264302882151)

No data found for target "120.63020270507428 -66.0264302882151".

661. Checking source_id 5291484512805323264 (RA=121.444646526896, DEC=-59.21648809056944)

No data found for target "121.444646526896 -59.21648809056944".

662. Checking source_id 5293288295987250816 (RA=110.83713664387948, DEC=-60.10162913000041)

No data found for target "110.83713664387948 -60.10162913000041".

663. Checking source_id 5298261284001871616 (RA=134.02504674847916, DEC=-61.96276891065736)
664. Checking source_id 5302788969815543936 (RA=129.50851733832943, DEC=-58.934301092646784)

No data found for target "129.50851733832943 -58.934301092646784".

665. Checking source_id 5307525906414825216 (RA=147.10558785257808, DEC=-56.73799973608294)

No data found for target "147.10558785257808 -56.73799973608294".

666. Checking source_id 5309974484478157696 (RA=139.21177443154738, DEC=-55.931717293874456)

No data found for target "139.21177443154738 -55.931717293874456".

667. Checking source_id 5315595737654226304 (RA=125.69448341721365, DEC=-57.4459015804563)

No data found for target "125.69448341721365 -57.4459015804563".

668. Checking source_id 5315595737654226560 (RA=125.69640715493324, DEC=-57.44392391891117)

No data found for target "125.69640715493324 -57.44392391891117".

669. Checking source_id 5344026286547761664 (RA=176.9689952882439, DEC=-55.06914073247352)
670. Checking source_id 5353126879893514368 (RA=164.52226495558665, DEC=-55.42154439805064)
671. Checking source_id 5380149023092265856 (RA=179.90447706741833, DEC=-42.946229979317195)

No data found for target "179.90447706741833 -42.946229979317195".

672. Checking source_id 5393446658454453632 (RA=162.05388771666577, DEC=-39.93962594730691)
673. Checking source_id 5418743844032438400 (RA=150.12849579829455, DEC=-41.50815733346062)

No data found for target "150.12849579829455 -41.50815733346062".

674. Checking source_id 5424690587034982144 (RA=143.35813068013894, DEC=-43.89273302384089)
675. Checking source_id 5432670704985289088 (RA=145.8742485909251, DEC=-38.56630443256017)
676. Checking source_id 5439029627401396096 (RA=146.491875412928, DEC=-32.89101863068049)

No data found for target "146.491875412928 -32.89101863068049".

677. Checking source_id 5440359486716251904 (RA=157.78388333811384, DEC=-41.46334165948587)
678. Checking source_id 5441169002153568512 (RA=159.8833472486551, DEC=-38.3370450973924)
679. Checking source_id 5458784415381054464 (RA=151.1632016429737, DEC=-33.58751841752631)

No data found for target "151.1632016429737 -33.58751841752631".

680. Checking source_id 5492622847798742272 (RA=114.05296644815438, DEC=-51.920572905284935)

No data found for target "114.05296644815438 -51.920572905284935".

681. Checking source_id 5519117229744210944 (RA=119.2234839106459, DEC=-45.63440964675406)

No data found for target "119.2234839106459 -45.63440964675406".

682. Checking source_id 5529120822749728384 (RA=130.17026521119897, DEC=-38.5440354728072)
683. Checking source_id 5538156819768871552 (RA=118.72808136767864, DEC=-38.1588602813617)

No data found for target "118.72808136767864 -38.1588602813617".

684. Checking source_id 5559035514776717312 (RA=104.43647190771412, DEC=-44.291651313997995)

No data found for target "104.43647190771412 -44.291651313997995".

685. Checking source_id 5559035514779971456 (RA=104.4373295461301, DEC=-44.29139605439596)

No data found for target "104.4373295461301 -44.29139605439596".

686. Checking source_id 5565156633450986752 (RA=107.756214337062, DEC=-38.416464112266354)

No data found for target "107.756214337062 -38.416464112266354".

687. Checking source_id 5588141992752796800 (RA=113.0312367991138, DEC=-36.124874823995825)

No data found for target "113.0312367991138 -36.124874823995825".

688. Checking source_id 5590736084278574464 (RA=109.52970180819229, DEC=-35.03913110858024)
689. Checking source_id 5599170330597007360 (RA=114.23733886623396, DEC=-30.406159966819494)

No data found for target "114.23733886623396 -30.406159966819494".

690. Checking source_id 5605438925569442432 (RA=111.65703095378969, DEC=-30.552171859726773)

No data found for target "111.65703095378969 -30.552171859726773".

691. Checking source_id 5611909104822545152 (RA=112.50772620155806, DEC=-28.517137799167745)
692. Checking source_id 5638902733763290752 (RA=128.88177876022422, DEC=-34.012228263178855)

No data found for target "128.88177876022422 -34.012228263178855".

693. Checking source_id 5642693123990628480 (RA=132.54220377468857, DEC=-28.367734260766717)
694. Checking source_id 5645479806157346688 (RA=129.640992950549, DEC=-28.72463006600081)
695. Checking source_id 5649998554125258368 (RA=138.05301863125402, DEC=-25.917628165480735)
696. Checking source_id 5653063069125830016 (RA=133.83156827756443, DEC=-23.87057312949651)

No data found for target "133.83156827756443 -23.87057312949651".

697. Checking source_id 5655050092795276800 (RA=136.7599966689761, DEC=-22.149052356271294)

No data found for target "136.7599966689761 -22.149052356271294".

698. Checking source_id 5661077924778519552 (RA=143.61785482348142, DEC=-26.72420885027511)
699. Checking source_id 5695264936746881536 (RA=126.77920858602496, DEC=-25.449225363796145)
700. Checking source_id 5700706729031126656 (RA=123.17043503163158, DEC=-21.55502398567159)

No data found for target "123.17043503163158 -21.55502398567159".

701. Checking source_id 5798502241016325120 (RA=225.5285537730114, DEC=-71.3014454095702)

No data found for target "225.5285537730114 -71.3014454095702".

702. Checking source_id 5808918155180366336 (RA=245.74844307047053, DEC=-69.09925953111602)

No data found for target "245.74844307047053 -69.09925953111602".

703. Checking source_id 5815970800722940800 (RA=251.9835074590181, DEC=-65.1536701406655)

No data found for target "251.9835074590181 -65.1536701406655".

704. Checking source_id 5819260642586368896 (RA=243.27172696880103, DEC=-70.15478761691558)

No data found for target "243.27172696880103 -70.15478761691558".

705. Checking source_id 5823352234607843968 (RA=232.7190589672623, DEC=-68.02160045447148)
706. Checking source_id 5840719364353028096 (RA=203.54159732659855, DEC=-71.36573625307176)

No data found for target "203.54159732659855 -71.36573625307176".

707. Checking source_id 5861048509766415616 (RA=189.57987020199144, DEC=-65.2456804598289)
708. Checking source_id 5900432500841313920 (RA=227.73324902272088, DEC=-51.69293779799564)

No data found for target "227.73324902272088 -51.69293779799564".

709. Checking source_id 5918660719983560192 (RA=266.6334444727895, DEC=-57.32506180218072)

No data found for target "266.6334444727895 -57.32506180218072".

710. Checking source_id 5925209514333720832 (RA=262.56573118520566, DEC=-51.6404321272004)

No data found for target "262.56573118520566 -51.6404321272004".

711. Checking source_id 5930139823230549120 (RA=249.9034373299412, DEC=-55.410609508601574)
712. Checking source_id 5931193640795532288 (RA=248.90361401821815, DEC=-52.03316495042088)
713. Checking source_id 5934097210481810432 (RA=248.3305162924753, DEC=-52.133851689110905)

No data found for target "248.3305162924753 -52.133851689110905".

714. Checking source_id 5942630107855861888 (RA=249.85706385766625, DEC=-46.88472519104563)
715. Checking source_id 5942777301034031104 (RA=250.19082185115985, DEC=-46.0015821042613)

No data found for target "250.19082185115985 -46.0015821042613".

716. Checking source_id 5943550124208359552 (RA=250.36544421749787, DEC=-43.98861786008088)

No data found for target "250.36544421749787 -43.98861786008088".

717. Checking source_id 5951535219996858624 (RA=263.08991610394963, DEC=-47.61694873889592)
718. Checking source_id 5983356259047553792 (RA=241.289897795576, DEC=-49.79967353527323)
719. Checking source_id 6012127622177717760 (RA=238.0267491026858, DEC=-33.988375449427416)
720. Checking source_id 6013642341180098432 (RA=233.06765151878705, DEC=-35.351264008293)
721. Checking source_id 6018209128388194688 (RA=246.71366499706508, DEC=-38.210202611793854)
722. Checking source_id 6025146733201615616 (RA=246.0683856455975, DEC=-32.20398349011275)
723. Checking source_id 6039144001564707072 (RA=243.5893264382953, DEC=-28.511686254176517)

No data found for target "243.5893264382953 -28.511686254176517".

724. Checking source_id 6056881391901174528 (RA=193.80080693446232, DEC=-59.4731389365543)

No data found for target "193.80080693446232 -59.4731389365543".

725. Checking source_id 6065173805485251072 (RA=207.84330351703483, DEC=-53.54792876649116)

No data found for target "207.84330351703483 -53.54792876649116".

726. Checking source_id 6066971747504719232 (RA=200.51762131763667, DEC=-55.01702752746204)
727. Checking source_id 6069775296000876416 (RA=202.60339969669704, DEC=-52.04614105231651)

No data found for target "202.60339969669704 -52.04614105231651".

728. Checking source_id 6073573215330461952 (RA=191.47157086795116, DEC=-55.114536629695976)

No data found for target "191.47157086795116 -55.114536629695976".

729. Checking source_id 6096529059601571200 (RA=214.19550544539564, DEC=-44.888706723102096)

No data found for target "214.19550544539564 -44.888706723102096".

730. Checking source_id 6109610086872510592 (RA=210.9624810075537, DEC=-42.699347027825176)

No data found for target "210.9624810075537 -42.699347027825176".

731. Checking source_id 6109949904687424640 (RA=212.99539892266264, DEC=-41.539721990460095)

No data found for target "212.99539892266264 -41.539721990460095".

732. Checking source_id 6116110468338455680 (RA=214.35558247321825, DEC=-40.304202316175186)

No data found for target "214.35558247321825 -40.304202316175186".

733. Checking source_id 6143175943486753152 (RA=182.48992008073932, DEC=-46.19264116008711)

No data found for target "182.48992008073932 -46.19264116008711".

734. Checking source_id 6725832095922016256 (RA=273.3347119890693, DEC=-39.84395218207264)
735. Checking source_id 6734485286788609664 (RA=277.3507091117809, DEC=-34.96362316023356)
736. Checking source_id 6759481141756109056 (RA=290.376709235217, DEC=-29.2629248637208)

                       ID  Sector  Exposure_Time   FFI   SPOC
0         769456276704128     4.0    1425.599419  True  False
1         769456276704128    31.0     475.199790  True  False
2       16302463200535040    31.0     475.199790  True   True
3       16302463200535040    42.0     475.199778  True   True
4       16302463200535040    43.0     475.199790  True   True
...                   ...     ...            ...   ...    ...
4263  6734485286788609664    93.0     158.399924  True   True
4264  6734485286788609664    92.0     158.399926  True   True
4265  6759481141756109056    13.0    1425.599392  True   True
4266  6759481141756109056    27.0     475.199782  True   True
4267  6759481141756109056    92.0     158.399926  True   True

[4268 rows x 5 columns]

Saved in tess_id_sector_exptime_G16d20_all_filtered.csv

## Code that verifies SPOC availbility as sanity check

In [16]:
import pandas as pd
import lightkurve as lk

# load original Gaia data and output spreadsheet
table = pd.read_csv("TESS_M=0.4_RP=15.csv")
out = pd.read_csv("tess_id_sector_exptime_G16d20_all_filtered.csv")

# -----------------------------
# manually choose row by index:
i = 2  # <-- change this index to inspect different stars
# -----------------------------

# get spreadsheet row
row = out.iloc[i]

# extract its Gaia ID
gaia_id = row["ID"]
print(f"\nID {gaia_id} (from spreadsheet SPOC={row['SPOC']})")

# getting RA/DEC from original .csv
orig = table[table["source_id"] == gaia_id].iloc[0]
ra, dec = orig["ra"], orig["dec"]
print(f"RA={ra}, DEC={dec}")

# query Lightkurve for SPOC
search = lk.search_targetpixelfile(f"{ra} {dec}", mission="TESS", author="SPOC")
print(search)

if len(search) > 0:
    tpf = search.download()
    print("\nDownloaded:")
    print(tpf)
else:
    print("\nNo SPOC TPF available for this target.")

ID 16302463200535040 (from spreadsheet SPOC=True)
RA=50.8422709188759, DEC=11.686387390947743
SearchResult containing 5 data products.

 #     mission     year author exptime target_name distance
                                  s                 arcsec
--- -------------- ---- ------ ------- ----------- --------
  0 TESS Sector 31 2020   SPOC      20   381133463      0.0
  1 TESS Sector 31 2020   SPOC     120   381133463      0.0
  2 TESS Sector 42 2021   SPOC     120   381133463      0.0
  3 TESS Sector 43 2021   SPOC     120   381133463      0.0
  4 TESS Sector 44 2021   SPOC     120   381133463      0.0

Downloaded:
TessTargetPixelFile(TICID: 381133463)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/lightkurve/search.py:420: LightkurveWarning: Warning: 5 files available to download. Only the first file has been downloaded. Please use `download_all()` or specify additional criteria (e.g. quarter, campaign, or sector) to limit your search.
  warnings.warn(

In [17]:
import lightkurve as lk

search = lk.search_targetpixelfile("Gaia Dr3 16302463200535040", mission="TESS")
search
tpf = search.download()
tpf.plot();

HTTPError: 500 Server Error: Internal Server Error for url: https://mast.stsci.edu/api/v0/invoke?request=%7B%22service%22%3A%20%22Mast.Name.Lookup%22%2C%20%22params%22%3A%20%7B%22input%22%3A%20%22Gaia%20Dr3%2016302463200535040%22%2C%20%22format%22%3A%20%22json%22%7D%7D

In [15]:
lk.search_targetpixelfile("Gaia DR3 769456276704128", mission="TESS", author="SPOC")

HTTPError: 500 Server Error: Internal Server Error for url: https://mast.stsci.edu/api/v0/invoke?request=%7B%22service%22%3A%20%22Mast.Name.Lookup%22%2C%20%22params%22%3A%20%7B%22input%22%3A%20%22Gaia%20DR3%20769456276704128%22%2C%20%22format%22%3A%20%22json%22%7D%7D

In [20]:
import pandas as pd
import lightkurve as lk
import time

In [21]:
# load data from .csv
table = pd.read_csv("TESS_M=0.4_RP=15.csv")

# convert parallax from mas to pc
table['distance_pc'] = 1000 / table['parallax']  

# filtered to have limit of G mag <16 and d<20
filtered = table[
    (table['phot_g_mean_mag'] <= 16) &
    (table['distance_pc'] <= 20)
]

# tells me total targets before and after filtering
print("Total sources before filtering:", len(table))
print("Sources after filtering:", len(filtered))
#print(filtered[['source_id','phot_g_mean_mag','distance_pc']].head())

#subset = filtered.head(5)
subset = filtered
rows = []

Total sources before filtering: 140813
Sources after filtering: 736

In [22]:
# loops .csv
for i, (id, ra, dec) in enumerate(zip(subset['source_id'], subset['ra'], subset['dec']), start=1):
    print(f"{i}. Checking source_id {id} (RA={ra}, DEC={dec})")

    try:
        coord = f"{ra} {dec}"

        # Looks specifically for FFI (TESSCut)
        search_ffi = lk.search_tesscut(coord)
        ffi_avail = len(search_ffi) > 0

        # Looks specifically for SPOC (short cadence)
        spoc = lk.search_targetpixelfile(
            f"Gaia DR3 {id}",
            mission="TESS",
            author="SPOC"
        )
        spoc_avail = len(spoc) > 0

        # If it doesn't have either of them, it will still record
        if not ffi_avail and not spoc_avail:
            rows.append({
                "ID": id,
                "DataType": None,
                "Sector": None,
                "Exposure_Time": None,
                "FFI_Avail": False,
                "SPOC_Avail": False
            })
            continue

        # Adds the rows for FFI
        if ffi_avail:
            for values in search_ffi:
                tab = values.table

                sector = None
                if "sequence_number" in tab.colnames:
                    sector = tab["sequence_number"][0]
                elif "sector" in tab.colnames:
                    sector = tab["sector"][0]

                exptime = tab["exptime"][0] if "exptime" in tab.colnames else None

                rows.append({
                    "ID": id,
                    "DataType": "FFI",
                    "Sector": sector,
                    "Exposure_Time": exptime,
                    "FFI_Avail": True,
                    "SPOC_Avail": spoc_avail
                })

        # Adds the rows for SPOC
        if spoc_avail:
            for values in spoc:
                sector = values.sector if hasattr(values, "sector") else None
                exptime = values.exptime if hasattr(values, "exptime") else None

                # Fallback to table columns if needed
                if sector is None or exptime is None:
                    tab = values.table
                    if sector is None and "sector" in tab.colnames:
                        sector = tab["sector"][0]
                    if exptime is None and "exptime" in tab.colnames:
                        exptime = tab["exptime"][0]

                rows.append({
                    "ID": id,
                    "DataType": "SPOC",
                    "Sector": sector,
                    "Exposure_Time": exptime,
                    "FFI_Avail": ffi_avail,
                    "SPOC_Avail": True
                })

    except Exception as e:
        print(f"Error for {id}: {e}")
        rows.append({
            "ID": id,
            "DataType": None,
            "Sector": None,
            "Exposure_Time": None,
            "FFI_Avail": False,
            "SPOC_Avail": False
        })
 #if i % 25 == 0:
  #      pd.DataFrame(rows).to_csv(
   #         "tess_id_sector_exptime_G16d20_all_filtered_UPDATED_PARTIAL.csv",
    #        index=False
     #   )
      #  print(f"Checkpoint saved at object {i}")
 
out = pd.DataFrame(rows)
display(out)

# save spreadsheet .csv
out.to_csv("tess_id_sector_exptime_G16d20_all_filtered_UPDATED.csv", index=False)
print("Saved in tess_id_sector_exptime_G16d20_all_filtered_UPDATED.csv")

1. Checking source_id 769456276704128 (RA=47.51489911594037, DEC=2.572769511017299)
2. Checking source_id 16302463200535040 (RA=50.8422709188759, DEC=11.686387390947743)
3. Checking source_id 18986817760556416 (RA=39.82435828918509, DEC=7.470816071340625)
4. Checking source_id 35398295820372864 (RA=43.358915254728714, DEC=17.407883277761023)

No data found for target "Gaia DR3 35398295820372864".

5. Checking source_id 57739208163471744 (RA=51.68738385482385, DEC=19.243802626944703)
6. Checking source_id 68553931516671488 (RA=54.87437762176911, DEC=24.96824115907829)
7. Checking source_id 72117556076986368 (RA=33.98650746472387, DEC=10.254962202598763)
8. Checking source_id 72354810070468224 (RA=33.192827917024836, DEC=10.547975698321418)
9. Checking source_id 89593331327905536 (RA=39.183682325426595, DEC=22.67227965316612)
10. Checking source_id 91196316201965184 (RA=29.56508818927173, DEC=18.12063665648874)
11. Checking source_id 97334889619799168 (RA=27.85070481391559, DEC=21.39275062405243)
12. Checking source_id 97993497084921984 (RA=27.018206566174985, DEC=21.205767467992107)
13. Checking source_id 117709729140217216 (RA=52.20764798129931, DEC=26.48616945277209)
14. Checking source_id 308828253324985984 (RA=19.459213398032063, DEC=28.669329862628036)
15. Checking source_id 327944328126649856 (RA=34.29473704167926, DEC=35.44121898612927)
16. Checking source_id 348020242217448576 (RA=24.208998277705287, DEC=41.39055046681678)

No data found for target "Gaia DR3 348020242217448576".

17. Checking source_id 373838214051410816 (RA=14.504225894844094, DEC=39.31987471822514)
18. Checking source_id 569821974111727744 (RA=63.51645882603903, DEC=82.25759093058488)
19. Checking source_id 598180646733241216 (RA=130.7186251598315, DEC=9.55037430644196)
20. Checking source_id 605079910398496640 (RA=134.08122584963937, DEC=12.662731415781227)
21. Checking source_id 615779464207025152 (RA=150.6775798896445, DEC=14.985896812309678)
22. Checking source_id 617982090939470464 (RA=144.87402457514528, DEC=14.646793438572836)
23. Checking source_id 619440661833351040 (RA=147.20907756971008, DEC=15.646815201966763)
24. Checking source_id 622339455521105280 (RA=153.97610368902318, DEC=17.490880663782907)
25. Checking source_id 628080246633611520 (RA=148.4782397121578, DEC=20.948079178895128)
26. Checking source_id 628865130046268672 (RA=153.72046302348045, DEC=21.395135245402663)
27. Checking source_id 641821259671808896 (RA=149.11007978867167, DEC=22.64914689456202)
28. Checking source_id 646255246469567232 (RA=143.20029276934693, DEC=26.994404086268727)

No data found for target "Gaia DR3 646255246469567232".

29. Checking source_id 646818024623804416 (RA=145.97884036380384, DEC=26.96855261959639)
30. Checking source_id 656328319169788032 (RA=125.48480046053642, DEC=17.816229744725995)
31. Checking source_id 666988221840703232 (RA=118.10053540514112, DEC=16.20259810649539)
32. Checking source_id 696501553469122304 (RA=144.84494415736484, DEC=29.72384628471681)
33. Checking source_id 700732474214292096 (RA=140.62274853344667, DEC=31.462808505180774)
34. Checking source_id 704966762213039488 (RA=133.16783218849463, DEC=28.315252421854034)

No data found for target "Gaia DR3 704966762213039488".

35. Checking source_id 706300980915871616 (RA=129.8558619958561, DEC=29.888835566188664)
36. Checking source_id 709563717249089792 (RA=130.06766840125894, DEC=31.45242630658037)
37. Checking source_id 741275934694972800 (RA=155.0009571782997, DEC=28.95264696593352)
38. Checking source_id 753585104807022080 (RA=152.17654982392168, DEC=35.5475756414613)
39. Checking source_id 758200712885953280 (RA=167.96464803741873, DEC=33.53697074560677)
40. Checking source_id 763973668623022464 (RA=170.67963052649262, DEC=37.93015926691593)
41. Checking source_id 764072689093638528 (RA=171.01885964390104, DEC=38.13629424820036)
42. Checking source_id 765038614353808768 (RA=167.20415886992, DEC=39.9194772969731)
43. Checking source_id 772430527947893632 (RA=175.43249920718978, DEC=42.75157375642011)
44. Checking source_id 788357434914248448 (RA=169.87953937654436, DEC=46.69261027622741)
45. Checking source_id 795434510226597760 (RA=148.93144985906537, DEC=35.36021293511174)
46. Checking source_id 806039471675754112 (RA=155.96718909727664, DEC=43.892552567095734)
47. Checking source_id 835748825612078848 (RA=161.3117904571487, DEC=49.690721671495034)
48. Checking source_id 844922257281519744 (RA=174.0685159675205, DEC=56.39999642341029)
49. Checking source_id 847330325186182912 (RA=156.51100654305094, DEC=50.45359969774126)
50. Checking source_id 868209703104242048 (RA=114.62216862501052, DEC=24.0019731597431)
51. Checking source_id 898506166187633280 (RA=112.98739022537632, DEC=36.22866483400494)
52. Checking source_id 907066684548911872 (RA=121.70088015375909, DEC=36.75903456662503)
53. Checking source_id 912087093295958144 (RA=132.2838763210011, DEC=39.605842131988005)
54. Checking source_id 921952117778154240 (RA=121.72910641215296, DEC=42.29129375007699)
55. Checking source_id 978338677527779200 (RA=106.90707091399624, DEC=48.68573489188429)
56. Checking source_id 982389862479141376 (RA=116.80766643936455, DEC=50.344381181505526)
57. Checking source_id 985610542491481984 (RA=113.84028667733696, DEC=54.849773078642905)
58. Checking source_id 1016640817918422272 (RA=135.93078072117314, DEC=52.04697454057216)
59. Checking source_id 1017783146073299328 (RA=134.8975225560541, DEC=53.72986152233806)
60. Checking source_id 1038195201485531776 (RA=139.44184149237842, DEC=58.417419402224134)
61. Checking source_id 1041395708035677312 (RA=132.1273646145831, DEC=61.14977484752529)
62. Checking source_id 1056860923195191936 (RA=179.45874784377168, DEC=66.56193013560468)
63. Checking source_id 1070519572033023232 (RA=150.52360646224852, DEC=69.75710578236257)
64. Checking source_id 1071851527289746176 (RA=149.9387380823067, DEC=72.20037314188153)
65. Checking source_id 1073206263054159104 (RA=158.84150877915906, DEC=69.446793871661)
66. Checking source_id 1083242222939300480 (RA=122.07423466781546, DEC=58.519009709876286)
67. Checking source_id 1117132130541140736 (RA=135.7225460569734, DEC=68.06446038566975)
68. Checking source_id 1123681096674583552 (RA=134.9987609031543, DEC=72.95993278581588)
69. Checking source_id 1125337098625077504 (RA=135.05447462137312, DEC=75.37236190179152)
70. Checking source_id 1134155113160270720 (RA=150.2915837503259, DEC=81.15484257034134)
71. Checking source_id 1138963758544545280 (RA=123.42723031947163, DEC=79.30137045178125)
72. Checking source_id 1139642706975159552 (RA=105.87490601885828, DEC=76.77275818273984)
73. Checking source_id 1149245394855341440 (RA=128.05827749211943, DEC=84.40965990897092)
74. Checking source_id 1149727977380998784 (RA=109.99020696216758, DEC=84.07690200527787)
75. Checking source_id 1155910118945913728 (RA=229.9411845112153, DEC=4.660000235225668)
76. Checking source_id 1159745146784043264 (RA=225.33415504486476, DEC=5.546794272660181)
77. Checking source_id 1165479168642900992 (RA=232.625560005462, DEC=9.434551385099413)
78. Checking source_id 1175938925836488448 (RA=216.2357318474915, DEC=8.888339518893313)
79. Checking source_id 1188693088919917952 (RA=224.109214809204, DEC=17.91876929997926)
80. Checking source_id 1209432042883668480 (RA=233.71072951618376, DEC=18.00196306214209)
81. Checking source_id 1212774313804554752 (RA=227.52009755174592, DEC=19.355624418458618)
82. Checking source_id 1214076070761755008 (RA=229.63109374468223, DEC=20.60824922657203)
83. Checking source_id 1227705135863076864 (RA=217.0156415738216, DEC=13.934833566564166)
84. Checking source_id 1235125877277843840 (RA=218.04584697379087, DEC=16.013385429054974)
85. Checking source_id 1256071505067560704 (RA=216.39418554867095, DEC=25.668004465226957)
86. Checking source_id 1276940648080594048 (RA=231.43145117487225, DEC=31.202217035964036)
87. Checking source_id 1282073374518833152 (RA=223.79801910728224, DEC=30.11225414386347)
88. Checking source_id 1282632682337912832 (RA=221.0710869095232, DEC=30.0357734179162)
89. Checking source_id 1320545217653492864 (RA=240.4298070154365, DEC=30.181367389399146)
90. Checking source_id 1320795047312113152 (RA=237.83964101743064, DEC=29.516446364274)
91. Checking source_id 1326893351115617024 (RA=251.6292959257543, DEC=34.580290245898446)
92. Checking source_id 1327654969076730880 (RA=249.25489571253425, DEC=35.593526440532905)
93. Checking source_id 1332966881549315456 (RA=247.8274448005916, DEC=40.86572384148289)
94. Checking source_id 1341113541156480768 (RA=257.89598966788463, DEC=38.44254560681901)
95. Checking source_id 1350714133093019904 (RA=269.4622611288724, DEC=46.59121608783237)
96. Checking source_id 1355264565043431040 (RA=257.3834721191679, DEC=43.680105808986085)
97. Checking source_id 1372215976327300480 (RA=239.57754339419824, DEC=35.408158262718665)
98. Checking source_id 1379500928055726848 (RA=241.20868366880867, DEC=39.16016523606519)
99. Checking source_id 1388684770725399296 (RA=229.1684830144717, DEC=39.17983717431188)
100. Checking source_id 1409902905599851392 (RA=247.8661959969435, DEC=47.17314755249796)
101. Checking source_id 1412645602995521920 (RA=255.85040248888004, DEC=51.40906417008386)
102. Checking source_id 1416123117756120960 (RA=259.41085537136235, DEC=52.40531634143529)
103. Checking source_id 1431176943768690816 (RA=248.57558060807455, DEC=57.16757381763237)
104. Checking source_id 1443068608699851008 (RA=202.9594075396803, DEC=23.389206653452536)
105. Checking source_id 1451197916638959872 (RA=209.71769182511895, DEC=27.87062339863821)
106. Checking source_id 1461049369026235904 (RA=197.8380339246302, DEC=28.542881140686458)
107. Checking source_id 1461125613285603840 (RA=197.3939952563072, DEC=28.984194794735036)
108. Checking source_id 1461507384337635840 (RA=199.13310731831825, DEC=27.87596984084402)
109. Checking source_id 1466009540856759680 (RA=196.7105478174373, DEC=30.84621621605227)
110. Checking source_id 1477762319428998400 (RA=214.94519097573385, DEC=31.617589844728105)
111. Checking source_id 1483977656798789120 (RA=213.98497602510355, DEC=36.27839269007434)
112. Checking source_id 1489294551432850560 (RA=223.06692178226328, DEC=41.32158904033235)
113. Checking source_id 1495487688115551744 (RA=207.7132354836552, DEC=36.73846792755987)
114. Checking source_id 1505209054532280960 (RA=214.34237220584717, DEC=45.42936021377157)
115. Checking source_id 1518564478676515712 (RA=189.11736017524785, DEC=35.19971562564376)
116. Checking source_id 1534239391319888384 (RA=190.70457462086816, DEC=41.8966090688773)
117. Checking source_id 1573896198753650944 (RA=181.4021839662666, DEC=56.394863843666194)
118. Checking source_id 1587576253706543232 (RA=228.15665054327465, DEC=45.73119308728785)
119. Checking source_id 1595170236922937728 (RA=233.51466659726952, DEC=51.368562240881666)
120. Checking source_id 1603272950424941440 (RA=233.8585360449291, DEC=60.08470833271646)

No data found for target "Gaia DR3 1603272950424941440".

121. Checking source_id 1603611493015735296 (RA=218.05659204654648, DEC=49.651165748848456)
122. Checking source_id 1604901876901703168 (RA=215.76332804586107, DEC=51.77600462861712)
123. Checking source_id 1616853430856547968 (RA=221.1035124404749, DEC=58.287786919281984)
124. Checking source_id 1618330448634358400 (RA=216.78665388902056, DEC=60.941040648347105)
125. Checking source_id 1631591147276525696 (RA=253.2075718369321, DEC=63.07812356967455)
126. Checking source_id 1638180413086979840 (RA=269.3142709072523, DEC=70.70178301936559)
127. Checking source_id 1648484868558988544 (RA=250.0827910688673, DEC=67.60294000951913)
128. Checking source_id 1650819612781643392 (RA=262.0450109199984, DEC=71.14096957434231)
129. Checking source_id 1655482224982135040 (RA=255.4369477446704, DEC=74.19781368444308)
130. Checking source_id 1656076893269778432 (RA=265.6823444683212, DEC=75.62282031158797)
131. Checking source_id 1669449084967071872 (RA=220.58662378500725, DEC=66.05561864866871)
132. Checking source_id 1678489647527832320 (RA=198.5949485165658, DEC=66.37603764196513)
133. Checking source_id 1683228851880827136 (RA=185.44336261603965, DEC=68.2687045566608)
134. Checking source_id 1683609076745527680 (RA=181.3678591223992, DEC=69.53936644393914)
135. Checking source_id 1683677624423753472 (RA=181.73532846482885, DEC=70.13042280787634)
136. Checking source_id 1701585301586363904 (RA=219.30529832556255, DEC=75.61151710152384)
137. Checking source_id 1701602958196086528 (RA=217.80244124264595, DEC=75.44491958012206)
138. Checking source_id 1710948192852697600 (RA=262.8122775792793, DEC=82.09105560054718)
139. Checking source_id 1714831771000745344 (RA=208.41629245213292, DEC=77.61886343809084)
140. Checking source_id 1735245338242513536 (RA=310.8514381606976, DEC=4.764685971871537)
141. Checking source_id 1768825106253209984 (RA=327.9522183313725, DEC=13.603838612745625)
142. Checking source_id 1773485214494929536 (RA=326.0387863765124, DEC=17.059722272765484)
143. Checking source_id 1773497412196823680 (RA=326.0343872670299, DEC=17.077038166155283)
144. Checking source_id 1776179945695834368 (RA=331.59592583103495, DEC=17.372810486070932)
145. Checking source_id 1890425839540910848 (RA=341.97779535087403, DEC=31.871783828604855)
146. Checking source_id 1893189736896880640 (RA=330.306566078579, DEC=28.30710892040449)
147. Checking source_id 2110165780975185792 (RA=278.6530518091756, DEC=40.12307795291824)
148. Checking source_id 2118429538570209920 (RA=278.86660840698516, DEC=45.762979999016885)
149. Checking source_id 2256631484392164736 (RA=277.8407516553966, DEC=64.9039850767494)
150. Checking source_id 2257597439718033536 (RA=274.74325647947336, DEC=66.19061665488063)
151. Checking source_id 2294281163411732736 (RA=278.9690777068371, DEC=80.09526285745366)
152. Checking source_id 2302668860880387072 (RA=289.10161012405797, DEC=84.22869527150492)
153. Checking source_id 2312376723918929920 (RA=356.6576476677058, DEC=-34.16710787919001)
154. Checking source_id 2325083848520121856 (RA=352.65810345342345, DEC=-33.30768786716094)
155. Checking source_id 2368212771939556992 (RA=3.9914280244393505, DEC=-16.61597822404432)
156. Checking source_id 2393563872239260928 (RA=351.86040963011595, DEC=-17.69494218902131)
157. Checking source_id 2395413147718069504 (RA=354.53268726381896, DEC=-16.23651363027235)
158. Checking source_id 2400808245117576704 (RA=339.69068815030255, DEC=-20.614689446269768)

No data found for target "Gaia DR3 2400808245117576704".

159. Checking source_id 2407340615496379008 (RA=352.10236185712836, DEC=-15.924966875091195)
160. Checking source_id 2407573643242037888 (RA=351.0712300150862, DEC=-15.373269236906095)
161. Checking source_id 2414623952318068224 (RA=1.2404631704419242, DEC=-17.160303653461234)
162. Checking source_id 2420649585275393920 (RA=356.83925393911727, DEC=-12.343968535630694)
163. Checking source_id 2421080250237097344 (RA=359.33671447287855, DEC=-12.980168707826213)
164. Checking source_id 2421080250237474176 (RA=359.3316119129798, DEC=-12.977870560152498)
165. Checking source_id 2450599697900838912 (RA=23.49187379987124, DEC=-17.640773463135556)
166. Checking source_id 2451701339832959232 (RA=22.623854394641025, DEC=-16.40544797329293)
167. Checking source_id 2452167910719793664 (RA=22.16461895808497, DEC=-14.96810617489612)
168. Checking source_id 2453195851012123904 (RA=26.781623953195012, DEC=-14.411598506271671)
169. Checking source_id 2457862762476854656 (RA=20.825063748419577, DEC=-12.938209952737276)
170. Checking source_id 2461728194387221504 (RA=30.434023239076055, DEC=-10.290317824118802)
171. Checking source_id 2467242352575094784 (RA=25.994623558557567, DEC=-6.913531290688611)
172. Checking source_id 2467732906559754496 (RA=27.769525129441792, DEC=-6.119239184112927)
173. Checking source_id 2468929243931522304 (RA=17.57395028608209, DEC=-11.855370704147928)

No data found for target "Gaia DR3 2468929243931522304".

174. Checking source_id 2486388560866377728 (RA=33.1190109988742, DEC=-8.071574920874733)
175. Checking source_id 2492866780297999232 (RA=33.554613532263986, DEC=-3.96280045849318)
176. Checking source_id 2497858563088120448 (RA=44.01738337380463, DEC=-0.608877262589059)
177. Checking source_id 2507016253701863040 (RA=33.23006351010599, DEC=0.0048112291822607)
178. Checking source_id 2514052131687080192 (RA=35.19339905103572, DEC=2.9757995116747007)
179. Checking source_id 2526788363283721984 (RA=8.93379610467678, DEC=-5.687454587970094)
180. Checking source_id 2528227035593363840 (RA=8.221728419110557, DEC=-4.569270815894982)
181. Checking source_id 2537831170877143552 (RA=17.050154984643736, DEC=0.4641340321772402)
182. Checking source_id 2614071100988460544 (RA=331.39766600457193, DEC=-11.075490632741356)

No data found for target "Gaia DR3 2614071100988460544".

183. Checking source_id 2616132101175335936 (RA=334.3256811695789, DEC=-8.806486660337637)
184. Checking source_id 2618333804489940992 (RA=329.3036181978969, DEC=-9.05802459659516)
185. Checking source_id 2620145937091715072 (RA=331.54090391057207, DEC=-7.394198350555103)
186. Checking source_id 2631857350835259392 (RA=348.9785213795388, DEC=-6.463096715840339)
187. Checking source_id 2668249051115631232 (RA=326.2524726236367, DEC=-5.788973523692696)
188. Checking source_id 2669873515120908544 (RA=326.82387294144644, DEC=-4.744613685896646)
189. Checking source_id 2670661109044300160 (RA=323.4543418919189, DEC=-6.8551113020513075)
190. Checking source_id 2673992663636347520 (RA=327.8635523883638, DEC=-1.4538921085791252)
191. Checking source_id 2681122098893985408 (RA=326.6718481188171, DEC=-0.1755173375144743)
192. Checking source_id 2683209044978079616 (RA=331.6251935434858, DEC=2.375809039939923)
193. Checking source_id 2683714304930755712 (RA=331.69527845431674, DEC=3.4163173765574197)
194. Checking source_id 2688566793341935360 (RA=323.4546452148779, DEC=1.7791345250832382)
195. Checking source_id 2705611005983192320 (RA=338.6921084252097, DEC=4.044371189279514)
196. Checking source_id 2708839657453920256 (RA=335.0565229770535, DEC=6.72679864112854)
197. Checking source_id 2710189960812052736 (RA=336.76251116872623, DEC=6.825575040979833)
198. Checking source_id 2719512513745949184 (RA=342.0961253423981, DEC=12.536167811623086)
199. Checking source_id 2775987485397299072 (RA=11.08183889277884, DEC=12.616598050741125)
200. Checking source_id 2799992744809482112 (RA=6.985243946351337, DEC=22.324902794590333)
201. Checking source_id 2800823799506215168 (RA=6.33469184849611, DEC=22.884358347500047)
202. Checking source_id 2801216123294143360 (RA=5.8655364124677485, DEC=24.30736066735532)
203. Checking source_id 2819781274051096192 (RA=354.4016087764225, DEC=16.367299189308994)
204. Checking source_id 2824770686019004032 (RA=352.9716753030632, DEC=19.937313746866927)
205. Checking source_id 2830318679957189632 (RA=342.22734755350785, DEC=18.332476624663535)
206. Checking source_id 2836510961942677376 (RA=340.84852132214786, DEC=22.138349954479125)
207. Checking source_id 2856874535763703680 (RA=4.725287520277892, DEC=27.813355639663538)
208. Checking source_id 2859027409595355776 (RA=6.148344264210615, DEC=30.041581512034053)
209. Checking source_id 2863419584886542080 (RA=5.128239996638605, DEC=33.08128045387165)
210. Checking source_id 2864382138598091648 (RA=353.76630482328295, DEC=25.250191671633328)
211. Checking source_id 2866851710433326208 (RA=356.5590246187754, DEC=28.43471215134376)
212. Checking source_id 2868199402451064064 (RA=355.7180385472229, DEC=30.82137349573688)
213. Checking source_id 2872988394066393344 (RA=355.0954866644879, DEC=34.55437676255151)
214. Checking source_id 2881313793031884544 (RA=358.71365830063576, DEC=38.52633962632873)
215. Checking source_id 2886233695250041216 (RA=91.21742524933885, DEC=-34.558412822381825)
216. Checking source_id 2891695137006940544 (RA=94.44578372665914, DEC=-34.01941716022002)
217. Checking source_id 2905516483501493120 (RA=82.7698222187872, DEC=-30.19782913482597)
218. Checking source_id 2907884728469088384 (RA=86.45936920758024, DEC=-27.16289618149821)
219. Checking source_id 2911981886751531648 (RA=91.9313221336463, DEC=-25.745763611837013)
220. Checking source_id 2954555801611979648 (RA=79.65245423379399, DEC=-28.69991906819153)
221. Checking source_id 3013672487388307456 (RA=83.84028163560048, DEC=-9.519503846133947)
222. Checking source_id 3015684005638599168 (RA=84.00082080161667, DEC=-7.64749055072158)
223. Checking source_id 3073508528645520000 (RA=128.60888691505394, DEC=-1.1461842748957634)
224. Checking source_id 3080039799513337216 (RA=129.37618554147426, DEC=3.56196898899723)
225. Checking source_id 3171631420210205056 (RA=68.81802669744249, DEC=-16.114491965535613)
226. Checking source_id 3181367767472670080 (RA=73.01496562474308, DEC=-10.973690528268827)
227. Checking source_id 3183748278864953856 (RA=76.55698495755243, DEC=-8.119530513718672)
228. Checking source_id 3197487123332369536 (RA=61.52874997880343, DEC=-5.579705448233032)
229. Checking source_id 3198812859478372480 (RA=65.86135866378902, DEC=-7.397152593091982)
230. Checking source_id 3200303384927512960 (RA=70.09847133151465, DEC=-5.501688546295259)
231. Checking source_id 3230306548988683392 (RA=68.68850665695317, DEC=-0.4472776491451271)
232. Checking source_id 3266937637860051840 (RA=47.81499313101462, DEC=1.108502371089936)
233. Checking source_id 3278137572540701056 (RA=56.08602675057091, DEC=7.698683077306292)
234. Checking source_id 3288082758293022848 (RA=73.02457095863625, DEC=6.47519220606572)
235. Checking source_id 3459586677937737088 (RA=182.3476049914616, DEC=-38.26276233724284)
236. Checking source_id 3464485826872541440 (RA=175.34234990922278, DEC=-36.40821490897027)
237. Checking source_id 3479221035031532416 (RA=178.2958474507511, DEC=-31.39953502009418)
238. Checking source_id 3489874340631095936 (RA=183.5363721475547, DEC=-23.75432290382595)
239. Checking source_id 3493736924979792768 (RA=178.92674906227322, DEC=-22.4171647007583)
240. Checking source_id 3496355755520065408 (RA=189.8989000476626, DEC=-26.97054952279352)
241. Checking source_id 3499296429434610304 (RA=194.05414981104076, DEC=-22.08421085269118)
242. Checking source_id 3502592975744957824 (RA=192.7215172935436, DEC=-21.35524787955247)
243. Checking source_id 3517619520125627904 (RA=182.07620531885144, DEC=-21.01936118449221)
244. Checking source_id 3517841140438425600 (RA=182.81963496571075, DEC=-19.973535053310865)
245. Checking source_id 3517841209157902720 (RA=182.79799193877028, DEC=-19.96139412325039)
246. Checking source_id 3530383784971799680 (RA=191.00091142330737, DEC=-11.175787631619018)
247. Checking source_id 3531294008802299392 (RA=169.1543575390885, DEC=-27.95891105546361)
248. Checking source_id 3536327366875661056 (RA=167.47217753029176, DEC=-24.24941832570553)
249. Checking source_id 3539057213728669184 (RA=166.27825468370008, DEC=-22.216074598403548)
250. Checking source_id 3546332682170832128 (RA=170.98588570400648, DEC=-18.363746221389203)
251. Checking source_id 3566338949070993536 (RA=169.2751391986689, DEC=-11.37435916898148)
252. Checking source_id 3574445407785255296 (RA=182.18346204777117, DEC=-11.564004075631765)
253. Checking source_id 3582675080520660992 (RA=185.96594679923768, DEC=-8.979976175598768)
254. Checking source_id 3584226658929871232 (RA=184.64361569925163, DEC=-6.423305459754171)
255. Checking source_id 3592769731134725248 (RA=172.6726859278835, DEC=-8.094129760812047)
256. Checking source_id 3602406744394215936 (RA=179.44156853878948, DEC=-1.8183858067070635)
257. Checking source_id 3608334005420675584 (RA=200.4743550952303, DEC=-14.402375689120356)
258. Checking source_id 3610474857638415616 (RA=204.6710209109411, DEC=-11.535869729632498)
259. Checking source_id 3612684120096472192 (RA=209.5658446545277, DEC=-12.049543189658584)
260. Checking source_id 3637468383496879104 (RA=204.72131158745523, DEC=-2.2634740111610667)
261. Checking source_id 3652910371473481344 (RA=216.9820370876051, DEC=-0.3751301143973934)
262. Checking source_id 3652910405833716864 (RA=216.98338440234295, DEC=-0.3717579253833862)
263. Checking source_id 3669916071144145920 (RA=217.0715724608264, DEC=5.31243130716067)
264. Checking source_id 3669916380381791104 (RA=217.08799771619425, DEC=5.3167596985937795)
265. Checking source_id 3677448412989388032 (RA=195.0149340750512, DEC=-5.6297508059701755)

No data found for target "Gaia DR3 3677448412989388032".

266. Checking source_id 3713826030072008192 (RA=207.2025218306175, DEC=4.099847002145388)
267. Checking source_id 3758629475341196672 (RA=164.61574644090516, DEC=-10.775511452309788)
268. Checking source_id 3759774208680370688 (RA=163.89244055921364, DEC=-9.355205624410983)
269. Checking source_id 3762071530853756928 (RA=158.75568416720952, DEC=-9.41153944861764)
270. Checking source_id 3793898411041910144 (RA=175.55398369123793, DEC=-1.3687129840118293)

No data found for target "Gaia DR3 3793898411041910144".

271. Checking source_id 3793898479761174656 (RA=175.55387781734504, DEC=-1.3651467411429208)
272. Checking source_id 3794437034301022720 (RA=177.98105299187364, DEC=-1.5263271044381868)
273. Checking source_id 3795993633527490304 (RA=176.92404164490358, DEC=0.2512338759265444)
274. Checking source_id 3795993633527490560 (RA=176.9183832811517, DEC=0.2551360375501735)
275. Checking source_id 3836344438956110208 (RA=149.96815413261183, DEC=2.7805250971078017)
276. Checking source_id 3838384617141390208 (RA=140.4513282977866, DEC=-2.328676307427825)
277. Checking source_id 3845035696121944576 (RA=139.04266578605825, DEC=1.8853361511850135)
278. Checking source_id 3850237416912716928 (RA=149.7346148256968, DEC=5.966340551968416)
279. Checking source_id 3862117335108574848 (RA=158.13634891696773, DEC=6.5012502773544405)
280. Checking source_id 3920481233377933824 (RA=182.518368136087, DEC=12.73595016486881)
281. Checking source_id 3927886100593557888 (RA=193.71037814037763, DEC=11.985615985802268)
282. Checking source_id 3931880591977203584 (RA=188.82234404657177, DEC=13.30249052683408)
283. Checking source_id 3965764619767224832 (RA=171.2218237122872, DEC=13.38089075564062)
284. Checking source_id 3968118399284369280 (RA=165.83769461159238, DEC=13.632847157123214)
285. Checking source_id 3978179338700027008 (RA=168.80258887774315, DEC=19.45118404016304)
286. Checking source_id 3987041475434695936 (RA=159.03739434658837, DEC=19.39015001792424)
287. Checking source_id 3997576171218205312 (RA=170.4794132895151, DEC=26.830263459667865)
288. Checking source_id 4004586348119642240 (RA=178.23977721633167, DEC=24.479688541188125)
289. Checking source_id 4188996885011268608 (RA=299.3487765276967, DEC=-12.566252961830063)
290. Checking source_id 4229940258487034368 (RA=307.50854656595607, DEC=0.39871746938847)
291. Checking source_id 4349305645979265920 (RA=242.74321092251347, DEC=-6.526530784784987)

No data found for target "242.74321092251347 -6.526530784784987".
No data found for target "Gaia DR3 4349305645979265920".

292. Checking source_id 4353476020565733632 (RA=252.72077443405544, DEC=-4.844117679510572)

No data found for target "252.72077443405544 -4.844117679510572".
No data found for target "Gaia DR3 4353476020565733632".

293. Checking source_id 4365609170043180416 (RA=254.27604768745735, DEC=-4.350649323558728)

No data found for target "254.27604768745735 -4.350649323558728".
No data found for target "Gaia DR3 4365609170043180416".

294. Checking source_id 4366633811793952896 (RA=258.01634026214566, DEC=-3.3925453464829833)

No data found for target "258.01634026214566 -3.3925453464829833".
No data found for target "Gaia DR3 4366633811793952896".

295. Checking source_id 4383790518216171264 (RA=250.02571538084769, DEC=0.7045342401421566)

No data found for target "250.02571538084769 0.7045342401421566".
No data found for target "Gaia DR3 4383790518216171264".

296. Checking source_id 4393265392168829056 (RA=258.8314799887317, DEC=4.960575338342743)

No data found for target "258.8314799887317 4.960575338342743".
No data found for target "Gaia DR3 4393265392168829056".

297. Checking source_id 4405150047715392128 (RA=243.60495984709544, DEC=-2.848575653404131)

No data found for target "243.60495984709544 -2.848575653404131".
No data found for target "Gaia DR3 4405150047715392128".

298. Checking source_id 4410702581435191296 (RA=237.5475233257174, DEC=0.958881993576492)
299. Checking source_id 4412417304175836544 (RA=240.6727825640195, DEC=1.530347271225057)

No data found for target "Gaia DR3 4412417304175836544".

300. Checking source_id 4423007800173036544 (RA=236.8120142223106, DEC=1.82248062760857)
301. Checking source_id 4443110789740420480 (RA=255.25771984966343, DEC=8.206529331440088)

No data found for target "255.25771984966343 8.206529331440088".
No data found for target "Gaia DR3 4443110789740420480".

302. Checking source_id 4446207564241339520 (RA=249.02120996412984, DEC=8.812978058517322)

No data found for target "249.02120996412984 8.812978058517322".
No data found for target "Gaia DR3 4446207564241339520".

303. Checking source_id 4446574040918651904 (RA=248.2212020132817, DEC=9.841238219932931)

No data found for target "248.2212020132817 9.841238219932931".
No data found for target "Gaia DR3 4446574040918651904".

304. Checking source_id 4454532237354157568 (RA=239.45174547990845, DEC=9.01878131907999)
305. Checking source_id 4540481374832743040 (RA=259.4321138774718, DEC=11.668137650695137)

No data found for target "259.4321138774718 11.668137650695137".
No data found for target "Gaia DR3 4540481374832743040".

306. Checking source_id 4540984195244025088 (RA=257.46817080562016, DEC=11.925767768358645)

No data found for target "257.46817080562016 11.925767768358645".
No data found for target "Gaia DR3 4540984195244025088".

307. Checking source_id 4549983418742839808 (RA=263.4709486275802, DEC=16.919716366320987)
308. Checking source_id 4554019214828782848 (RA=262.59454686161763, DEC=19.208516712601973)
309. Checking source_id 4566158991430299520 (RA=252.741579155228, DEC=22.45335201410153)
310. Checking source_id 4567274927017734400 (RA=260.47682518226895, DEC=21.43091558237368)
311. Checking source_id 4568060562432051584 (RA=256.77899349986836, DEC=21.553906093733755)
312. Checking source_id 4574048021719712640 (RA=259.9695666590066, DEC=26.502318754868263)
313. Checking source_id 4594186745414679680 (RA=263.80474400128486, DEC=26.578452534570733)
314. Checking source_id 4609151442264875648 (RA=267.89764258006653, DEC=37.82801852429099)
315. Checking source_id 4620448786799883136 (RA=43.437287895891245, DEC=-79.98664426166238)
316. Checking source_id 4646616923022587136 (RA=41.51227837952512, DEC=-70.40213295868823)
317. Checking source_id 4654435618927743872 (RA=65.05548915027946, DEC=-70.09683448950774)
318. Checking source_id 4665366619931917824 (RA=74.88261512661207, DEC=-61.88437139795797)
319. Checking source_id 4672462936698379520 (RA=50.21568535473568, DEC=-63.86585958449603)
320. Checking source_id 4676145235499604096 (RA=61.51584482379152, DEC=-64.09722087351366)
321. Checking source_id 4677345043203760896 (RA=67.025472974701, DEC=-62.15543452946297)
322. Checking source_id 4689958778035794048 (RA=7.773722280188864, DEC=-72.01767831001747)
323. Checking source_id 4690736923033593728 (RA=18.27130621215673, DEC=-70.84376343995396)
324. Checking source_id 4705628051386514304 (RA=16.02568403467347, DEC=-65.37498961991618)
325. Checking source_id 4706483132131647232 (RA=3.93774642370424, DEC=-67.99395121635692)
326. Checking source_id 4708990018643008896 (RA=14.305598383824345, DEC=-64.25584867932709)
327. Checking source_id 4714117865996976768 (RA=34.366362901437554, DEC=-59.38085727536495)
328. Checking source_id 4719430087707860736 (RA=30.160435097325607, DEC=-55.96826051259185)
329. Checking source_id 4726357491998516480 (RA=39.47063857709459, DEC=-58.75214686390397)
330. Checking source_id 4733113441195646592 (RA=54.73403875235281, DEC=-52.568615867333605)
331. Checking source_id 4757687388639045504 (RA=84.41696430616265, DEC=-61.90996787478893)
332. Checking source_id 4772342676044749952 (RA=81.87712822395483, DEC=-51.48627898796885)
333. Checking source_id 4785886941312921344 (RA=76.30968124678876, DEC=-47.937535542918475)
334. Checking source_id 4805600119646735616 (RA=83.3667058276365, DEC=-42.95553305572998)
335. Checking source_id 4838250838987898880 (RA=62.384660594435694, DEC=-44.5937681602659)
336. Checking source_id 4846689899968623744 (RA=53.23079051788499, DEC=-44.701350214389144)
337. Checking source_id 4860376345833699840 (RA=54.898570206777336, DEC=-35.42759363988114)
338. Checking source_id 4864160624337973248 (RA=68.17902996429045, DEC=-39.79100877620122)
339. Checking source_id 4872659466967320576 (RA=67.3272896118439, DEC=-31.39865271628241)
340. Checking source_id 4879015915487168384 (RA=69.23691490050261, DEC=-29.0569204851486)
341. Checking source_id 4883809068925124224 (RA=62.23165947039066, DEC=-31.482746317950557)
342. Checking source_id 4884761177275202176 (RA=66.63566693368529, DEC=-30.802598323056248)
343. Checking source_id 4894315447987680640 (RA=68.90113171549795, DEC=-25.46047870256822)
344. Checking source_id 4896480390678599168 (RA=66.04804319730742, DEC=-23.943154274248094)
345. Checking source_id 4912898156569562624 (RA=26.623503842306945, DEC=-53.65951511605823)
346. Checking source_id 4914733005253271040 (RA=18.321365594968658, DEC=-54.486623674742)
347. Checking source_id 4919497979411495296 (RA=2.0695188524464223, DEC=-57.09822684087826)
348. Checking source_id 4929042942932181888 (RA=17.94604714801365, DEC=-49.13780173027396)
349. Checking source_id 4941774600386872960 (RA=28.211506635601257, DEC=-48.095754425177795)
350. Checking source_id 4947513157730843136 (RA=41.29488660260175, DEC=-43.74395570978885)
351. Checking source_id 4960651016012601856 (RA=24.841366809333778, DEC=-39.60350836178757)
352. Checking source_id 4965689356248347648 (RA=37.034810770953925, DEC=-36.472406047033026)
353. Checking source_id 4966072879648455296 (RA=37.489187626886974, DEC=-36.11070763794735)

No data found for target "Gaia DR3 4966072879648455296".

354. Checking source_id 4975284347548097152 (RA=11.424370322965071, DEC=-47.558161328122075)

No data found for target "Gaia DR3 4975284347548097152".

355. Checking source_id 4975847194422433280 (RA=8.30811225525422, DEC=-47.55395581377568)
356. Checking source_id 4995796699034222464 (RA=2.4392791777364233, DEC=-42.02765540973986)
357. Checking source_id 5020179503252128768 (RA=31.449610334078532, DEC=-30.17617825921)
358. Checking source_id 5039735554502890752 (RA=20.68377378657759, DEC=-25.78542674151736)
359. Checking source_id 5041034524411980288 (RA=17.329387245051528, DEC=-24.5073953704236)
360. Checking source_id 5055805741577757824 (RA=52.87633565748463, DEC=-30.71257633526702)
361. Checking source_id 5059643002799575424 (RA=46.97079038744201, DEC=-28.23657947424524)
362. Checking source_id 5075243629687810560 (RA=48.57727876178081, DEC=-23.15750510834894)
363. Checking source_id 5079067147013772288 (RA=43.66648548412693, DEC=-22.266581909507593)
364. Checking source_id 5082514940600694272 (RA=60.12104814020346, DEC=-25.87995956135253)
365. Checking source_id 5110641302736199424 (RA=58.583405672029585, DEC=-14.626996430366534)
366. Checking source_id 5123785831102567680 (RA=34.08872967380762, DEC=-22.012448796550615)
367. Checking source_id 5131300889999108608 (RA=36.875530606173776, DEC=-19.12877052888649)
368. Checking source_id 5142787797211936640 (RA=28.533593959764787, DEC=-15.607511219843047)
369. Checking source_id 5159273530961537280 (RA=44.543868419797654, DEC=-12.882602840627078)
370. Checking source_id 5183110874332308480 (RA=47.9036106160578, DEC=-4.278627146775743)
371. Checking source_id 5185165891628969984 (RA=40.314644601412986, DEC=-4.538542485444145)
372. Checking source_id 5189170557793054848 (RA=159.68433024045862, DEC=-86.54629290223104)
373. Checking source_id 5213167330349528064 (RA=117.3008524617764, DEC=-76.70272278517169)
374. Checking source_id 5260759175761502976 (RA=98.43896955100809, DEC=-75.62380392415764)
375. Checking source_id 5266917261213622144 (RA=100.87412359188694, DEC=-70.05487868120974)
376. Checking source_id 5287046368477870848 (RA=104.98256254599588, DEC=-61.74878384014599)
377. Checking source_id 5292028393100840320 (RA=110.21409706569334, DEC=-62.16902108648849)
378. Checking source_id 5381146215717550336 (RA=176.39577945210556, DEC=-40.933493409092144)
379. Checking source_id 5468091231551021184 (RA=159.43763962372515, DEC=-27.776254901109976)
380. Checking source_id 5471516004114550784 (RA=161.46467275513655, DEC=-23.15077023592966)
381. Checking source_id 5481843025342799104 (RA=96.4834930044876, DEC=-60.05701848235131)
382. Checking source_id 5486916932205092352 (RA=107.40960930410569, DEC=-57.06023470133151)
383. Checking source_id 5550620058937466880 (RA=95.27757860461126, DEC=-49.09274147732291)
384. Checking source_id 5571142580908768384 (RA=92.7211184738034, DEC=-43.40164255784951)
385. Checking source_id 5657274198660921472 (RA=148.8489090294773, DEC=-27.262009487759073)
386. Checking source_id 5677606810060597248 (RA=145.6464031860283, DEC=-19.235729064940955)
387. Checking source_id 5682008056323530368 (RA=142.8412957234274, DEC=-17.295762704607554)
388. Checking source_id 5683119044103789440 (RA=140.69502164812556, DEC=-15.791134557336749)
389. Checking source_id 5686163724944033792 (RA=148.1735302257391, DEC=-15.60441952077654)
390. Checking source_id 5690846274384548864 (RA=146.2242946880038, DEC=-12.348259270729132)
391. Checking source_id 5761985432616501376 (RA=133.39836837028676, DEC=-3.4931644292214545)
392. Checking source_id 5776161813992756992 (RA=262.3503788640829, DEC=-80.14714892351998)
393. Checking source_id 5802998414627069696 (RA=267.1169966232858, DEC=-74.462112650771)
394. Checking source_id 5802998414627070080 (RA=267.1154248644766, DEC=-74.46618671420113)
395. Checking source_id 6113324752547911040 (RA=205.9239625297205, DEC=-40.04188776687056)
396. Checking source_id 6114232433761438208 (RA=209.53254015680207, DEC=-39.63592927128449)
397. Checking source_id 6119528334597735296 (RA=216.07789507666112, DEC=-35.242767894759034)
398. Checking source_id 6140884286374656000 (RA=197.33924464935492, DEC=-40.16195152209893)
399. Checking source_id 6160315989731008768 (RA=189.3413879822573, DEC=-32.01211771374125)
400. Checking source_id 6171593062022433920 (RA=206.69006617532065, DEC=-31.82305317678408)
401. Checking source_id 6173812151364882688 (RA=209.30431353578368, DEC=-29.375884964103)
402. Checking source_id 6203502160773159424 (RA=221.02688491852965, DEC=-34.44835557219465)
403. Checking source_id 6213248060043565184 (RA=230.55627655949743, DEC=-27.825797312308065)
404. Checking source_id 6221167631840454400 (RA=216.5238030463142, DEC=-29.781111592648628)
405. Checking source_id 6235533167875990272 (RA=238.1869310006881, DEC=-26.38915421137295)

No data found for target "Gaia DR3 6235533167875990272".

406. Checking source_id 6242063304871870592 (RA=241.6211962565556, DEC=-24.122605217741636)
407. Checking source_id 6274832977622107264 (RA=210.69268639294623, DEC=-24.528814983299633)
408. Checking source_id 6290519435137636224 (RA=209.7907314283468, DEC=-19.835179948860276)
409. Checking source_id 6302599662016881664 (RA=209.5831773084932, DEC=-13.273879021103491)
410. Checking source_id 6302909449418261120 (RA=213.94124035505024, DEC=-13.493135958190171)
411. Checking source_id 6311012064136913920 (RA=220.44099075609032, DEC=-14.45563075942006)
412. Checking source_id 6324308389531786112 (RA=217.7529796815058, DEC=-12.297869679498262)
413. Checking source_id 6337717243069148032 (RA=220.75503345248413, DEC=-5.654254209998345)

No data found for target "Gaia DR3 6337717243069148032".

414. Checking source_id 6342940473056949120 (RA=326.6919266604704, DEC=-85.71878034422768)
415. Checking source_id 6343789261675614464 (RA=346.8620932514289, DEC=-84.86803600287753)
416. Checking source_id 6343965492773694464 (RA=352.6454136504384, DEC=-84.92220191651951)
417. Checking source_id 6359521108406068992 (RA=282.2114626702034, DEC=-82.24624920519395)
418. Checking source_id 6366571314402539008 (RA=304.05133275745055, DEC=-75.51775999531469)
419. Checking source_id 6367463327570835328 (RA=292.41454163597473, DEC=-74.74499106636954)
420. Checking source_id 6371660537113102976 (RA=321.98723385002035, DEC=-72.28794764107055)
421. Checking source_id 6381623044470172672 (RA=340.4960624875462, DEC=-75.00821792446833)
422. Checking source_id 6383229053001389312 (RA=332.5622450415509, DEC=-71.76929995017014)
423. Checking source_id 6386280060329151616 (RA=358.3593934660763, DEC=-70.94461574811649)
424. Checking source_id 6398188767690594048 (RA=336.09392717197517, DEC=-65.97694057827437)
425. Checking source_id 6402860489518406144 (RA=327.36082199142527, DEC=-63.11246709845328)
426. Checking source_id 6405457982659103872 (RA=333.46143166945996, DEC=-63.702023164643734)
427. Checking source_id 6408509574103239552 (RA=336.1020654088805, DEC=-58.4372924747797)
428. Checking source_id 6415630939116638464 (RA=292.7596556224023, DEC=-73.61878815166652)
429. Checking source_id 6421374031949679744 (RA=284.01803778313814, DEC=-69.36730317347698)
430. Checking source_id 6424217300298269568 (RA=301.7005986943156, DEC=-67.6140994648447)
431. Checking source_id 6437366909611503104 (RA=276.58219550905926, DEC=-65.79742068685235)
432. Checking source_id 6446274293824799488 (RA=289.91952257165434, DEC=-59.92317486728616)
433. Checking source_id 6456884409233519360 (RA=315.805198569885, DEC=-56.96185322955984)
434. Checking source_id 6462049502543522688 (RA=323.9144197383885, DEC=-53.42468721801943)
435. Checking source_id 6468337884421010048 (RA=304.9573471563971, DEC=-58.28012185634601)
436. Checking source_id 6469383588698276480 (RA=306.90363380423844, DEC=-54.88222294269785)
437. Checking source_id 6472836050915560448 (RA=302.1006290894661, DEC=-55.357946447725794)
438. Checking source_id 6478328150150225664 (RA=315.27888909461694, DEC=-49.12456979699407)
439. Checking source_id 6487483783474213632 (RA=359.6844071176511, DEC=-62.761415023739694)
440. Checking source_id 6487693790194944128 (RA=358.6747226512832, DEC=-61.58699736797349)
441. Checking source_id 6522188390538224640 (RA=356.6320742231057, DEC=-50.7263749471709)
442. Checking source_id 6554995893362365952 (RA=348.7598304428063, DEC=-35.472806727469305)
443. Checking source_id 6561146458331160320 (RA=328.6866968776705, DEC=-46.99435689427491)
444. Checking source_id 6572811211549713792 (RA=327.88311437897886, DEC=-40.290948939179614)
445. Checking source_id 6575069780231675264 (RA=330.6269230434408, DEC=-37.08193913674626)
446. Checking source_id 6599565765426015232 (RA=334.33070901737386, DEC=-34.73633155418452)
447. Checking source_id 6600863910701061632 (RA=339.71603972979403, DEC=-32.27585374173224)
448. Checking source_id 6608187792013181312 (RA=339.6059287587044, DEC=-29.35802125906652)
449. Checking source_id 6612817217002464128 (RA=329.70705396749236, DEC=-32.47323280840755)
450. Checking source_id 6612817835477756160 (RA=329.70265125152406, DEC=-32.44203323266612)
451. Checking source_id 6613969195950456448 (RA=334.858951355117, DEC=-31.061723984283592)
452. Checking source_id 6623351805412369024 (RA=342.0203381724408, DEC=-24.369627417603155)
453. Checking source_id 6637017330494491648 (RA=283.70836681424106, DEC=-57.07969410501362)
454. Checking source_id 6645504151509887744 (RA=293.5167610204471, DEC=-52.42173789201841)
455. Checking source_id 6650117736660187136 (RA=280.7780058472517, DEC=-54.61562415094667)
456. Checking source_id 6658123517042686464 (RA=288.164090058716, DEC=-50.271765612752674)
457. Checking source_id 6671213104189712000 (RA=298.49966039519774, DEC=-47.8150277282357)
458. Checking source_id 6672112470338969856 (RA=302.4651437572208, DEC=-47.527716567604266)
459. Checking source_id 6674554829263069440 (RA=309.34041351902783, DEC=-46.73127945877358)
460. Checking source_id 6742962972412390912 (RA=290.5241642082332, DEC=-35.063462184524234)
461. Checking source_id 6744957928883188736 (RA=294.61464248866554, DEC=-32.52523817811287)
462. Checking source_id 6768500538717144064 (RA=296.2257504183332, DEC=-23.633980573875828)
463. Checking source_id 6773453838597541760 (RA=315.2680353695968, DEC=-41.24370426778464)
464. Checking source_id 6779821003058453120 (RA=312.5691416793731, DEC=-34.413153176093374)
465. Checking source_id 6805970245721550080 (RA=314.1147209082977, DEC=-24.00400432430843)
466. Checking source_id 6817950657560102016 (RA=326.69107096359306, DEC=-21.29660962151476)
467. Checking source_id 6823449766182657280 (RA=328.76028235110175, DEC=-20.24027219429661)
468. Checking source_id 6851779920225659136 (RA=301.1288564266629, DEC=-23.70213617627802)
469. Checking source_id 6853658057885526912 (RA=301.3968679556646, DEC=-22.304962207672475)
470. Checking source_id 6856077189625042688 (RA=308.40224210084426, DEC=-21.336459771050528)
471. Checking source_id 6858958940879829248 (RA=312.4711253064467, DEC=-17.26945706554899)

No data found for target "Gaia DR3 6858958940879829248".

472. Checking source_id 6868107358662346112 (RA=295.50308205557945, DEC=-21.069272230763502)
473. Checking source_id 6868221463056407168 (RA=295.553370876108, DEC=-20.764012353990857)

No data found for target "Gaia DR3 6868221463056407168".

474. Checking source_id 6895572437565417856 (RA=317.85070768221846, DEC=-9.677453339060431)
475. Checking source_id 6900333494712655616 (RA=311.68342967315823, DEC=-11.80400321707132)
476. Checking source_id 6914281796143286784 (RA=310.68929166017307, DEC=-5.004806087747568)
477. Checking source_id 6916929660661726208 (RA=313.28984955557723, DEC=-1.552171010067834)
478. Checking source_id 121254932585133568 (RA=54.03685781019895, DEC=31.31038873961227)
479. Checking source_id 144312344255035392 (RA=68.39367443219042, DEC=20.74463639402465)
480. Checking source_id 150510158159630848 (RA=65.74709242385883, DEC=25.986214128203905)
481. Checking source_id 156150240492946816 (RA=77.66340440529314, DEC=29.78023889010632)
482. Checking source_id 179700710496485504 (RA=67.60697228135813, DEC=39.84732582326925)
483. Checking source_id 200296663143599104 (RA=73.15109158635963, DEC=40.70183928537737)
484. Checking source_id 205533465225342208 (RA=76.27525560161628, DEC=44.23424149518413)
485. Checking source_id 207033680124098048 (RA=76.39343357193754, DEC=46.79953911392597)
486. Checking source_id 230171768457140736 (RA=59.3320361570653, DEC=41.12839689730314)
487. Checking source_id 258996015538087680 (RA=71.58398349941925, DEC=48.74489866356334)
488. Checking source_id 260343123440688128 (RA=72.26910056105879, DEC=51.643088269642206)
489. Checking source_id 265201384281320448 (RA=87.85441435895838, DEC=55.18811792034226)
490. Checking source_id 269066953631488384 (RA=89.98201323957848, DEC=58.56976827470822)
491. Checking source_id 353610331133759744 (RA=35.5628493353625, DEC=45.70035456975228)
492. Checking source_id 358249819229900672 (RA=32.225052363016104, DEC=49.44771631277939)
493. Checking source_id 358269546017619840 (RA=31.76767495536706, DEC=49.643504110332174)

No data found for target "Gaia DR3 358269546017619840".

494. Checking source_id 393155984814848128 (RA=2.025945508249953, DEC=47.95067855186984)
495. Checking source_id 393621524910343296 (RA=2.2322728822606455, DEC=49.31654365243212)

No data found for target "2.2322728822606455 49.31654365243212".
No data found for target "Gaia DR3 393621524910343296".

496. Checking source_id 411311395692644224 (RA=15.495585706669338, DEC=54.18217771927336)
497. Checking source_id 415665118140313472 (RA=9.63951695492825, DEC=51.46623313406483)
498. Checking source_id 418363560198079616 (RA=9.826094856422966, DEC=55.13591102822271)
499. Checking source_id 419624356438705152 (RA=6.314208313156801, DEC=54.380246070851605)
500. Checking source_id 423027104407576576 (RA=2.874734923550554, DEC=59.13922658078038)
501. Checking source_id 439595542043685888 (RA=44.527654103364355, DEC=50.2384703559099)
502. Checking source_id 445100418805396608 (RA=52.70255404316823, DEC=54.231972478973546)
503. Checking source_id 459215468053012096 (RA=34.98428465514067, DEC=59.32335305221488)
504. Checking source_id 466652427262218240 (RA=45.012514355122065, DEC=62.86500045511667)
505. Checking source_id 474987206435652608 (RA=58.29378718240847, DEC=62.56771136910784)
506. Checking source_id 476809509515283712 (RA=63.07602734404104, DEC=64.73018080218111)
507. Checking source_id 477826420331704064 (RA=73.41994024991934, DEC=62.31662864915945)
508. Checking source_id 482089261274984064 (RA=73.62491412218532, DEC=65.07763013001318)
509. Checking source_id 505516521175942784 (RA=29.850702638903563, DEC=58.52028397205597)
510. Checking source_id 515045129459646080 (RA=31.795389122280643, DEC=64.28574993877805)
511. Checking source_id 522864272041351296 (RA=15.83964458528098, DEC=62.36589259248621)
512. Checking source_id 532266024164292352 (RA=23.291015466764694, DEC=69.96894582310217)
513. Checking source_id 549007291282705024 (RA=44.339286532301905, DEC=76.55134902167823)
514. Checking source_id 555032443207370880 (RA=61.66178755097324, DEC=79.2652664645624)
515. Checking source_id 671436777166606976 (RA=114.71207091660123, DEC=18.488193351242423)
516. Checking source_id 890284258753196544 (RA=109.07456243442758, DEC=33.150948447796246)
517. Checking source_id 939599584345993984 (RA=105.84622747575096, DEC=34.698233312449034)
518. Checking source_id 970354749937140736 (RA=90.62210758518228, DEC=49.86182103675996)
519. Checking source_id 971499272821709440 (RA=93.5071616638108, DEC=51.668469680157074)
520. Checking source_id 997801721262070912 (RA=96.4717182937526, DEC=56.17135899080708)
521. Checking source_id 1104878103513141760 (RA=90.61043756165334, DEC=66.34230092025918)
522. Checking source_id 1752189568342546048 (RA=305.84222990657156, DEC=8.003250060157944)
523. Checking source_id 1762523981210977664 (RA=311.1575675254911, DEC=15.292303822792627)
524. Checking source_id 1810616448010879488 (RA=310.14718809392286, DEC=15.502590198203675)
525. Checking source_id 1862034696988864896 (RA=305.5638248021488, DEC=31.295355736427048)
526. Checking source_id 1905816425352678656 (RA=336.25690873315784, DEC=35.668126158187434)
527. Checking source_id 1923896622760418176 (RA=352.34657450570336, DEC=41.46426656329359)
528. Checking source_id 1934862945577481344 (RA=345.7178593481215, DEC=43.6376403112615)
529. Checking source_id 1941011930001137280 (RA=358.73570743127874, DEC=50.60416096368615)
530. Checking source_id 1952802469918554368 (RA=326.5928819418585, DEC=38.21751708114409)
531. Checking source_id 1958030617647715328 (RA=332.8501471342748, DEC=40.999937747390554)
532. Checking source_id 1965478468902062464 (RA=321.13780325406816, DEC=40.06853292389345)
533. Checking source_id 1974606167761195904 (RA=326.7361495066119, DEC=46.635039174978616)
534. Checking source_id 2001345397199713152 (RA=336.2346972856473, DEC=52.007111377537385)
535. Checking source_id 2012619720701400192 (RA=355.96646640493077, DEC=61.03541809766475)
536. Checking source_id 2014653404891943936 (RA=343.5831299528126, DEC=60.9948603958803)
537. Checking source_id 2022893621784904064 (RA=291.50765658547584, DEC=24.438522554529968)
538. Checking source_id 2042871958509344896 (RA=287.1236406175739, DEC=32.28000653137807)
539. Checking source_id 2045458628362127360 (RA=294.6829962716154, DEC=33.19441313934374)
540. Checking source_id 2047690533883897856 (RA=297.17034072865096, DEC=35.92017560607515)
541. Checking source_id 2050589430625453824 (RA=288.1237527690882, DEC=35.56394945542676)
542. Checking source_id 2054269874008075904 (RA=305.578413996564, DEC=32.287514824881384)
543. Checking source_id 2056115198113182208 (RA=307.0937101191311, DEC=34.20220748536728)
544. Checking source_id 2063967910147595008 (RA=309.1927827933898, DEC=38.84173999457955)
545. Checking source_id 2066768499405895296 (RA=313.2412180042452, DEC=43.17197818114904)
546. Checking source_id 2080285727861817088 (RA=297.79001858504904, DEC=46.48457360658962)
547. Checking source_id 2090085056523454464 (RA=280.4944113394081, DEC=31.83052644422543)
548. Checking source_id 2091177593123254016 (RA=278.90744884954285, DEC=32.994787158699616)
549. Checking source_id 2098413719661573248 (RA=280.4043356891839, DEC=39.70257169518205)
550. Checking source_id 2098514324976071424 (RA=280.8414837270263, DEC=40.67522342269669)
551. Checking source_id 2105033123258653056 (RA=283.7690701880948, DEC=42.99751921986174)
552. Checking source_id 2107257297843283584 (RA=284.1100119283428, DEC=46.382926799980986)
553. Checking source_id 2119686379142441472 (RA=282.6902545804929, DEC=47.97148162043484)
554. Checking source_id 2125777643503392640 (RA=291.8257765035261, DEC=42.53079017110482)
555. Checking source_id 2135110259540829824 (RA=294.0599087081086, DEC=50.22063557211082)
556. Checking source_id 2173367633501430272 (RA=324.5723456671, DEC=52.955345203478224)
557. Checking source_id 2185710338703934976 (RA=301.25028584217137, DEC=54.43021426747369)
558. Checking source_id 2188318517720321664 (RA=306.5243172601894, DEC=58.57537971545967)
559. Checking source_id 2213428064767263360 (RA=346.8886073691008, DEC=68.66835203448122)
560. Checking source_id 2218904319868065408 (RA=333.85898858277557, DEC=66.22529504635877)
561. Checking source_id 2222540228723911168 (RA=326.67209809426436, DEC=66.80387671285244)
562. Checking source_id 2247535151679497472 (RA=299.56795496573375, DEC=65.04026975891064)
563. Checking source_id 2281046483684995840 (RA=336.79143736412533, DEC=77.86718788883624)
564. Checking source_id 2282790893241302144 (RA=350.7290232368062, DEC=78.79433614628547)
565. Checking source_id 2913314288686472576 (RA=93.44641834723038, DEC=-23.906400629805045)
566. Checking source_id 2913411183147100416 (RA=93.43901141965836, DEC=-23.86821581115909)

No data found for target "Gaia DR3 2913411183147100416".

567. Checking source_id 2918040883015489408 (RA=90.59401922772396, DEC=-20.32646095303724)
568. Checking source_id 2920124904228150144 (RA=100.91781659682088, DEC=-26.412851737979935)
569. Checking source_id 2926033267402660224 (RA=101.67024419717264, DEC=-21.83802845727015)
570. Checking source_id 2999254213453678720 (RA=89.16931209956947, DEC=-10.309936799168852)
571. Checking source_id 3005440443830195968 (RA=90.72650698393748, DEC=-9.253679424751372)
572. Checking source_id 3007559370624135424 (RA=94.836432883577, DEC=-6.658919729456425)
573. Checking source_id 3023121827755777280 (RA=85.55220113669213, DEC=-5.461181586870268)
574. Checking source_id 3026511175437908096 (RA=112.05454567294036, DEC=-18.790322998386273)
575. Checking source_id 3046640175314154624 (RA=106.30041622285356, DEC=-10.131001534433214)
576. Checking source_id 3051343817347672576 (RA=107.63069808891784, DEC=-8.712967693425067)
577. Checking source_id 3059182338820698624 (RA=108.29665561709618, DEC=-5.198202455814469)
578. Checking source_id 3059246454092369024 (RA=109.32310142871492, DEC=-5.0193865914700995)
579. Checking source_id 3060641356390249728 (RA=112.19128658651584, DEC=-3.301647006516706)
580. Checking source_id 3080857458209146368 (RA=117.42488030146365, DEC=-3.3430177047924063)
581. Checking source_id 3089829644889680256 (RA=122.7004539534854, DEC=1.1540989604627692)
582. Checking source_id 3104733181410232576 (RA=98.87393995438822, DEC=-4.0547741963145425)
583. Checking source_id 3127503620545728128 (RA=100.54682814138062, DEC=3.5801351731802407)
584. Checking source_id 3134682194522547968 (RA=113.57319136841932, DEC=0.9832433944126404)
585. Checking source_id 3136232952593850496 (RA=112.87192845713916, DEC=2.819034946832578)
586. Checking source_id 3136952686035250688 (RA=116.1658359308822, DEC=3.5504844454883244)
587. Checking source_id 3143635723866162432 (RA=117.96608429205932, DEC=5.5473917843088385)
588. Checking source_id 3144499458967932672 (RA=119.53643234079507, DEC=7.283595270088088)
589. Checking source_id 3154550541435395200 (RA=106.30160565523498, DEC=8.429349117067947)
590. Checking source_id 3316364602541746048 (RA=90.01597644159976, DEC=2.7063740799024933)
591. Checking source_id 3317901440625203968 (RA=94.29340278756932, DEC=5.118125291285412)

No data found for target "Gaia DR3 3317901440625203968".

592. Checking source_id 3325157736332326784 (RA=92.8333873160516, DEC=7.184300019759825)
593. Checking source_id 3336130626153639424 (RA=85.22382048241539, DEC=8.905037560985615)
594. Checking source_id 3339914973377653760 (RA=84.16024229906046, DEC=11.296613294698856)
595. Checking source_id 3341624061123288448 (RA=83.71660430393523, DEC=13.87787924781139)
596. Checking source_id 3348805143361118464 (RA=89.00194337351587, DEC=15.766279215720711)
597. Checking source_id 3352081447497931264 (RA=100.42870725855788, DEC=12.445392442104405)
598. Checking source_id 3352091927220152320 (RA=99.02567810888785, DEC=11.613741303546275)
599. Checking source_id 3361034083487398016 (RA=106.14366570307368, DEC=16.956605362921632)
600. Checking source_id 3390044040652614656 (RA=82.65453223954857, DEC=15.24064022866458)
601. Checking source_id 3394484074763973504 (RA=80.44960452985814, DEC=17.343472744693543)
602. Checking source_id 3410478399832994688 (RA=68.65672101895085, DEC=19.10111134882547)
603. Checking source_id 3411398347466374144 (RA=70.73293563415463, DEC=21.473566186536463)
604. Checking source_id 3418324583527645440 (RA=75.32477273200419, DEC=22.61536006911671)
605. Checking source_id 3428298528382128000 (RA=88.25801375874899, DEC=25.12803987623394)
606. Checking source_id 3435919896308345856 (RA=98.6395067289538, DEC=31.50140313353504)
607. Checking source_id 3449170488894369792 (RA=83.2148749335413, DEC=33.827735578720784)
608. Checking source_id 4038724053950164096 (RA=271.5994368768923, DEC=-36.02315817876133)

No data found for target "Gaia DR3 4038724053950164096".

609. Checking source_id 4040839376832467584 (RA=268.5107931154532, DEC=-34.67277670489463)
610. Checking source_id 4055579464064558592 (RA=266.6704915930946, DEC=-32.23412636909977)
611. Checking source_id 4078319494857310336 (RA=280.54710817071043, DEC=-23.484031970853025)
612. Checking source_id 4092990622155744000 (RA=276.6302402477138, DEC=-19.39395723243286)
613. Checking source_id 4095396422225930624 (RA=270.90095793365253, DEC=-18.98205434475698)
614. Checking source_id 4101968375059565568 (RA=282.00420159430814, DEC=-14.581942889145273)
615. Checking source_id 4110023156763233408 (RA=261.8107667727851, DEC=-25.162126124890616)
616. Checking source_id 4127182375667696128 (RA=254.13911786858904, DEC=-20.77796755384291)
617. Checking source_id 4130971047908354304 (RA=249.4304219999168, DEC=-20.226456686831902)
618. Checking source_id 4165561928540617856 (RA=266.6220201822353, DEC=-8.712042478984)

No data found for target "266.6220201822353 -8.712042478984".
No data found for target "Gaia DR3 4165561928540617856".

619. Checking source_id 4168368844280868992 (RA=263.5353570622817, DEC=-8.832425873814643)

No data found for target "263.5353570622817 -8.832425873814643".
No data found for target "Gaia DR3 4168368844280868992".

620. Checking source_id 4177911333902753280 (RA=272.2238175099148, DEC=-2.1159832414070445)
621. Checking source_id 4192723988912416256 (RA=300.9931913964132, DEC=-8.130958023358552)
622. Checking source_id 4202659377841518720 (RA=285.81106903339054, DEC=-9.535830690792572)
623. Checking source_id 4213581106021661184 (RA=292.77003917182395, DEC=-3.102897138507079)
624. Checking source_id 4223813264304668288 (RA=302.32583654605094, DEC=-1.2289714355165018)
625. Checking source_id 4242728884389090944 (RA=303.2508406645244, DEC=1.2158307317171082)
626. Checking source_id 4247106761739962880 (RA=301.23744889203846, DEC=3.350649778524621)
627. Checking source_id 4257891802569298048 (RA=277.6634404154124, DEC=-3.9390440317740865)

No data found for target "Gaia DR3 4257891802569298048".

628. Checking source_id 4276632394156013440 (RA=276.022285849461, DEC=1.6867594792255736)
629. Checking source_id 4277318077096011264 (RA=274.0739324349659, DEC=1.5214295166369465)
630. Checking source_id 4279261876207080576 (RA=283.3570176109194, DEC=2.8470624550523547)

No data found for target "Gaia DR3 4279261876207080576".

631. Checking source_id 4286249341336984576 (RA=282.0747587449577, DEC=7.690323894810538)
632. Checking source_id 4311982650767794176 (RA=283.5714196687941, DEC=10.969734789639295)
633. Checking source_id 4361639417663824768 (RA=259.0868121132202, DEC=-5.398155460437159)

No data found for target "259.0868121132202 -5.398155460437159".
No data found for target "Gaia DR3 4361639417663824768".

634. Checking source_id 4363875373342033664 (RA=261.5634344754104, DEC=-3.192392272704998)

No data found for target "261.5634344754104 -3.192392272704998".
No data found for target "Gaia DR3 4363875373342033664".

635. Checking source_id 4470812298018311296 (RA=274.13072292110206, DEC=4.881193235821266)
636. Checking source_id 4475881317196185728 (RA=268.5686657879008, DEC=7.377832327281468)

No data found for target "268.5686657879008 7.377832327281468".
No data found for target "Gaia DR3 4475881317196185728".

637. Checking source_id 4489306942580947584 (RA=265.4751620316947, DEC=9.680499876229684)

No data found for target "265.4751620316947 9.680499876229684".
No data found for target "Gaia DR3 4489306942580947584".

638. Checking source_id 4496383055821714816 (RA=269.59373567871177, DEC=12.760552335950688)
639. Checking source_id 4498055584805914752 (RA=271.16198277595925, DEC=13.904135825968742)
640. Checking source_id 4502369583096912896 (RA=271.7024404523592, DEC=17.347173925497184)
641. Checking source_id 4505805591300126080 (RA=280.6872687939103, DEC=13.906220985923316)
642. Checking source_id 4508377078422114944 (RA=279.0809524821553, DEC=13.608565199505213)
643. Checking source_id 4512525016089353472 (RA=281.34496634633183, DEC=18.865092511988657)
644. Checking source_id 4519789081415296128 (RA=286.8027296402767, DEC=20.875538401484672)
645. Checking source_id 4519789321942643072 (RA=286.7709107522999, DEC=20.88648751787881)
646. Checking source_id 4525711600783788160 (RA=279.38295544494116, DEC=20.51039866122592)
647. Checking source_id 4534214948839463040 (RA=282.9185149722373, DEC=24.458792373775765)
648. Checking source_id 4535928365908540416 (RA=280.2931336884971, DEC=24.787728362716255)
649. Checking source_id 4535928365908541440 (RA=280.2932736323553, DEC=24.78903471867591)
650. Checking source_id 4579825847951057792 (RA=273.2784750722023, DEC=26.030906428526674)
651. Checking source_id 4586421272746553472 (RA=275.86767226420693, DEC=28.166943770663465)
652. Checking source_id 4587614930058979584 (RA=279.8882509500303, DEC=29.870257114332887)
653. Checking source_id 5199087706000356096 (RA=161.9002962835104, DEC=-79.46369785139531)
654. Checking source_id 5222018879990530304 (RA=133.76679892825808, DEC=-71.59438347686567)
655. Checking source_id 5225863906515477376 (RA=163.8163930280901, DEC=-73.9368211911611)
656. Checking source_id 5241011156681563136 (RA=166.13864488936107, DEC=-62.54316032322312)
657. Checking source_id 5249254676369630336 (RA=144.214659619105, DEC=-65.23023843939158)
658. Checking source_id 5249863805819472640 (RA=145.71175224473672, DEC=-63.63190837805288)
659. Checking source_id 5271055243163629056 (RA=124.53289609935436, DEC=-68.31451297878304)
660. Checking source_id 5274724279106403968 (RA=120.63020270507428, DEC=-66.0264302882151)

No data found for target "Gaia DR3 5274724279106403968".

661. Checking source_id 5291484512805323264 (RA=121.444646526896, DEC=-59.21648809056944)
662. Checking source_id 5293288295987250816 (RA=110.83713664387948, DEC=-60.10162913000041)
663. Checking source_id 5298261284001871616 (RA=134.02504674847916, DEC=-61.96276891065736)
664. Checking source_id 5302788969815543936 (RA=129.50851733832943, DEC=-58.934301092646784)
665. Checking source_id 5307525906414825216 (RA=147.10558785257808, DEC=-56.73799973608294)
666. Checking source_id 5309974484478157696 (RA=139.21177443154738, DEC=-55.931717293874456)
667. Checking source_id 5315595737654226304 (RA=125.69448341721365, DEC=-57.4459015804563)
668. Checking source_id 5315595737654226560 (RA=125.69640715493324, DEC=-57.44392391891117)
669. Checking source_id 5344026286547761664 (RA=176.9689952882439, DEC=-55.06914073247352)
670. Checking source_id 5353126879893514368 (RA=164.52226495558665, DEC=-55.42154439805064)
671. Checking source_id 5380149023092265856 (RA=179.90447706741833, DEC=-42.946229979317195)
672. Checking source_id 5393446658454453632 (RA=162.05388771666577, DEC=-39.93962594730691)

No data found for target "Gaia DR3 5393446658454453632".

673. Checking source_id 5418743844032438400 (RA=150.12849579829455, DEC=-41.50815733346062)
674. Checking source_id 5424690587034982144 (RA=143.35813068013894, DEC=-43.89273302384089)
675. Checking source_id 5432670704985289088 (RA=145.8742485909251, DEC=-38.56630443256017)
676. Checking source_id 5439029627401396096 (RA=146.491875412928, DEC=-32.89101863068049)
677. Checking source_id 5440359486716251904 (RA=157.78388333811384, DEC=-41.46334165948587)
678. Checking source_id 5441169002153568512 (RA=159.8833472486551, DEC=-38.3370450973924)
679. Checking source_id 5458784415381054464 (RA=151.1632016429737, DEC=-33.58751841752631)
680. Checking source_id 5492622847798742272 (RA=114.05296644815438, DEC=-51.920572905284935)
681. Checking source_id 5519117229744210944 (RA=119.2234839106459, DEC=-45.63440964675406)
682. Checking source_id 5529120822749728384 (RA=130.17026521119897, DEC=-38.5440354728072)
683. Checking source_id 5538156819768871552 (RA=118.72808136767864, DEC=-38.1588602813617)
684. Checking source_id 5559035514776717312 (RA=104.43647190771412, DEC=-44.291651313997995)
685. Checking source_id 5559035514779971456 (RA=104.4373295461301, DEC=-44.29139605439596)
686. Checking source_id 5565156633450986752 (RA=107.756214337062, DEC=-38.416464112266354)
687. Checking source_id 5588141992752796800 (RA=113.0312367991138, DEC=-36.124874823995825)
688. Checking source_id 5590736084278574464 (RA=109.52970180819229, DEC=-35.03913110858024)
689. Checking source_id 5599170330597007360 (RA=114.23733886623396, DEC=-30.406159966819494)
690. Checking source_id 5605438925569442432 (RA=111.65703095378969, DEC=-30.552171859726773)
691. Checking source_id 5611909104822545152 (RA=112.50772620155806, DEC=-28.517137799167745)
692. Checking source_id 5638902733763290752 (RA=128.88177876022422, DEC=-34.012228263178855)
693. Checking source_id 5642693123990628480 (RA=132.54220377468857, DEC=-28.367734260766717)
694. Checking source_id 5645479806157346688 (RA=129.640992950549, DEC=-28.72463006600081)
695. Checking source_id 5649998554125258368 (RA=138.05301863125402, DEC=-25.917628165480735)
696. Checking source_id 5653063069125830016 (RA=133.83156827756443, DEC=-23.87057312949651)
697. Checking source_id 5655050092795276800 (RA=136.7599966689761, DEC=-22.149052356271294)
698. Checking source_id 5661077924778519552 (RA=143.61785482348142, DEC=-26.72420885027511)
699. Checking source_id 5695264936746881536 (RA=126.77920858602496, DEC=-25.449225363796145)
700. Checking source_id 5700706729031126656 (RA=123.17043503163158, DEC=-21.55502398567159)
701. Checking source_id 5798502241016325120 (RA=225.5285537730114, DEC=-71.3014454095702)
702. Checking source_id 5808918155180366336 (RA=245.74844307047053, DEC=-69.09925953111602)
703. Checking source_id 5815970800722940800 (RA=251.9835074590181, DEC=-65.1536701406655)
704. Checking source_id 5819260642586368896 (RA=243.27172696880103, DEC=-70.15478761691558)
705. Checking source_id 5823352234607843968 (RA=232.7190589672623, DEC=-68.02160045447148)
706. Checking source_id 5840719364353028096 (RA=203.54159732659855, DEC=-71.36573625307176)
707. Checking source_id 5861048509766415616 (RA=189.57987020199144, DEC=-65.2456804598289)
708. Checking source_id 5900432500841313920 (RA=227.73324902272088, DEC=-51.69293779799564)
709. Checking source_id 5918660719983560192 (RA=266.6334444727895, DEC=-57.32506180218072)
710. Checking source_id 5925209514333720832 (RA=262.56573118520566, DEC=-51.6404321272004)
711. Checking source_id 5930139823230549120 (RA=249.9034373299412, DEC=-55.410609508601574)
712. Checking source_id 5931193640795532288 (RA=248.90361401821815, DEC=-52.03316495042088)
713. Checking source_id 5934097210481810432 (RA=248.3305162924753, DEC=-52.133851689110905)
714. Checking source_id 5942630107855861888 (RA=249.85706385766625, DEC=-46.88472519104563)
715. Checking source_id 5942777301034031104 (RA=250.19082185115985, DEC=-46.0015821042613)
716. Checking source_id 5943550124208359552 (RA=250.36544421749787, DEC=-43.98861786008088)
717. Checking source_id 5951535219996858624 (RA=263.08991610394963, DEC=-47.61694873889592)
718. Checking source_id 5983356259047553792 (RA=241.289897795576, DEC=-49.79967353527323)
719. Checking source_id 6012127622177717760 (RA=238.0267491026858, DEC=-33.988375449427416)
720. Checking source_id 6013642341180098432 (RA=233.06765151878705, DEC=-35.351264008293)
721. Checking source_id 6018209128388194688 (RA=246.71366499706508, DEC=-38.210202611793854)
722. Checking source_id 6025146733201615616 (RA=246.0683856455975, DEC=-32.20398349011275)
723. Checking source_id 6039144001564707072 (RA=243.5893264382953, DEC=-28.511686254176517)
724. Checking source_id 6056881391901174528 (RA=193.80080693446232, DEC=-59.4731389365543)
725. Checking source_id 6065173805485251072 (RA=207.84330351703483, DEC=-53.54792876649116)
726. Checking source_id 6066971747504719232 (RA=200.51762131763667, DEC=-55.01702752746204)
727. Checking source_id 6069775296000876416 (RA=202.60339969669704, DEC=-52.04614105231651)
728. Checking source_id 6073573215330461952 (RA=191.47157086795116, DEC=-55.114536629695976)
729. Checking source_id 6096529059601571200 (RA=214.19550544539564, DEC=-44.888706723102096)
730. Checking source_id 6109610086872510592 (RA=210.9624810075537, DEC=-42.699347027825176)
731. Checking source_id 6109949904687424640 (RA=212.99539892266264, DEC=-41.539721990460095)
732. Checking source_id 6116110468338455680 (RA=214.35558247321825, DEC=-40.304202316175186)
733. Checking source_id 6143175943486753152 (RA=182.48992008073932, DEC=-46.19264116008711)

No data found for target "Gaia DR3 6143175943486753152".

734. Checking source_id 6725832095922016256 (RA=273.3347119890693, DEC=-39.84395218207264)
735. Checking source_id 6734485286788609664 (RA=277.3507091117809, DEC=-34.96362316023356)
736. Checking source_id 6759481141756109056 (RA=290.376709235217, DEC=-29.2629248637208)

,ID,DataType,Sector,Exposure_Time,FFI_Avail,SPOC_Avail
0,769456276704128,FFI,4.0,1425.599419,True,True
1,769456276704128,FFI,31.0,475.19979,True,True
2,769456276704128,SPOC,NaN,[120.0 s],True,True
3,769456276704128,SPOC,NaN,[120.0 s],True,True
4,16302463200535040,FFI,31.0,475.19979,True,True
...,...,...,...,...,...,...
8950,6734485286788609664,SPOC,NaN,[120.0 s],True,True
8951,6759481141756109056,FFI,13.0,1425.599392,True,True
8952,6759481141756109056,FFI,27.0,475.199782,True,True
8953,6759481141756109056,FFI,92.0,158.399926,True,True
8954,6759481141756109056,SPOC,NaN,[120.0 s],True,True

Saved in tess_id_sector_exptime_G16d20_all_filtered_UPDATED_test.csv

In [14]:
#looks specifically for spoc (short cadence, selected targets)
lk.search_targetpixelfile("Gaia DR3 769456276704128", mission="TESS", author="SPOC")

HTTPError: 500 Server Error: Internal Server Error for url: https://mast.stsci.edu/api/v0/invoke?request=%7B%22service%22%3A%20%22Mast.Name.Lookup%22%2C%20%22params%22%3A%20%7B%22input%22%3A%20%22Gaia%20DR3%20769456276704128%22%2C%20%22format%22%3A%20%22json%22%7D%7D

In [19]:
#FFI
lk.search_tesscut("Gaia DR3 769456276704128")

SearchResult containing 2 data products.

 #     mission     year  author exptime       target_name        distance
                                   s                              arcsec
--- -------------- ---- ------- ------- ------------------------ --------
  0 TESS Sector 04 2018 TESScut    1426 Gaia DR3 769456276704128      0.0
  1 TESS Sector 31 2020 TESScut     475 Gaia DR3 769456276704128      0.0

In [25]:
import pandas as pd
import lightkurve as lk
import time
import re

def get_sector_from_tab(tab):
    """Try to read sector from columns; otherwise parse from mission string 'TESS Sector XX'."""
    # direct columns first
    if "sector" in tab.colnames:
        try:
            return int(tab["sector"][0])
        except Exception:
            pass
    if "sequence_number" in tab.colnames:
        try:
            return int(tab["sequence_number"][0])
        except Exception:
            pass

    # parse from mission string (common for search_targetpixelfile results)
    if "mission" in tab.colnames:
        m = re.search(r"Sector\s+(\d+)", str(tab["mission"][0]))
        if m:
            return int(m.group(1))

    return None


# load data from .csv
table = pd.read_csv("TESS_M=0.4_RP=15.csv")

# convert parallax from mas to pc
table["distance_pc"] = 1000 / table["parallax"]

# filtered to have limit of G mag <16 and d<20
filtered = table[
    (table["phot_g_mean_mag"] <= 16) &
    (table["distance_pc"] <= 20)
]

print("Total sources before filtering:", len(table))
print("Sources after filtering:", len(filtered))

#subset = filtered.head(5)
subset = filtered
rows = []

for i, (id, ra, dec) in enumerate(zip(subset["source_id"], subset["ra"], subset["dec"]), start=1):
    print(f"{i}. Checking source_id {id} (RA={ra}, DEC={dec})")

    try:
        coord = f"{ra} {dec}"

        # Looks specifically for FFI (TESSCut)
        search_ffi = lk.search_tesscut(coord)
        ffi_avail = len(search_ffi) > 0

        # Looks specifically for SPOC (target pixel files)
        spoc = lk.search_targetpixelfile(
            f"Gaia DR3 {id}",
            mission="TESS",
            author="SPOC"
        )
        spoc_avail = len(spoc) > 0

        if not ffi_avail and not spoc_avail:
            rows.append({
                "ID": id,
                "DataType": None,
                "Sector": None,
                "Exposure_Time": None,
                "FFI_Avail": False,
                "SPOC_Avail": False
            })
            continue

        # Adds the rows for FFI
        if ffi_avail:
            for values in search_ffi:
                tab = values.table

                sector = None
                if "sequence_number" in tab.colnames:
                    sector = tab["sequence_number"][0]
                elif "sector" in tab.colnames:
                    sector = tab["sector"][0]

                exptime = tab["exptime"][0] if "exptime" in tab.colnames else None

                rows.append({
                    "ID": id,
                    "DataType": "FFI",
                    "Sector": sector,
                    "Exposure_Time": exptime,
                    "FFI_Avail": True,
                    "SPOC_Avail": spoc_avail
                })

        # Adds the rows for SPOC
        if spoc_avail:
            for values in spoc:
                tab = values.table

                sector = get_sector_from_tab(tab)

                # exptime should be in the table for search_targetpixelfile results
                exptime = tab["exptime"][0] if "exptime" in tab.colnames else None

                rows.append({
                    "ID": id,
                    "DataType": "SPOC",
                    "Sector": sector,
                    "Exposure_Time": exptime,
                    "FFI_Avail": ffi_avail,
                    "SPOC_Avail": True
                })

    except Exception as e:
        print(f"Error for {id}: {e}")
        rows.append({
            "ID": id,
            "DataType": None,
            "Sector": None,
            "Exposure_Time": None,
            "FFI_Avail": False,
            "SPOC_Avail": False
        })

out = pd.DataFrame(rows)
display(out)

out.to_csv("tess_id_sector_exptime_G16d20_all_filtered_UPDATED_SEC.csv", index=False)
print("Saved in tess_id_sector_exptime_G16d20_all_filtered_UPDATED_SEC.csv")

Total sources before filtering: 140813
Sources after filtering: 736
1. Checking source_id 769456276704128 (RA=47.51489911594037, DEC=2.572769511017299)
2. Checking source_id 16302463200535040 (RA=50.8422709188759, DEC=11.686387390947743)
3. Checking source_id 18986817760556416 (RA=39.82435828918509, DEC=7.470816071340625)
4. Checking source_id 35398295820372864 (RA=43.358915254728714, DEC=17.407883277761023)
5. Checking source_id 57739208163471744 (RA=51.68738385482385, DEC=19.243802626944703)
6. Checking source_id 68553931516671488 (RA=54.87437762176911, DEC=24.96824115907829)
7. Checking source_id 72117556076986368 (RA=33.98650746472387, DEC=10.254962202598763)
8. Checking source_id 72354810070468224 (RA=33.192827917024836, DEC=10.547975698321418)
9. Checking source_id 89593331327905536 (RA=39.183682325426595, DEC=22.67227965316612)
10. Checking source_id 91196316201965184 (RA=29.56508818927173, DEC=18.12063665648874)
11. Checking source_id 97334889619799168 (RA=27.85070481391559, DEC=21.39275062405243)
12. Checking source_id 97993497084921984 (RA=27.018206566174985, DEC=21.205767467992107)
13. Checking source_id 117709729140217216 (RA=52.20764798129931, DEC=26.48616945277209)
14. Checking source_id 308828253324985984 (RA=19.459213398032063, DEC=28.669329862628036)
15. Checking source_id 327944328126649856 (RA=34.29473704167926, DEC=35.44121898612927)
16. Checking source_id 348020242217448576 (RA=24.208998277705287, DEC=41.39055046681678)
17. Checking source_id 373838214051410816 (RA=14.504225894844094, DEC=39.31987471822514)
18. Checking source_id 569821974111727744 (RA=63.51645882603903, DEC=82.25759093058488)
19. Checking source_id 598180646733241216 (RA=130.7186251598315, DEC=9.55037430644196)
20. Checking source_id 605079910398496640 (RA=134.08122584963937, DEC=12.662731415781227)
21. Checking source_id 615779464207025152 (RA=150.6775798896445, DEC=14.985896812309678)
22. Checking source_id 617982090939470464 (RA=144.87402457514528, DEC=14.646793438572836)
23. Checking source_id 619440661833351040 (RA=147.20907756971008, DEC=15.646815201966763)
24. Checking source_id 622339455521105280 (RA=153.97610368902318, DEC=17.490880663782907)
25. Checking source_id 628080246633611520 (RA=148.4782397121578, DEC=20.948079178895128)
26. Checking source_id 628865130046268672 (RA=153.72046302348045, DEC=21.395135245402663)
27. Checking source_id 641821259671808896 (RA=149.11007978867167, DEC=22.64914689456202)
28. Checking source_id 646255246469567232 (RA=143.20029276934693, DEC=26.994404086268727)
29. Checking source_id 646818024623804416 (RA=145.97884036380384, DEC=26.96855261959639)
30. Checking source_id 656328319169788032 (RA=125.48480046053642, DEC=17.816229744725995)
31. Checking source_id 666988221840703232 (RA=118.10053540514112, DEC=16.20259810649539)
32. Checking source_id 696501553469122304 (RA=144.84494415736484, DEC=29.72384628471681)
33. Checking source_id 700732474214292096 (RA=140.62274853344667, DEC=31.462808505180774)
34. Checking source_id 704966762213039488 (RA=133.16783218849463, DEC=28.315252421854034)
35. Checking source_id 706300980915871616 (RA=129.8558619958561, DEC=29.888835566188664)
36. Checking source_id 709563717249089792 (RA=130.06766840125894, DEC=31.45242630658037)
37. Checking source_id 741275934694972800 (RA=155.0009571782997, DEC=28.95264696593352)
38. Checking source_id 753585104807022080 (RA=152.17654982392168, DEC=35.5475756414613)
39. Checking source_id 758200712885953280 (RA=167.96464803741873, DEC=33.53697074560677)
40. Checking source_id 763973668623022464 (RA=170.67963052649262, DEC=37.93015926691593)
41. Checking source_id 764072689093638528 (RA=171.01885964390104, DEC=38.13629424820036)
42. Checking source_id 765038614353808768 (RA=167.20415886992, DEC=39.9194772969731)
43. Checking source_id 772430527947893632 (RA=175.43249920718978, DEC=42.75157375642011)
44. Checking source_id 788357434914248448 (RA=169.87953937654436, DEC=46.69261027622741)
45. Checking source_id 795434510226597760 (RA=148.93144985906537, DEC=35.36021293511174)
46. Checking source_id 806039471675754112 (RA=155.96718909727664, DEC=43.892552567095734)
47. Checking source_id 835748825612078848 (RA=161.3117904571487, DEC=49.690721671495034)
48. Checking source_id 844922257281519744 (RA=174.0685159675205, DEC=56.39999642341029)
49. Checking source_id 847330325186182912 (RA=156.51100654305094, DEC=50.45359969774126)
50. Checking source_id 868209703104242048 (RA=114.62216862501052, DEC=24.0019731597431)
51. Checking source_id 898506166187633280 (RA=112.98739022537632, DEC=36.22866483400494)
52. Checking source_id 907066684548911872 (RA=121.70088015375909, DEC=36.75903456662503)
53. Checking source_id 912087093295958144 (RA=132.2838763210011, DEC=39.605842131988005)
54. Checking source_id 921952117778154240 (RA=121.72910641215296, DEC=42.29129375007699)
55. Checking source_id 978338677527779200 (RA=106.90707091399624, DEC=48.68573489188429)
56. Checking source_id 982389862479141376 (RA=116.80766643936455, DEC=50.344381181505526)
57. Checking source_id 985610542491481984 (RA=113.84028667733696, DEC=54.849773078642905)
58. Checking source_id 1016640817918422272 (RA=135.93078072117314, DEC=52.04697454057216)
59. Checking source_id 1017783146073299328 (RA=134.8975225560541, DEC=53.72986152233806)
60. Checking source_id 1038195201485531776 (RA=139.44184149237842, DEC=58.417419402224134)
61. Checking source_id 1041395708035677312 (RA=132.1273646145831, DEC=61.14977484752529)
62. Checking source_id 1056860923195191936 (RA=179.45874784377168, DEC=66.56193013560468)
63. Checking source_id 1070519572033023232 (RA=150.52360646224852, DEC=69.75710578236257)
64. Checking source_id 1071851527289746176 (RA=149.9387380823067, DEC=72.20037314188153)
65. Checking source_id 1073206263054159104 (RA=158.84150877915906, DEC=69.446793871661)
66. Checking source_id 1083242222939300480 (RA=122.07423466781546, DEC=58.519009709876286)
67. Checking source_id 1117132130541140736 (RA=135.7225460569734, DEC=68.06446038566975)
68. Checking source_id 1123681096674583552 (RA=134.9987609031543, DEC=72.95993278581588)
69. Checking source_id 1125337098625077504 (RA=135.05447462137312, DEC=75.37236190179152)
70. Checking source_id 1134155113160270720 (RA=150.2915837503259, DEC=81.15484257034134)
71. Checking source_id 1138963758544545280 (RA=123.42723031947163, DEC=79.30137045178125)
72. Checking source_id 1139642706975159552 (RA=105.87490601885828, DEC=76.77275818273984)
73. Checking source_id 1149245394855341440 (RA=128.05827749211943, DEC=84.40965990897092)
74. Checking source_id 1149727977380998784 (RA=109.99020696216758, DEC=84.07690200527787)
75. Checking source_id 1155910118945913728 (RA=229.9411845112153, DEC=4.660000235225668)
76. Checking source_id 1159745146784043264 (RA=225.33415504486476, DEC=5.546794272660181)
77. Checking source_id 1165479168642900992 (RA=232.625560005462, DEC=9.434551385099413)
78. Checking source_id 1175938925836488448 (RA=216.2357318474915, DEC=8.888339518893313)
79. Checking source_id 1188693088919917952 (RA=224.109214809204, DEC=17.91876929997926)
80. Checking source_id 1209432042883668480 (RA=233.71072951618376, DEC=18.00196306214209)
81. Checking source_id 1212774313804554752 (RA=227.52009755174592, DEC=19.355624418458618)
82. Checking source_id 1214076070761755008 (RA=229.63109374468223, DEC=20.60824922657203)
83. Checking source_id 1227705135863076864 (RA=217.0156415738216, DEC=13.934833566564166)
84. Checking source_id 1235125877277843840 (RA=218.04584697379087, DEC=16.013385429054974)
85. Checking source_id 1256071505067560704 (RA=216.39418554867095, DEC=25.668004465226957)
86. Checking source_id 1276940648080594048 (RA=231.43145117487225, DEC=31.202217035964036)
87. Checking source_id 1282073374518833152 (RA=223.79801910728224, DEC=30.11225414386347)
88. Checking source_id 1282632682337912832 (RA=221.0710869095232, DEC=30.0357734179162)
89. Checking source_id 1320545217653492864 (RA=240.4298070154365, DEC=30.181367389399146)
90. Checking source_id 1320795047312113152 (RA=237.83964101743064, DEC=29.516446364274)
91. Checking source_id 1326893351115617024 (RA=251.6292959257543, DEC=34.580290245898446)
92. Checking source_id 1327654969076730880 (RA=249.25489571253425, DEC=35.593526440532905)
93. Checking source_id 1332966881549315456 (RA=247.8274448005916, DEC=40.86572384148289)
94. Checking source_id 1341113541156480768 (RA=257.89598966788463, DEC=38.44254560681901)
95. Checking source_id 1350714133093019904 (RA=269.4622611288724, DEC=46.59121608783237)
96. Checking source_id 1355264565043431040 (RA=257.3834721191679, DEC=43.680105808986085)
97. Checking source_id 1372215976327300480 (RA=239.57754339419824, DEC=35.408158262718665)
98. Checking source_id 1379500928055726848 (RA=241.20868366880867, DEC=39.16016523606519)
99. Checking source_id 1388684770725399296 (RA=229.1684830144717, DEC=39.17983717431188)
100. Checking source_id 1409902905599851392 (RA=247.8661959969435, DEC=47.17314755249796)
101. Checking source_id 1412645602995521920 (RA=255.85040248888004, DEC=51.40906417008386)
102. Checking source_id 1416123117756120960 (RA=259.41085537136235, DEC=52.40531634143529)
103. Checking source_id 1431176943768690816 (RA=248.57558060807455, DEC=57.16757381763237)
104. Checking source_id 1443068608699851008 (RA=202.9594075396803, DEC=23.389206653452536)
105. Checking source_id 1451197916638959872 (RA=209.71769182511895, DEC=27.87062339863821)
106. Checking source_id 1461049369026235904 (RA=197.8380339246302, DEC=28.542881140686458)
107. Checking source_id 1461125613285603840 (RA=197.3939952563072, DEC=28.984194794735036)
108. Checking source_id 1461507384337635840 (RA=199.13310731831825, DEC=27.87596984084402)
109. Checking source_id 1466009540856759680 (RA=196.7105478174373, DEC=30.84621621605227)
110. Checking source_id 1477762319428998400 (RA=214.94519097573385, DEC=31.617589844728105)
111. Checking source_id 1483977656798789120 (RA=213.98497602510355, DEC=36.27839269007434)
112. Checking source_id 1489294551432850560 (RA=223.06692178226328, DEC=41.32158904033235)
113. Checking source_id 1495487688115551744 (RA=207.7132354836552, DEC=36.73846792755987)
114. Checking source_id 1505209054532280960 (RA=214.34237220584717, DEC=45.42936021377157)
115. Checking source_id 1518564478676515712 (RA=189.11736017524785, DEC=35.19971562564376)
116. Checking source_id 1534239391319888384 (RA=190.70457462086816, DEC=41.8966090688773)
117. Checking source_id 1573896198753650944 (RA=181.4021839662666, DEC=56.394863843666194)
118. Checking source_id 1587576253706543232 (RA=228.15665054327465, DEC=45.73119308728785)
119. Checking source_id 1595170236922937728 (RA=233.51466659726952, DEC=51.368562240881666)
120. Checking source_id 1603272950424941440 (RA=233.8585360449291, DEC=60.08470833271646)
121. Checking source_id 1603611493015735296 (RA=218.05659204654648, DEC=49.651165748848456)
122. Checking source_id 1604901876901703168 (RA=215.76332804586107, DEC=51.77600462861712)
123. Checking source_id 1616853430856547968 (RA=221.1035124404749, DEC=58.287786919281984)
124. Checking source_id 1618330448634358400 (RA=216.78665388902056, DEC=60.941040648347105)
125. Checking source_id 1631591147276525696 (RA=253.2075718369321, DEC=63.07812356967455)
126. Checking source_id 1638180413086979840 (RA=269.3142709072523, DEC=70.70178301936559)
127. Checking source_id 1648484868558988544 (RA=250.0827910688673, DEC=67.60294000951913)
128. Checking source_id 1650819612781643392 (RA=262.0450109199984, DEC=71.14096957434231)
129. Checking source_id 1655482224982135040 (RA=255.4369477446704, DEC=74.19781368444308)
130. Checking source_id 1656076893269778432 (RA=265.6823444683212, DEC=75.62282031158797)
131. Checking source_id 1669449084967071872 (RA=220.58662378500725, DEC=66.05561864866871)
132. Checking source_id 1678489647527832320 (RA=198.5949485165658, DEC=66.37603764196513)
133. Checking source_id 1683228851880827136 (RA=185.44336261603965, DEC=68.2687045566608)
134. Checking source_id 1683609076745527680 (RA=181.3678591223992, DEC=69.53936644393914)
135. Checking source_id 1683677624423753472 (RA=181.73532846482885, DEC=70.13042280787634)
136. Checking source_id 1701585301586363904 (RA=219.30529832556255, DEC=75.61151710152384)
137. Checking source_id 1701602958196086528 (RA=217.80244124264595, DEC=75.44491958012206)
138. Checking source_id 1710948192852697600 (RA=262.8122775792793, DEC=82.09105560054718)
139. Checking source_id 1714831771000745344 (RA=208.41629245213292, DEC=77.61886343809084)
140. Checking source_id 1735245338242513536 (RA=310.8514381606976, DEC=4.764685971871537)
141. Checking source_id 1768825106253209984 (RA=327.9522183313725, DEC=13.603838612745625)
142. Checking source_id 1773485214494929536 (RA=326.0387863765124, DEC=17.059722272765484)
143. Checking source_id 1773497412196823680 (RA=326.0343872670299, DEC=17.077038166155283)
144. Checking source_id 1776179945695834368 (RA=331.59592583103495, DEC=17.372810486070932)
145. Checking source_id 1890425839540910848 (RA=341.97779535087403, DEC=31.871783828604855)
146. Checking source_id 1893189736896880640 (RA=330.306566078579, DEC=28.30710892040449)
147. Checking source_id 2110165780975185792 (RA=278.6530518091756, DEC=40.12307795291824)
148. Checking source_id 2118429538570209920 (RA=278.86660840698516, DEC=45.762979999016885)
149. Checking source_id 2256631484392164736 (RA=277.8407516553966, DEC=64.9039850767494)
150. Checking source_id 2257597439718033536 (RA=274.74325647947336, DEC=66.19061665488063)
151. Checking source_id 2294281163411732736 (RA=278.9690777068371, DEC=80.09526285745366)
152. Checking source_id 2302668860880387072 (RA=289.10161012405797, DEC=84.22869527150492)
153. Checking source_id 2312376723918929920 (RA=356.6576476677058, DEC=-34.16710787919001)
154. Checking source_id 2325083848520121856 (RA=352.65810345342345, DEC=-33.30768786716094)
155. Checking source_id 2368212771939556992 (RA=3.9914280244393505, DEC=-16.61597822404432)
156. Checking source_id 2393563872239260928 (RA=351.86040963011595, DEC=-17.69494218902131)
157. Checking source_id 2395413147718069504 (RA=354.53268726381896, DEC=-16.23651363027235)
158. Checking source_id 2400808245117576704 (RA=339.69068815030255, DEC=-20.614689446269768)
159. Checking source_id 2407340615496379008 (RA=352.10236185712836, DEC=-15.924966875091195)
160. Checking source_id 2407573643242037888 (RA=351.0712300150862, DEC=-15.373269236906095)
161. Checking source_id 2414623952318068224 (RA=1.2404631704419242, DEC=-17.160303653461234)
162. Checking source_id 2420649585275393920 (RA=356.83925393911727, DEC=-12.343968535630694)
163. Checking source_id 2421080250237097344 (RA=359.33671447287855, DEC=-12.980168707826213)
164. Checking source_id 2421080250237474176 (RA=359.3316119129798, DEC=-12.977870560152498)
165. Checking source_id 2450599697900838912 (RA=23.49187379987124, DEC=-17.640773463135556)
166. Checking source_id 2451701339832959232 (RA=22.623854394641025, DEC=-16.40544797329293)
167. Checking source_id 2452167910719793664 (RA=22.16461895808497, DEC=-14.96810617489612)
168. Checking source_id 2453195851012123904 (RA=26.781623953195012, DEC=-14.411598506271671)
169. Checking source_id 2457862762476854656 (RA=20.825063748419577, DEC=-12.938209952737276)
170. Checking source_id 2461728194387221504 (RA=30.434023239076055, DEC=-10.290317824118802)
171. Checking source_id 2467242352575094784 (RA=25.994623558557567, DEC=-6.913531290688611)
172. Checking source_id 2467732906559754496 (RA=27.769525129441792, DEC=-6.119239184112927)
173. Checking source_id 2468929243931522304 (RA=17.57395028608209, DEC=-11.855370704147928)
174. Checking source_id 2486388560866377728 (RA=33.1190109988742, DEC=-8.071574920874733)
175. Checking source_id 2492866780297999232 (RA=33.554613532263986, DEC=-3.96280045849318)
176. Checking source_id 2497858563088120448 (RA=44.01738337380463, DEC=-0.608877262589059)
177. Checking source_id 2507016253701863040 (RA=33.23006351010599, DEC=0.0048112291822607)
178. Checking source_id 2514052131687080192 (RA=35.19339905103572, DEC=2.9757995116747007)
179. Checking source_id 2526788363283721984 (RA=8.93379610467678, DEC=-5.687454587970094)
180. Checking source_id 2528227035593363840 (RA=8.221728419110557, DEC=-4.569270815894982)
181. Checking source_id 2537831170877143552 (RA=17.050154984643736, DEC=0.4641340321772402)
182. Checking source_id 2614071100988460544 (RA=331.39766600457193, DEC=-11.075490632741356)
183. Checking source_id 2616132101175335936 (RA=334.3256811695789, DEC=-8.806486660337637)
184. Checking source_id 2618333804489940992 (RA=329.3036181978969, DEC=-9.05802459659516)
185. Checking source_id 2620145937091715072 (RA=331.54090391057207, DEC=-7.394198350555103)
186. Checking source_id 2631857350835259392 (RA=348.9785213795388, DEC=-6.463096715840339)
187. Checking source_id 2668249051115631232 (RA=326.2524726236367, DEC=-5.788973523692696)
188. Checking source_id 2669873515120908544 (RA=326.82387294144644, DEC=-4.744613685896646)
189. Checking source_id 2670661109044300160 (RA=323.4543418919189, DEC=-6.8551113020513075)
190. Checking source_id 2673992663636347520 (RA=327.8635523883638, DEC=-1.4538921085791252)
191. Checking source_id 2681122098893985408 (RA=326.6718481188171, DEC=-0.1755173375144743)
192. Checking source_id 2683209044978079616 (RA=331.6251935434858, DEC=2.375809039939923)
193. Checking source_id 2683714304930755712 (RA=331.69527845431674, DEC=3.4163173765574197)
194. Checking source_id 2688566793341935360 (RA=323.4546452148779, DEC=1.7791345250832382)
195. Checking source_id 2705611005983192320 (RA=338.6921084252097, DEC=4.044371189279514)
196. Checking source_id 2708839657453920256 (RA=335.0565229770535, DEC=6.72679864112854)
197. Checking source_id 2710189960812052736 (RA=336.76251116872623, DEC=6.825575040979833)
198. Checking source_id 2719512513745949184 (RA=342.0961253423981, DEC=12.536167811623086)
199. Checking source_id 2775987485397299072 (RA=11.08183889277884, DEC=12.616598050741125)
200. Checking source_id 2799992744809482112 (RA=6.985243946351337, DEC=22.324902794590333)
201. Checking source_id 2800823799506215168 (RA=6.33469184849611, DEC=22.884358347500047)
202. Checking source_id 2801216123294143360 (RA=5.8655364124677485, DEC=24.30736066735532)
203. Checking source_id 2819781274051096192 (RA=354.4016087764225, DEC=16.367299189308994)
204. Checking source_id 2824770686019004032 (RA=352.9716753030632, DEC=19.937313746866927)
205. Checking source_id 2830318679957189632 (RA=342.22734755350785, DEC=18.332476624663535)
206. Checking source_id 2836510961942677376 (RA=340.84852132214786, DEC=22.138349954479125)
207. Checking source_id 2856874535763703680 (RA=4.725287520277892, DEC=27.813355639663538)
208. Checking source_id 2859027409595355776 (RA=6.148344264210615, DEC=30.041581512034053)
209. Checking source_id 2863419584886542080 (RA=5.128239996638605, DEC=33.08128045387165)
210. Checking source_id 2864382138598091648 (RA=353.76630482328295, DEC=25.250191671633328)
211. Checking source_id 2866851710433326208 (RA=356.5590246187754, DEC=28.43471215134376)
212. Checking source_id 2868199402451064064 (RA=355.7180385472229, DEC=30.82137349573688)
213. Checking source_id 2872988394066393344 (RA=355.0954866644879, DEC=34.55437676255151)
214. Checking source_id 2881313793031884544 (RA=358.71365830063576, DEC=38.52633962632873)
215. Checking source_id 2886233695250041216 (RA=91.21742524933885, DEC=-34.558412822381825)
216. Checking source_id 2891695137006940544 (RA=94.44578372665914, DEC=-34.01941716022002)
217. Checking source_id 2905516483501493120 (RA=82.7698222187872, DEC=-30.19782913482597)
218. Checking source_id 2907884728469088384 (RA=86.45936920758024, DEC=-27.16289618149821)
219. Checking source_id 2911981886751531648 (RA=91.9313221336463, DEC=-25.745763611837013)
220. Checking source_id 2954555801611979648 (RA=79.65245423379399, DEC=-28.69991906819153)
221. Checking source_id 3013672487388307456 (RA=83.84028163560048, DEC=-9.519503846133947)

,ID,DataType,Sector,Exposure_Time,FFI_Avail,SPOC_Avail
0,769456276704128,FFI,4.0,1425.599419,True,True
1,769456276704128,FFI,31.0,475.199790,True,True
2,769456276704128,SPOC,4.0,120.000000,True,True
3,769456276704128,SPOC,31.0,120.000000,True,True
4,16302463200535040,FFI,31.0,475.199790,True,True
...,...,...,...,...,...,...
8950,6734485286788609664,SPOC,93.0,120.000000,True,True
8951,6759481141756109056,FFI,13.0,1425.599392,True,True
8952,6759481141756109056,FFI,27.0,475.199782,True,True
8953,6759481141756109056,FFI,92.0,158.399926,True,True
8954,6759481141756109056,SPOC,27.0,120.000000,True,True

Saved in tess_id_sector_exptime_G16d20_all_filtered_UPDATED_SEC.csv